<script lang="ts">
	/**
	 * Bug Report Dialog
	 *
	 * Full form for submitting a bug report with:
	 * - Category selection
	 * - Severity selection
	 * - Title and description
	 * - Optional screenshot upload
	 * - Auto-captured context display
	 */
	import * as Dialog from '$lib/components/ui/dialog';
	import { Button } from '$lib/components/ui/button';
	import { Input } from '$lib/components/ui/input';
	import { Textarea } from '$lib/components/ui/textarea';
	import { Label } from '$lib/components/ui/label';
	import * as RadioGroup from '$lib/components/ui/radio-group';
	import MySelect from '$lib/components/MySelect.svelte';
	import { toaster } from '$lib/stores/toaster.svelte';
	import { getFreezeDetectionContext } from '$lib/utils/freezeDetection';
	import type { BugReportCategory, BugReportSeverity } from '$lib/types/bug-reports';
	import {
		BUG_REPORT_CATEGORY_LABELS,
		BUG_REPORT_CATEGORY_ICONS,
		BUG_REPORT_SEVERITY_LABELS
	} from '$lib/types/bug-reports';
	import { Loader2, Upload, X } from 'lucide-svelte';

	interface Props {
		open: boolean;
		onOpenChange: (open: boolean) => void;
		autoGenerated?: boolean;
		initialDescription?: string;
	}

	let {
		open = $bindable(),
		onOpenChange,
		autoGenerated = false,
		initialDescription = ''
	}: Props = $props();

	// Form state
	let category = $state<BugReportCategory>('bug');
	let severity = $state<BugReportSeverity>('medium');
	let title = $state('');
	let description = $state(initialDescription);
	let screenshotFile = $state<File | null>(null);
	let screenshotPreview = $state<string | null>(null);
	let isSubmitting = $state(false);

	// Category options for MySelect
	const categoryItems = Object.entries(BUG_REPORT_CATEGORY_LABELS).map(([value, label]) => ({
		value,
		label: `${BUG_REPORT_CATEGORY_ICONS[value as BugReportCategory]} ${label}`
	}));

	// Validation
	const titleValid = $derived(title.trim().length >= 5 && title.trim().length <= 200);
	const descriptionValid = $derived(
		description.trim().length >= 20 && description.trim().length <= 5000
	);
	const isValid = $derived(titleValid && descriptionValid);

	// Character counts
	const titleLength = $derived(title.length);
	const descriptionLength = $derived(description.length);

	// Context capture
	const pageUrl = $derived(typeof window !== 'undefined' ? window.location.href : '');
	const userAgent = $derived(typeof navigator !== 'undefined' ? navigator.userAgent : '');
	const viewportSize = $derived(
		typeof window !== 'undefined' ? `${window.innerWidth}x${window.innerHeight}` : ''
	);

	// Handle screenshot selection
	function handleFileSelect(event: Event) {
		const input = event.target as HTMLInputElement;
		const file = input.files?.[0];

		if (!file) return;

		// Validate file
		if (file.size > 5 * 1024 * 1024) {
			toaster.error('Le fichier ne doit pas dépasser 5 Mo');
			return;
		}

		if (!['image/jpeg', 'image/png', 'image/gif', 'image/webp'].includes(file.type)) {
			toaster.error('Format non supporté. Utilisez JPEG, PNG, GIF ou WebP.');
			return;
		}

		screenshotFile = file;

		// Create preview
		const reader = new FileReader();
		reader.onload = (e) => {
			screenshotPreview = e.target?.result as string;
		};
		reader.readAsDataURL(file);
	}

	function removeScreenshot() {
		screenshotFile = null;
		screenshotPreview = null;
	}

	// Submit handler
	async function handleSubmit() {
		if (!isValid || isSubmitting) return;

		isSubmitting = true;

		try {
			// Get freeze detection context
			const freezeContext = getFreezeDetectionContext();

			// Create the bug report
			const response = await fetch('/api/bug-reports', {
				method: 'POST',
				headers: { 'Content-Type': 'application/json' },
				body: JSON.stringify({
					category,
					severity,
					title: title.trim(),
					description: description.trim(),
					pageUrl,
					userAgent,
					viewportSize,
					sessionContext: {
						...freezeContext,
						capturedAt: new Date().toISOString()
					},
					autoGenerated
				})
			});

			if (!response.ok) {
				const error = await response.json();
				throw new Error(error.message || 'Erreur lors de la création du rapport');
			}

			const { report } = await response.json();

			// Upload screenshot if provided
			if (screenshotFile && report.id) {
				const formData = new FormData();
				formData.append('image', screenshotFile);

				const uploadResponse = await fetch(`/api/bug-reports/${report.id}/screenshot`, {
					method: 'POST',
					body: formData
				});

				if (!uploadResponse.ok) {
					console.error('Failed to upload screenshot');
					// Don't fail the whole operation for screenshot upload failure
				}
			}

			toaster.success('Rapport envoyé avec succès');
			resetForm();
			onOpenChange(false);
		} catch (error) {
			const message = error instanceof Error ? error.message : 'Une erreur est survenue';
			toaster.error(message);
		} finally {
			isSubmitting = false;
		}
	}

	function resetForm() {
		category = 'bug';
		severity = 'medium';
		title = '';
		description = initialDescription;
		screenshotFile = null;
		screenshotPreview = null;
	}

	// Reset form when dialog closes
	$effect(() => {
		if (!open) {
			// Delay reset to allow close animation
			setTimeout(resetForm, 300);
		}
	});
</script>

<Dialog.Root bind:open {onOpenChange}>
	<Dialog.Content class="max-h-[90vh] max-w-lg overflow-y-auto">
		<Dialog.Header>
			<Dialog.Title class="flex items-center gap-2">
				<span class="text-xl">🐜</span>
				Signaler un problème
			</Dialog.Title>
			<Dialog.Description>
				Aidez-nous à améliorer l'application en signalant les problèmes que vous rencontrez.
			</Dialog.Description>
		</Dialog.Header>

		<form
			onsubmit={(e) => {
				e.preventDefault();
				handleSubmit();
			}}
			class="space-y-4"
		>
			<!-- Category -->
			<div class="space-y-2">
				<Label for="category">Type de problème</Label>
				<MySelect type="single" bind:value={category} items={categoryItems} />
			</div>

			<!-- Severity -->
			<div class="space-y-2">
				<Label>Importance</Label>
				<RadioGroup.Root bind:value={severity} class="flex flex-wrap gap-3">
					{#each Object.entries(BUG_REPORT_SEVERITY_LABELS) as [value, label] (value)}
						<div class="flex items-center gap-2">
							<RadioGroup.Item {value} id={`severity-${value}`} />
							<Label for={`severity-${value}`} class="cursor-pointer font-normal">
								{label}
							</Label>
						</div>
					{/each}
				</RadioGroup.Root>
			</div>

			<!-- Title -->
			<div class="space-y-2">
				<Label for="title">Titre</Label>
				<Input
					id="title"
					bind:value={title}
					placeholder="Résumez le problème en quelques mots..."
					disabled={isSubmitting}
					aria-invalid={title.length > 0 && !titleValid}
				/>
				<p class="text-xs text-muted-foreground">
					{titleLength} / 200 caractères
					{#if title.length > 0 && title.length < 5}
						<span class="text-destructive">(minimum 5)</span>
					{/if}
				</p>
			</div>

			<!-- Description -->
			<div class="space-y-2">
				<Label for="description">Description</Label>
				<Textarea
					id="description"
					bind:value={description}
					placeholder="Décrivez le problème en détail. Quelles actions avez-vous effectuées ? Que s'est-il passé ?"
					rows={5}
					disabled={isSubmitting}
					aria-invalid={description.length > 0 && !descriptionValid}
				/>
				<p class="text-xs text-muted-foreground">
					{descriptionLength} / 5000 caractères
					{#if description.length > 0 && description.length < 20}
						<span class="text-destructive">(minimum 20)</span>
					{/if}
				</p>
			</div>

			<!-- Screenshot -->
			<div class="space-y-2">
				<Label>Capture d'écran (optionnel)</Label>
				{#if screenshotPreview}
					<div class="relative inline-block">
						<img
							src={screenshotPreview}
							alt="Aperçu de la capture"
							class="max-h-32 rounded border"
						/>
						<button
							type="button"
							onclick={removeScreenshot}
							class="absolute -top-2 -right-2 rounded-full bg-destructive p-1 text-destructive-foreground hover:bg-destructive/90"
							aria-label="Supprimer la capture"
						>
							<X class="h-3 w-3" />
						</button>
					</div>
				{:else}
					<label
						class="flex cursor-pointer items-center justify-center gap-2 rounded-lg border-2 border-dashed border-muted-foreground/25 p-4 transition-colors hover:border-muted-foreground/50"
					>
						<Upload class="h-5 w-5 text-muted-foreground" />
						<span class="text-sm text-muted-foreground">Cliquer pour ajouter une capture</span>
						<input
							type="file"
							accept="image/jpeg,image/png,image/gif,image/webp"
							onchange={handleFileSelect}
							class="hidden"
							disabled={isSubmitting}
						/>
					</label>
				{/if}
			</div>

			<!-- Context info (readonly) -->
			<div class="rounded-lg bg-muted/50 p-3 text-xs text-muted-foreground">
				<p class="mb-1 font-medium">Contexte capturé automatiquement :</p>
				<ul class="space-y-0.5">
					<li>• Page : {pageUrl ? new URL(pageUrl).pathname : 'N/A'}</li>
					<li>• Écran : {viewportSize || 'N/A'}</li>
					<li>• Navigateur : {userAgent ? userAgent.split(' ').pop() : 'N/A'}</li>
				</ul>
			</div>
		</form>

		<Dialog.Footer class="gap-2 sm:gap-0">
			<Button variant="outline" onclick={() => onOpenChange(false)} disabled={isSubmitting}>
				Annuler
			</Button>
			<Button onclick={handleSubmit} disabled={!isValid || isSubmitting}>
				{#if isSubmitting}
					<Loader2 class="mr-2 h-4 w-4 animate-spin" />
					Envoi...
				{:else}
					Envoyer
				{/if}
			</Button>
		</Dialog.Footer>
	</Dialog.Content>
</Dialog.Root>
