<script lang="ts">
	/**
	 * Freeze Report Prompt
	 *
	 * Shown when a freeze > 15s is detected.
	 * Offers to send an automatic bug report.
	 */
	import * as Dialog from '$lib/components/ui/dialog';
	import { Button } from '$lib/components/ui/button';
	import { toaster } from '$lib/stores/toaster.svelte';
	import { getFreezeDetectionContext } from '$lib/utils/freezeDetection';
	import { Loader2, AlertTriangle } from 'lucide-svelte';

	interface Props {
		open: boolean;
		freezeDuration: number;
		onOpenChange: (open: boolean) => void;
	}

	let { open = $bindable(), freezeDuration, onOpenChange }: Props = $props();

	let isSubmitting = $state(false);

	function formatDuration(ms: number): string {
		if (ms >= 1000) {
			return `${(ms / 1000).toFixed(1)} secondes`;
		}
		return `${ms} ms`;
	}

	async function submitAutomaticReport() {
		if (isSubmitting) return;
		isSubmitting = true;

		try {
			const context = getFreezeDetectionContext();

			const response = await fetch('/api/bug-reports', {
				method: 'POST',
				headers: { 'Content-Type': 'application/json' },
				body: JSON.stringify({
					category: 'bug',
					severity: freezeDuration > 20000 ? 'critical' : 'high',
					title: `Application bloquée pendant ${formatDuration(freezeDuration)}`,
					description: `Rapport automatique : L'application a cessé de répondre pendant ${formatDuration(freezeDuration)}.\n\nCe rapport a été généré automatiquement par le système de détection de freeze.`,
					pageUrl: typeof window !== 'undefined' ? window.location.href : '',
					userAgent: typeof navigator !== 'undefined' ? navigator.userAgent : '',
					viewportSize:
						typeof window !== 'undefined' ? `${window.innerWidth}x${window.innerHeight}` : '',
					sessionContext: {
						...context,
						capturedAt: new Date().toISOString(),
						freezeDuration
					},
					autoGenerated: true
				})
			});

			if (!response.ok) {
				throw new Error('Erreur lors de la création du rapport');
			}

			toaster.success('Rapport envoyé automatiquement. Merci !');
			onOpenChange(false);
		} catch (error) {
			console.error('Failed to submit freeze report:', error);
			toaster.error("Impossible d'envoyer le rapport");
		} finally {
			isSubmitting = false;
		}
	}
</script>

<Dialog.Root bind:open {onOpenChange}>
	<Dialog.Content class="max-w-md">
		<Dialog.Header>
			<Dialog.Title class="flex items-center gap-2">
				<AlertTriangle class="h-5 w-5 text-orange-500" />
				Application bloquée
			</Dialog.Title>
			<Dialog.Description>
				L'application n'a pas répondu pendant <strong>{formatDuration(freezeDuration)}</strong>.
				Voulez-vous envoyer un rapport pour nous aider à corriger ce problème ?
			</Dialog.Description>
		</Dialog.Header>

		<div class="rounded-lg bg-muted p-3 text-sm">
			<p class="font-medium">Informations capturées :</p>
			<ul class="mt-1 list-inside list-disc text-muted-foreground">
				<li>Durée du blocage</li>
				<li>Page visitée</li>
				<li>Dernières actions effectuées</li>
				<li>Erreurs techniques récentes</li>
			</ul>
		</div>

		<Dialog.Footer class="gap-2 sm:gap-0">
			<Button variant="outline" onclick={() => onOpenChange(false)} disabled={isSubmitting}>
				Non merci
			</Button>
			<Button onclick={submitAutomaticReport} disabled={isSubmitting}>
				{#if isSubmitting}
					<Loader2 class="mr-2 h-4 w-4 animate-spin" />
					Envoi...
				{:else}
					Envoyer le rapport
				{/if}
			</Button>
		</Dialog.Footer>
	</Dialog.Content>
</Dialog.Root>
