/**
 * API Endpoint: Create a new Guess Who Math Game
 * Path: POST /api/games/guess-who/create
 *
 * Creates a new game with:
 * - 24 random numbers on the grid (2-99)
 * - Player1 assigned as creator with a secret number
 * - Status set to 'waiting' until opponent joins
 * - Share token generated for invitation link
 */

import { error, json } from '@sveltejs/kit';
import type { RequestHandler } from './$types';
import { requireAuth } from '$lib/server/middleware/auth';
import { createGameSchema } from '$lib/server/validation/guess-who';
import { sanitizePostgresError } from '$lib/server/utils/error-handler';
import { generateGrid, assignSecretNumbers } from '$lib/utils/guess-who';

/**
 * POST /api/games/guess-who/create
 *
 * Creates a new Guess Who game for the authenticated user.
 *
 * **Security**:
 * - Requires authentication (any role can play)
 * - Grid and secret numbers generated server-side
 * - Share token generated by database function
 *
 * **Response**:
 * ```json
 * {
 *   "game": {
 *     "id": "uuid",
 *     "status": "waiting",
 *     "gridNumbers": [...],
 *     "shareToken": "ABCdef123..."
 *   },
 *   "mySecretNumber": 42,
 *   "shareUrl": "/games/guess-who/join/ABCdef123..."
 * }
 * ```
 */
export const POST: RequestHandler = async ({ request, locals, url }) => {
	// Require authentication (any authenticated user can create a game)
	const { user } = await requireAuth(locals);

	// Validate request body (empty but validates structure)
	const body = await request.json().catch(() => ({}));
	const validation = createGameSchema.safeParse(body);

	if (!validation.success) {
		throw error(400, validation.error.issues[0].message);
	}

	// Generate grid of 24 unique numbers (2-99)
	const gridNumbers = generateGrid();

	// Assign secret numbers for both players (player2's will be used when they join)
	const [player1Secret, player2Secret] = assignSecretNumbers(gridNumbers);

	try {
		// Create new game record
		const { data: game, error: createError } = await locals.supabase
			.from('guess_who_games')
			.insert({
				player1_id: user.id,
				status: 'waiting',
				grid_numbers: gridNumbers,
				player1_secret: player1Secret,
				player2_secret: player2Secret // Pre-assigned, will be revealed when player2 joins
			})
			.select('id, status, grid_numbers, share_token, created_at')
			.single();

		if (createError) {
			sanitizePostgresError(createError, 'GUESS_WHO_CREATE');
		}

		if (!game) {
			throw error(500, 'Erreur lors de la creation de la partie');
		}

		// Build share URL
		const shareUrl = `${url.origin}/games/guess-who/join/${game.share_token}`;

		return json({
			game: {
				id: game.id,
				status: game.status,
				gridNumbers: game.grid_numbers,
				shareToken: game.share_token,
				createdAt: game.created_at
			},
			mySecretNumber: player1Secret,
			shareUrl
		});
	} catch (err) {
		sanitizePostgresError(err, 'GUESS_WHO_CREATE');
	}
};
