/**
 * API Endpoint: Create a new Guess Who Math Game
 * Path: POST /api/games/guess-who/create
 *
 * Creates a new game with:
 * - 24 items on the grid (based on selected pack - numbers or polymorphic items)
 * - Player1 assigned as creator with a secret item
 * - Status set to 'waiting' until opponent joins
 * - Share token generated for invitation link
 */

import { error, json } from '@sveltejs/kit';
import type { RequestHandler } from './$types';
import { requireAuth } from '$lib/server/middleware/auth';
import { createGameSchema } from '$lib/server/validation/guess-who';
import { sanitizePostgresError } from '$lib/server/utils/error-handler';
import {
	generateGridForPack,
	assignSecretNumbers,
	generateGridItemsForPack,
	assignSecretItems,
	serializeGrid,
	serializeGridItem
} from '$lib/utils/guess-who';
import { GAME_PACKS, isNumberPack } from '$lib/types/guess-who';

/**
 * POST /api/games/guess-who/create
 *
 * Creates a new Guess Who game for the authenticated user.
 *
 * **Security**:
 * - Requires authentication (any role can play)
 * - Grid and secret items generated server-side
 * - Share token generated by database function
 *
 * **Request Body**:
 * ```json
 * {
 *   "packId": "naturals_medium" // Optional, defaults to naturals_medium
 * }
 * ```
 *
 * **Response**:
 * ```json
 * {
 *   "game": {
 *     "id": "uuid",
 *     "status": "waiting",
 *     "packId": "naturals_medium",
 *     "itemType": "number",
 *     "gridNumbers": [...],     // For number packs
 *     "gridItems": [...],       // For polymorphic packs
 *     "shareToken": "ABCdef123..."
 *   },
 *   "mySecretNumber": 42,       // For number packs
 *   "mySecretItem": {...},      // For polymorphic packs
 *   "shareUrl": "/games/guess-who/join/ABCdef123..."
 * }
 * ```
 */
export const POST: RequestHandler = async ({ request, locals, url }) => {
	// Require authentication (any authenticated user can create a game)
	const { user } = await requireAuth(locals);

	// Validate request body
	const body = await request.json().catch(() => ({}));
	const validation = createGameSchema.safeParse(body);

	if (!validation.success) {
		throw error(400, validation.error.issues[0].message);
	}

	const { packId } = validation.data;
	const pack = GAME_PACKS[packId];

	if (!pack) {
		throw error(400, `Unknown pack: ${packId}`);
	}

	// Check if this is a number pack or polymorphic pack
	const isNumeric = isNumberPack(pack);
	const itemType = pack.itemType;

	try {
		let insertData: Record<string, unknown>;
		let responseData: Record<string, unknown>;

		if (isNumeric) {
			// Number pack: use grid_numbers and player secrets
			const gridNumbers = generateGridForPack(packId);
			const [player1Secret, player2Secret] = assignSecretNumbers(gridNumbers);

			insertData = {
				player1_id: user.id,
				status: 'waiting',
				pack_id: packId,
				item_type: 'number',
				grid_numbers: gridNumbers,
				player1_secret: player1Secret,
				player2_secret: player2Secret
			};

			responseData = {
				mySecretNumber: player1Secret
			};
		} else {
			// Polymorphic pack: use grid_items and secret items
			const gridItems = generateGridItemsForPack(packId);
			const [player1SecretItem, player2SecretItem] = assignSecretItems(gridItems);

			// Also store grid_numbers for backward compatibility (extract numbers if possible)
			// For non-number items, we store an empty array
			const gridNumbers: number[] = [];

			insertData = {
				player1_id: user.id,
				status: 'waiting',
				pack_id: packId,
				item_type: itemType,
				grid_numbers: gridNumbers,
				grid_items: serializeGrid(gridItems),
				player1_secret: null, // Not used for polymorphic
				player2_secret: null,
				player1_secret_item: serializeGridItem(player1SecretItem),
				player2_secret_item: serializeGridItem(player2SecretItem)
			};

			responseData = {
				mySecretItem: player1SecretItem
			};
		}

		// Create new game record
		const { data: game, error: createError } = await locals.supabase
			.from('guess_who_games')
			.insert(insertData)
			.select('id, status, pack_id, item_type, grid_numbers, grid_items, share_token, created_at')
			.single();

		if (createError) {
			sanitizePostgresError(createError, 'GUESS_WHO_CREATE');
		}

		if (!game) {
			throw error(500, 'Erreur lors de la creation de la partie');
		}

		// Build share URL
		const shareUrl = `${url.origin}/games/guess-who/join/${game.share_token}`;

		return json({
			game: {
				id: game.id,
				status: game.status,
				packId: game.pack_id,
				itemType: game.item_type,
				gridNumbers: game.grid_numbers,
				gridItems: game.grid_items,
				shareToken: game.share_token,
				createdAt: game.created_at
			},
			...responseData,
			shareUrl
		});
	} catch (err) {
		sanitizePostgresError(err, 'GUESS_WHO_CREATE');
	}
};
