/**
 * Bug Reports Validation Schemas
 *
 * Zod schemas for validating bug report API requests.
 */

import { z } from 'zod';

// =============================================================================
// Enum Schemas
// =============================================================================

export const bugReportCategorySchema = z.enum(['bug', 'content', 'ux', 'feature', 'other']);

export const bugReportSeveritySchema = z.enum(['low', 'medium', 'high', 'critical']);

export const bugReportStatusSchema = z.enum([
	'pending',
	'acknowledged',
	'in_progress',
	'resolved',
	'wont_fix',
	'duplicate'
]);

// =============================================================================
// Session Context Schemas
// =============================================================================

const capturedErrorSchema = z.object({
	id: z.string(),
	type: z.string(),
	message: z.string(),
	severity: z.string(),
	timestamp: z.string(),
	url: z.string().optional(),
	file_path: z.string().optional(),
	line_number: z.number().int().nonnegative().optional(),
	stack_trace: z.string().optional()
});

const freezeEventSchema = z.object({
	id: z.string(),
	timestamp: z.string(),
	duration: z.number().positive(),
	type: z.enum(['long_task', 'unresponsive']),
	context: z
		.object({
			url: z.string().optional(),
			lastAction: z.string().optional()
		})
		.optional()
});

const userActionSchema = z.object({
	type: z.enum(['click', 'input', 'navigation', 'scroll']),
	target: z.string().max(200),
	timestamp: z.string()
});

const slowRequestSchema = z.object({
	url: z.string(),
	duration: z.number().positive(),
	status: z.number().int()
});

const webVitalsSchema = z.object({
	LCP: z.number().optional(),
	FID: z.number().optional(),
	CLS: z.number().optional(),
	FCP: z.number().optional(),
	TTFB: z.number().optional(),
	INP: z.number().optional()
});

const sessionContextSchema = z.object({
	capturedAt: z.string().optional(),
	recentErrors: z.array(capturedErrorSchema).max(20).optional(),
	slowRequests: z.array(slowRequestSchema).max(10).optional(),
	freezeEvents: z.array(freezeEventSchema).max(50).optional(),
	recentActions: z.array(userActionSchema).max(30).optional(),
	webVitals: webVitalsSchema.optional(),
	exerciseId: z.string().uuid().optional(),
	exerciseType: z.string().max(100).optional(),
	classId: z.string().uuid().optional(),
	assignmentId: z.string().uuid().optional()
});

// =============================================================================
// Create Bug Report Schema
// =============================================================================

export const createBugReportSchema = z.object({
	category: bugReportCategorySchema,
	severity: bugReportSeveritySchema.default('medium'),
	title: z
		.string()
		.min(5, 'Le titre doit contenir au moins 5 caractères')
		.max(200, 'Le titre ne peut pas dépasser 200 caractères')
		.transform((s) => s.trim()),
	description: z
		.string()
		.min(20, 'La description doit contenir au moins 20 caractères')
		.max(5000, 'La description ne peut pas dépasser 5000 caractères')
		.transform((s) => s.trim()),
	pageUrl: z.string().max(500).optional(),
	userAgent: z.string().max(500).optional(),
	viewportSize: z
		.string()
		.max(20)
		.regex(/^\d+x\d+$/, 'Format viewport invalide (ex: 1920x1080)')
		.optional(),
	sessionContext: sessionContextSchema.optional(),
	screenshotUrl: z.string().url().optional(),
	screenshotPath: z.string().max(500).optional(),
	autoGenerated: z.boolean().default(false)
});

export type CreateBugReportInput = z.infer<typeof createBugReportSchema>;

// =============================================================================
// Update Bug Report Schema (User - only pending reports)
// =============================================================================

export const updateBugReportUserSchema = z
	.object({
		title: z
			.string()
			.min(5, 'Le titre doit contenir au moins 5 caractères')
			.max(200, 'Le titre ne peut pas dépasser 200 caractères')
			.transform((s) => s.trim())
			.optional(),
		description: z
			.string()
			.min(20, 'La description doit contenir au moins 20 caractères')
			.max(5000, 'La description ne peut pas dépasser 5000 caractères')
			.transform((s) => s.trim())
			.optional()
	})
	.refine((data) => data.title !== undefined || data.description !== undefined, {
		message: 'Au moins un champ doit être modifié'
	});

export type UpdateBugReportUserInput = z.infer<typeof updateBugReportUserSchema>;

// =============================================================================
// Update Bug Report Schema (Admin)
// =============================================================================

export const updateBugReportAdminSchema = z
	.object({
		status: bugReportStatusSchema.optional(),
		resolutionNotes: z
			.string()
			.max(2000, 'Les notes ne peuvent pas dépasser 2000 caractères')
			.transform((s) => s.trim())
			.optional()
	})
	.refine((data) => data.status !== undefined || data.resolutionNotes !== undefined, {
		message: 'Au moins un champ doit être modifié'
	});

export type UpdateBugReportAdminInput = z.infer<typeof updateBugReportAdminSchema>;

// =============================================================================
// List Bug Reports Query Schema
// =============================================================================

export const listBugReportsQuerySchema = z.object({
	status: bugReportStatusSchema.optional(),
	category: bugReportCategorySchema.optional(),
	severity: bugReportSeveritySchema.optional(),
	limit: z.coerce.number().int().min(1).max(100).default(20),
	offset: z.coerce.number().int().min(0).default(0)
});

export type ListBugReportsQuery = z.infer<typeof listBugReportsQuerySchema>;

// =============================================================================
// Screenshot Upload Schema
// =============================================================================

export const screenshotUploadSchema = z.object({
	reportId: z.string().uuid('ID de rapport invalide')
});

// =============================================================================
// Export Request Schema
// =============================================================================

export const exportBugReportSchema = z.object({
	reportId: z.string().uuid('ID de rapport invalide'),
	format: z.enum(['markdown', 'json']).default('markdown')
});

export type ExportBugReportInput = z.infer<typeof exportBugReportSchema>;
