/**
 * MathAST Transform Module
 *
 * Provides transformation rules and utilities for mathematical expressions.
 *
 * @module mathAST/transform
 */

// Trigonometric identities
export {
	// Application functions
	applyTrigIdentities,
	contractToDoubleAngle,
	simplifyPythagorean,
	simplifyQuotients,
	linearize,
	expandAddition,
	expandDoubleAngle,
	simplifyNegativeAngle,
	simplifyCofunction,
	simplifySupplementary,
	simplifyShiftPiOver2,
	factorize,
	reducePeriodic,
	expandHalfAngle,
	reduceHigherPowers,
	// Individual transforms (for testing/direct use)
	TRANSFORM_SIN_COS_PRODUCT,
	TRANSFORM_DOUBLE_ANGLE_SIN,
	TRANSFORM_SIN_SQUARED,
	TRANSFORM_COS_SQUARED,
	TRANSFORM_PYTHAGOREAN,
	TRANSFORM_ONE_MINUS_SIN_SQUARED,
	TRANSFORM_ONE_MINUS_COS_SQUARED,
	TRANSFORM_SIN_OVER_COS,
	TRANSFORM_COS_COS_PRODUCT,
	TRANSFORM_SIN_SIN_PRODUCT,
	TRANSFORM_SIN_COS_DIFFERENT,
	TRANSFORM_COS_SUM,
	TRANSFORM_COS_DIFFERENCE,
	TRANSFORM_SIN_SUM,
	TRANSFORM_SIN_DIFFERENCE,
	TRANSFORM_EXPAND_DOUBLE_SIN,
	TRANSFORM_EXPAND_DOUBLE_COS,
	TRANSFORM_EXPAND_DOUBLE_TAN,
	TRANSFORM_COS_OVER_SIN,
	TRANSFORM_ONE_OVER_COS,
	TRANSFORM_ONE_OVER_SIN,
	TRANSFORM_TAN_SUM,
	TRANSFORM_TAN_DIFFERENCE,
	TRANSFORM_SIN_NEGATIVE,
	TRANSFORM_COS_NEGATIVE,
	TRANSFORM_TAN_NEGATIVE,
	TRANSFORM_SIN_COFUNCTION,
	TRANSFORM_COS_COFUNCTION,
	TRANSFORM_TAN_COFUNCTION,
	TRANSFORM_SIN_PLUS_SIN,
	TRANSFORM_SIN_MINUS_SIN,
	TRANSFORM_COS_PLUS_COS,
	TRANSFORM_COS_MINUS_COS,
	TRANSFORM_SIN_PERIOD_2PI,
	TRANSFORM_COS_PERIOD_2PI,
	TRANSFORM_SIN_PLUS_PI,
	TRANSFORM_COS_PLUS_PI,
	TRANSFORM_SIN_HALF_ANGLE,
	TRANSFORM_COS_HALF_ANGLE,
	TRANSFORM_SIN_CUBED,
	TRANSFORM_COS_CUBED,
	TRANSFORM_SIN_FOURTH,
	TRANSFORM_COS_FOURTH,
	TRANSFORM_SIN_SUPPLEMENTARY,
	TRANSFORM_COS_SUPPLEMENTARY,
	TRANSFORM_TAN_SUPPLEMENTARY,
	TRANSFORM_SIN_PLUS_PI_OVER_2,
	TRANSFORM_COS_PLUS_PI_OVER_2,
	TRANSFORM_TAN_PLUS_PI_OVER_2,
	// Types
	type TrigTransformResult
} from './trig-identities';
