/**
 * Question Transformer - TinyMath to UbuMaths v2
 * ===============================================
 *
 * Comprehensive transformer for converting old TinyMath QuestionBase objects
 * to new UbuMaths v2 QuestionTemplate objects as part of Phase 1.4 of the
 * migration project.
 *
 * Features:
 * - Automatic question type detection
 * - Variable syntax conversion
 * - Answer format transformation
 * - Validation option mapping
 * - Comprehensive error handling
 * - Warning generation for manual review items
 *
 * @module migration/question-transformer
 */

import type {
	QuestionBase,
	OldGrade,
	Choice,
	CorrectionDetail,
	CorrectionFormat,
	Variables,
	// eslint-disable-next-line @typescript-eslint/no-unused-vars
	VariableName
} from './old-question-types';

import type {
	QuestionTemplate,
	QuestionType,
	QuestionVariation,
	QuestionVariable,
	QuestionCorrection,
	SharedVariationDefaults,
	// eslint-disable-next-line @typescript-eslint/no-unused-vars
	PrecisionType,
	ValidationRule,
	ConstraintOptions,
	RequiredForm
} from '$lib/questions/types';

import type { DisplayOptions, TemplateMarkdown } from '$lib/ubumark';
import { templateMarkdown } from '$lib/ubumark';

import {
	hasChoices,
	hasMultipleAnswers,
	hasFillInBlanks,
	hasAnswerFields,
	hasImages,
	// eslint-disable-next-line @typescript-eslint/no-unused-vars
	hasVariables,
	hasTestAnswers,
	getVariationCount,
	// eslint-disable-next-line @typescript-eslint/no-unused-vars
	detectQuestionType as detectOldQuestionType
} from './old-question-types';

import {
	convertTinyCASToNew,
	fixMathDelimiters,
	toSimplifiedSyntax,
	toBareVariableSyntax
} from './syntax-converter';
import { convertPlaceholders } from './placeholder-converter';
import { convertConditionals } from './conditional-converter';
// Note: No AsciiMath→LaTeX conversion here. Variables use custom mathAST syntax.
// LaTeX conversion happens at question instantiation when inside $...$

// ============================================================================
// IMAGE URL MAPPING TYPE
// ============================================================================

/**
 * Mapping from old image paths to new Supabase Storage URLs
 *
 * The mapping supports multiple path formats for the same image:
 * - Full absolute path: /Users/david/Coding/js/ubumaths/static/images/questions/...
 * - Relative path: entiers/reperage/...
 * - With leading slash: /entiers/reperage/...
 * - With /images prefix: /images/entiers/reperage/...
 */
export type ImageUrlMapping = Record<string, string>;

/**
 * Look up new URL for an old image path
 *
 * Tries multiple path formats to find a match:
 * 1. Exact path as provided
 * 2. Without leading slash
 * 3. With /images/ prefix removed
 * 4. Normalized relative path
 *
 * @param oldPath - The old image path from the question
 * @param mapping - The image URL mapping object
 * @returns The new Supabase Storage URL, or undefined if not found
 */
function lookupImageUrl(oldPath: string, mapping: ImageUrlMapping): string | undefined {
	// Try exact match first
	if (mapping[oldPath]) {
		return mapping[oldPath];
	}

	// Try without leading slash
	const withoutLeadingSlash = oldPath.replace(/^\//, '');
	if (mapping[withoutLeadingSlash]) {
		return mapping[withoutLeadingSlash];
	}

	// Try with /images/ prefix removed
	const withoutImages = oldPath.replace(/^\/?images\//, '');
	if (mapping[withoutImages]) {
		return mapping[withoutImages];
	}

	// Try adding /images/ prefix
	const withImages = `/images/${withoutLeadingSlash}`;
	if (mapping[withImages]) {
		return mapping[withImages];
	}

	// Not found
	return undefined;
}

/**
 * Convert an old image path to markdown image syntax with new URL
 *
 * @param oldPath - The old image path
 * @param mapping - The image URL mapping object
 * @param altText - Alternative text for the image
 * @returns Markdown image syntax or undefined if not found
 */
function convertImageToMarkdown(
	oldPath: string,
	mapping: ImageUrlMapping | undefined,
	altText: string
): string | undefined {
	if (!mapping) {
		return undefined;
	}

	const newUrl = lookupImageUrl(oldPath, mapping);
	if (newUrl) {
		return `![${altText}](${newUrl})`;
	}

	return undefined;
}

// ============================================================================
// RESULT TYPES
// ============================================================================

/**
 * Result of a question transformation
 */
export interface TransformResult {
	/** Whether transformation succeeded */
	success: boolean;

	/** Transformed template if successful (without id/audit fields - will be generated by database) */
	template?: Omit<QuestionTemplate, 'id' | 'created_at' | 'updated_at' | 'created_by'>;

	/** List of warnings about items needing review */
	warnings?: string[];

	/** List of errors that prevented transformation */
	errors?: string[];

	/** Statistics about the transformation */
	stats?: TransformStats;
}

/**
 * Statistics about a transformation
 */
export interface TransformStats {
	/** Number of variations created */
	variations: number;

	/** Number of variables converted */
	variables: number;

	/** Number of syntax conversions performed */
	syntaxConversions: number;

	/** Number of validation options mapped */
	optionsMapped: number;

	/** Number of display options mapped to defaultDisplayOptions */
	displayOptionsMapped: number;

	/** Number of correction syntax conversions (placeholders + conditionals) */
	correctionConversions: number;

	/** Question type detected */
	detectedType: string;

	/** Whether images were skipped */
	hasImages: boolean;

	/** Whether custom validation was detected */
	hasCustomValidation: boolean;

	/** Number of images converted using the mapping */
	imagesConverted: number;

	/** Number of images that could not be found in mapping */
	imagesMissing: number;

	/** Number of AsciiMath to LaTeX conversions performed */
	asciiMathConverted: number;
}

// ============================================================================
// GRADE MAPPING
// ============================================================================

import type { GradeCode } from '$lib/types/grades';

/**
 * Map old grade format to new unified GradeCode format
 *
 * Old system used 'SPE_1', 'SPE_T', 'STMG'
 * New system uses '1_SPE', 'T_SPE', 'T_STMG'
 */
function mapGrade(oldGrade: OldGrade): GradeCode {
	const gradeMap: Record<OldGrade, GradeCode> = {
		CP: 'CP',
		CE1: 'CE1',
		CE2: 'CE2',
		CM1: 'CM1',
		CM2: 'CM2',
		'6': '6',
		'5': '5',
		'4': '4',
		'3': '3',
		'2': '2',
		// Legacy names mapped to new format
		SPE_1: '1_SPE', // Old 'SPE_1' -> New '1_SPE'
		SPE_T: 'T_SPE', // Old 'SPE_T' -> New 'T_SPE'
		T_EXP: 'T_EXP',
		T_COMP: 'T_COMP',
		STMG: 'T_STMG' // Old 'STMG' -> New 'T_STMG' (assuming Terminale STMG)
	};

	return gradeMap[oldGrade] || 'CM1'; // Default to CM1 if unknown
}

// ============================================================================
// MIGRATION MODE DETECTION
// ============================================================================

/**
 * Internal migration mode — determines HOW to convert the old question.
 * The output type is always inferred from structure (choices → MC, else → FIB).
 */
type MigrationMode =
	| 'result_rewrite' // Has expressions (no ? in them), no choices → fill_in_blanks with expression convention
	| 'answer_field' // Has answerFields, no choices → fill_in_blanks with $?$ in statement
	| 'fill_in' // Has expressions with ?, no choices → fill_in_blanks (existing behavior)
	| 'multiple_choice'; // Has choices → multiple_choice

/**
 * Detect migration mode from old question structure.
 * Replaces the old detectQuestionType which returned types that no longer exist.
 */
function detectMigrationMode(oldQuestion: QuestionBase): MigrationMode {
	// Multiple choice (with or without multiple answers)
	if (hasMultipleAnswers(oldQuestion) || hasChoices(oldQuestion)) {
		return 'multiple_choice';
	}

	// Fill in blanks (expressions with ?)
	if (hasFillInBlanks(oldQuestion)) {
		return 'fill_in';
	}

	// Has custom answer fields → convert to fill_in_blanks with $?$ in statement
	if (hasAnswerFields(oldQuestion)) {
		return 'answer_field';
	}

	// Has expressions without ? → result/rewrite → fill_in_blanks with expression convention
	return 'result_rewrite';
}

/**
 * @deprecated Use detectMigrationMode instead. Kept for stats reporting.
 */
function detectQuestionType(oldQuestion: QuestionBase): string {
	const mode = detectMigrationMode(oldQuestion);
	// Map to legacy names for stats only
	switch (mode) {
		case 'multiple_choice':
			return 'multiple_choice';
		case 'fill_in':
			return 'fill_in_blanks';
		case 'answer_field':
			return 'fill_in_blanks';
		case 'result_rewrite':
			return oldQuestion['result-type'] === 'decimal' ? 'numerical_decimal' : 'fill_in_blanks';
	}
}

// ============================================================================
// VARIABLE CONVERSION
// ============================================================================

/**
 * Convert a 1-based number to a letter name (Excel column style)
 * 1→a, 2→b, ..., 26→z, 27→aa, 28→ab, etc.
 */
export function numberToLetterName(num: number): string {
	let result = '';
	let n = num;
	while (n > 0) {
		n--; // Adjust for 0-based indexing
		result = String.fromCharCode(97 + (n % 26)) + result;
		n = Math.floor(n / 26);
	}
	return result;
}

/**
 * Decompose a complex digits: expression into intermediate variables.
 *
 * When a digits: decimal expression has ranges in its parts (e.g., "digits:0..2.1..2"),
 * the "." separator is ambiguous with ".." ranges. We split it into intermediate
 * variables that each resolve to a single digit count, then reference them with
 * the standard "digits:intVar.decVar" syntax.
 *
 * @example
 * "digits:0..2.1..2" becomes:
 *   { name: "b_int", expression: "0..2" }
 *   { name: "b_dec", expression: "1..2" }
 *   { name: "b", expression: "digits:b_int.b_dec" }
 *
 * @example
 * "digits:0..4-a.1..4" becomes:
 *   { name: "b_int", expression: "eval:4-a" } (with range 0..)
 *   → actually: { name: "b_int", expression: "0..eval:4-a" }
 *   Hmm, that doesn't work either. Let's use the range directly.
 *
 * @returns Array of variables (intermediates + final), or null if no decomposition needed
 */
function decomposeComplexDigits(varName: string, expression: string): QuestionVariable[] | null {
	// Only handle digits: expressions
	if (!expression.startsWith('digits:')) return null;

	const spec = expression.slice('digits:'.length);

	// Check if this is a decimal format (has a separator between int/dec parts)
	// Simple cases like "digits:a" or "digits:2" or "digits:1..3" don't need decomposition
	// Only decimal format "digits:X.Y" needs checking

	// Find the separator "." that divides int digits from dec digits
	// Must not confuse with ".." (range separator)
	// Strategy: try to split into exactly 2 parts on "." that is NOT part of ".."
	const parts = splitDigitsParts(spec);
	if (!parts) return null;

	const [beforePart, afterPart] = parts;

	// If neither part contains ".." (ranges), no decomposition needed
	// The standard "digits:2.3" or "digits:a.b" syntax works fine
	if (!beforePart.includes('..') && !afterPart.includes('..')) return null;

	// Create intermediate variables for the range parts
	const result: QuestionVariable[] = [];

	const intVarName = `${varName}_int`;
	const decVarName = `${varName}_dec`;

	result.push({ name: intVarName, expression: beforePart });
	result.push({ name: decVarName, expression: afterPart });
	result.push({ name: varName, expression: `digits:${intVarName}.${decVarName}` });

	return result;
}

/**
 * Split a digits spec "X.Y" into [X, Y] where "." separates int/dec parts.
 * Returns null if this is not a decimal format (no valid "." separator found).
 *
 * Must distinguish "." (decimal separator) from ".." (range separator).
 * Scans for "." that is NOT preceded or followed by another ".".
 */
function splitDigitsParts(spec: string): [string, string] | null {
	for (let i = 0; i < spec.length; i++) {
		if (spec[i] === '.') {
			// Check it's a single ".", not part of ".."
			const prevIsDot = i > 0 && spec[i - 1] === '.';
			const nextIsDot = i < spec.length - 1 && spec[i + 1] === '.';
			if (!prevIsDot && !nextIsDot) {
				return [spec.substring(0, i), spec.substring(i + 1)];
			}
		}
	}
	return null;
}

/**
 * Convert old variable definitions to new format
 */
function convertVariables(
	oldVars: Variables | undefined,
	warnings: string[]
): QuestionVariable[] | undefined {
	if (!oldVars) return undefined;

	const variables: QuestionVariable[] = [];

	for (const [varName, expression] of Object.entries(oldVars)) {
		// Remove & prefix from variable name and convert numeric to letter
		const rawName = varName.substring(1);
		const name = /^\d+$/.test(rawName) ? numberToLetterName(parseInt(rawName, 10)) : rawName;

		// Convert TinyCAS syntax to new syntax
		const conversionResult = convertTinyCASToNew(expression);

		if (!conversionResult.success) {
			warnings.push(
				`Failed to convert variable ${varName}: ${conversionResult.errors?.join(', ')}`
			);
			// Use original expression as fallback, but still simplify and convert to bare names
			variables.push({
				name,
				expression: toBareVariableSyntax(toSimplifiedSyntax(expression))
			});
		} else {
			if (conversionResult.warnings) {
				warnings.push(...conversionResult.warnings.map((w) => `Variable ${varName}: ${w}`));
			}

			// Variable expressions are NOT math - they're definitions like "5..7", "eval:a+b", "rouge|vert"
			// Do NOT convert them to LaTeX - they are interpreted by the parameterization system
			const afterTinyCAS = conversionResult.converted || expression;

			// Convert to simplified syntax and use bare variable names
			// {{a}}^{{b}} → a^b (resolver handles bare name substitution)
			const simplified = toBareVariableSyntax(toSimplifiedSyntax(afterTinyCAS));

			// Handle complex digits: expressions where parts contain ranges (..)
			// e.g., "digits:0..2.1..2" → split into intermediate variables
			const digitsDecomposed = decomposeComplexDigits(name, simplified);
			if (digitsDecomposed) {
				variables.push(...digitsDecomposed);
			} else {
				variables.push({
					name,
					expression: simplified
				});
			}
		}
	}

	return variables.length > 0 ? variables : undefined;
}

// ============================================================================
// STATEMENT CONVERSION
// ============================================================================

/**
 * Result of statement conversion including extracted expression variable
 */
interface StatementResult {
	/** The converted statement with expression reference */
	statement: TemplateMarkdown;
	/** The extracted expression as a variable (if expression was provided) */
	expressionVariable?: QuestionVariable;
}

/**
 * Convert statement and expression to TemplateMarkdown string.
 * Expression is extracted as a separate variable and referenced in the statement.
 *
 * @param enonce - The question text (enounce)
 * @param expression - The mathematical expression (will become a variable)
 * @param expressionIndex - Index for naming the expression variable (expression1, expression2...)
 * @param images - Array of image paths for this variation
 * @param imageMapping - Mapping from old paths to new URLs
 * @param warnings - Array to collect warnings
 * @param stats - Stats object to track image conversions
 * @returns StatementResult with statement and optional expression variable
 */
function convertStatement(
	enonce: string | undefined,
	expression: string | undefined,
	expressionIndex: number,
	images: string[] | undefined,
	imageMapping: ImageUrlMapping | undefined,
	warnings: string[],
	stats: TransformStats
): StatementResult {
	const parts: string[] = [];
	let expressionVariable: QuestionVariable | undefined;

	// Process enonce (statement text)
	if (enonce) {
		const conversionResult = convertTinyCASToNew(enonce);

		if (!conversionResult.success) {
			warnings.push(`Failed to convert statement: ${conversionResult.errors?.join(', ')}`);
			parts.push(enonce);
		} else {
			if (conversionResult.warnings) {
				warnings.push(...conversionResult.warnings.map((w) => `Statement: ${w}`));
			}
			parts.push(conversionResult.converted || enonce);
		}
	}

	// Process expression - extract as variable and add reference to statement
	if (expression) {
		const conversionResult = convertTinyCASToNew(expression);
		const varName = `expression${expressionIndex}`;

		if (!conversionResult.success) {
			warnings.push(`Failed to convert expression: ${conversionResult.errors?.join(', ')}`);
			// Still create variable with original expression, convert to bare syntax
			expressionVariable = {
				name: varName,
				expression: toBareVariableSyntax(toSimplifiedSyntax(expression))
			};
		} else {
			if (conversionResult.warnings) {
				warnings.push(...conversionResult.warnings.map((w) => `Expression: ${w}`));
			}
			// Keep expression in custom mathAST syntax (no LaTeX conversion here)
			// LaTeX conversion happens at instantiation when inside $...$
			const afterTinyCAS = conversionResult.converted || expression;

			// Convert to bare variable syntax: {{a}}^{{b}} → a^b
			// The resolver handles bare variable name substitution automatically
			const bareExpr = toBareVariableSyntax(toSimplifiedSyntax(afterTinyCAS));

			expressionVariable = {
				name: varName,
				expression: bareExpr
			};
		}

		// Add reference to statement - check for existing $$ delimiters in the expression
		const exprContent = expressionVariable.expression;
		const hasDisplayDelimiters = exprContent.includes('$$');

		if (hasDisplayDelimiters) {
			// Expression already has $$ - just reference the variable
			parts.push('{{' + varName + '}}');
		} else {
			// Wrap reference in $$ for display math
			parts.push('$${{' + varName + '}}$$');
		}
	}

	// Process images
	if (images && images.length > 0) {
		for (let i = 0; i < images.length; i++) {
			const imagePath = images[i];
			const imageMarkdown = convertImageToMarkdown(
				imagePath,
				imageMapping,
				`Question image ${i + 1}`
			);

			if (imageMarkdown) {
				parts.push(imageMarkdown);
				stats.imagesConverted++;
			} else {
				// Image not found in mapping
				stats.imagesMissing++;
				if (imageMapping) {
					warnings.push(`Image not found in mapping: ${imagePath}`);
				}
				// Include original path as fallback
				parts.push(`![Question image ${i + 1}](${imagePath})`);
			}
		}
	}

	// Fallback if nothing was provided
	if (parts.length === 0) {
		warnings.push('No statement or expression provided');
		return {
			statement: templateMarkdown('Question content missing'),
			expressionVariable: undefined
		};
	}

	// Join parts with double newline (paragraph break)
	// Apply fixMathDelimiters to convert inline $$...$$ to $...$
	return {
		statement: templateMarkdown(fixMathDelimiters(parts.join('\n\n'))),
		expressionVariable
	};
}

// ============================================================================
// ANSWER FIELD CONVERSION
// ============================================================================

/**
 * Convert an old answerField template to a ubumark statement with $?$ blanks.
 *
 * Conversion rules:
 * - \text{...} → plain text
 * - $$...$$ where content is "..." (three dots) → $?$ (math blank)
 * - $$expr$$ where content is NOT "..." → $converted_expr$ (math display)
 *
 * @example
 * '\\text{Le double de }$$&1$$\\text{ est }$$...$$\\text{.}'
 * → 'Le double de ${{a}}$ est $?$.'
 */
function convertAnswerFieldToStatement(answerField: string, warnings: string[]): string {
	let result = answerField;

	// Step 1: Convert \text{...} → plain text
	result = result.replace(/\\text\{([^}]*)\}/g, '$1');

	// Step 2: Convert $$...$$ segments
	result = result.replace(/\$\$(.*?)\$\$/g, (_match, content: string) => {
		if (content === '...') {
			// Blank marker → $?$
			return '$?$';
		}
		// Math expression (may contain variable references like &1)
		const converted = convertTinyCASToNew(content);
		if (converted.warnings) {
			warnings.push(...converted.warnings.map((w) => `AnswerField math: ${w}`));
		}
		return '$' + (converted.converted || content) + '$';
	});

	return result;
}

/**
 * Detect if a TinyMath solution contains a unit.
 * TinyMath unit syntax: [_expr_unit_] where unit is text after the last _ before ]
 * Examples: [_&2_km.h^{-1}_], [_&1_m_]
 *
 * @returns true if the solution contains a unit annotation
 */
function solutionHasUnit(solution: string): boolean {
	// Match patterns like [_expr_unit_] or [._expr_unit_.]
	// The unit is between the last two underscores
	// Simplified check: look for _text_ pattern where text looks like a unit
	const unitPattern = /_([a-zA-Z][a-zA-Z0-9.^{}-]*)_\]$/;
	return unitPattern.test(solution);
}

/**
 * Extract blanks from solutionss for result/rewrite or answerField questions.
 *
 * @param solutions - The solutions array for this variation
 * @param answerFormat - Optional answer format (e.g., "10^?", "?*10^?")
 * @param expressionVarName - Name of the expression variable (for default blank)
 * @param warnings - Array to collect warnings
 */
function extractBlanksFromSolutions(
	solutions: (string | number)[] | undefined,
	answerFormat: string | undefined,
	expressionVarName: string | undefined,
	warnings: string[],
	blankCount?: number
): NonNullable<QuestionVariation['blanks']> {
	const blanks: NonNullable<QuestionVariation['blanks']> = [];

	// Count expected blanks: explicit count > answerFormat ? count > default 1
	const expectedCount = blankCount ?? (answerFormat ? (answerFormat.match(/\?/g) || []).length : 1);

	if (solutions && solutions.length > 0) {
		const count = Math.min(expectedCount, solutions.length);
		if (solutions.length < expectedCount) {
			warnings.push(`Expected ${expectedCount} solution(s) for blanks but got ${solutions.length}`);
		}
		for (let i = 0; i < count; i++) {
			const rawAnswer = String(solutions[i]);
			const conversionResult = convertTinyCASToNew(rawAnswer);
			if (conversionResult.warnings) {
				warnings.push(...conversionResult.warnings.map((w) => `Blank solution: ${w}`));
			}
			const blank: NonNullable<QuestionVariation['blanks']>[number] = {
				expectedAnswer: conversionResult.converted || rawAnswer
			};

			// Detect unit in solution
			if (solutionHasUnit(rawAnswer)) {
				blank.unit = { expected: true };
			}

			blanks.push(blank);
		}
	} else if (expressionVarName) {
		// No explicit solutions → eval of expression
		blanks.push({ expectedAnswer: `{{eval:{{${expressionVarName}}}}}` });
	} else {
		warnings.push('No solutions and no expression variable for blanks');
	}

	return blanks;
}

// ============================================================================
// SOLUTION CONVERSION
// ============================================================================

/**
 * Convert solution(s) to new format.
 * Note: This converts the expected solution (from solutionss), not student answers.
 */
function convertSolution(
	solutions: (string | number)[] | undefined,
	questionType: QuestionType,
	warnings: string[]
): string | string[] {
	if (!solutions || solutions.length === 0) {
		warnings.push('No solutions provided');
		return questionType === 'multiple_choice' ? ['0'] : '';
	}

	// For multiple choice, solutions are indices
	if (questionType === 'multiple_choice') {
		return solutions.map((s) => String(s));
	}

	// For other types, convert the expression syntax
	const solutionValue = String(solutions[0]);
	const conversionResult = convertTinyCASToNew(solutionValue);

	if (!conversionResult.success) {
		warnings.push(`Failed to convert solution: ${conversionResult.errors?.join(', ')}`);
		return solutionValue;
	}

	if (conversionResult.warnings) {
		warnings.push(...conversionResult.warnings.map((w) => `Solution: ${w}`));
	}

	// Keep solution in custom mathAST syntax (no LaTeX conversion)
	// Solutions are compared using mathAST, not rendered as LaTeX
	// Use simplified syntax (same as variable expressions)
	const afterTinyCAS = conversionResult.converted || solutionValue;
	return toBareVariableSyntax(toSimplifiedSyntax(afterTinyCAS));
}

// ============================================================================
// CHOICES CONVERSION
// ============================================================================

/**
 * Convert choices for multiple choice questions
 *
 * @param choices - Array of choice objects from old question
 * @param correctIndices - Indices of correct choices
 * @param imageMapping - Mapping from old image paths to new URLs
 * @param warnings - Array to collect warnings
 * @param stats - Stats object to track image conversions
 * @returns Array of converted choices
 */
function convertChoices(
	choices: Choice[] | undefined,
	imageMapping: ImageUrlMapping | undefined,
	warnings: string[],
	stats: TransformStats
): QuestionVariation['choices'] {
	if (!choices || choices.length === 0) {
		return undefined;
	}

	// Note: isCorrect is no longer set here - the correct choice is determined
	// at runtime by evaluating the solution (which contains the correct index)
	return choices.map((choice, index) => {
		let content: TemplateMarkdown;

		if (choice.text) {
			const conversionResult = convertTinyCASToNew(choice.text);
			if (!conversionResult.success && conversionResult.errors) {
				warnings.push(`Choice ${index}: ${conversionResult.errors.join(', ')}`);
			}
			// Apply fixMathDelimiters to convert inline $$...$$ to $...$
			const converted = fixMathDelimiters(conversionResult.converted || choice.text);
			content = templateMarkdown(converted);
		} else if (choice.image) {
			// Convert image using mapping if available
			const imageMarkdown = convertImageToMarkdown(
				choice.image,
				imageMapping,
				`Choice ${index + 1}`
			);

			if (imageMarkdown) {
				content = templateMarkdown(imageMarkdown);
				stats.imagesConverted++;
			} else {
				// Fallback to original path
				stats.imagesMissing++;
				if (imageMapping) {
					warnings.push(`Choice image not found in mapping: ${choice.image}`);
				}
				content = templateMarkdown(`![Choice ${index + 1}](${choice.image})`);
			}
		} else {
			content = templateMarkdown(`Choice ${index + 1}`);
		}

		return {
			content
		};
	});
}

// ============================================================================
// CORRECTION CONVERSION
// ============================================================================

/**
 * Apply all legacy syntax conversions to a text string
 *
 * Conversion order:
 * 1. TinyCAS syntax (variable references, evaluations)
 * 2. Placeholder syntax (&sol, &answer, &expression, etc.)
 * 3. Conditional syntax (@@condition ?? text@@)
 *
 * @param text - The text to convert
 * @param warnings - Array to collect conversion warnings
 * @returns The converted text with all legacy syntax transformed to new format
 */
function convertLegacySyntax(text: string, warnings: string[]): string {
	if (!text) return text;

	// Step 1: Convert TinyCAS syntax
	const casResult = convertTinyCASToNew(text);
	let converted = text;

	if (!casResult.success) {
		warnings.push(`TinyCAS conversion warning: ${casResult.errors?.join(', ')}`);
	} else {
		converted = casResult.converted || text;
		if (casResult.warnings) {
			warnings.push(...casResult.warnings.map((w) => `TinyCAS: ${w}`));
		}
	}

	// Step 2: Convert placeholder syntax (&sol, &answer, etc.)
	const placeholderResult = convertPlaceholders(converted);
	converted = placeholderResult.converted;

	// Step 3: Convert conditional syntax (@@cond ?? text@@)
	const conditionalResult = convertConditionals(converted);
	converted = conditionalResult.converted;

	// Step 4: Fix math delimiters (convert inline $$...$$ to $...$)
	converted = fixMathDelimiters(converted);

	return converted;
}

/**
 * Transform old correction fields to unified QuestionCorrection
 *
 * Maps:
 * - correctionFormats.correct -> feedback.correct
 * - correctionFormats.uncorrect -> feedback.incorrect
 * - correctionDetailss -> steps
 *
 * @param correctionDetails - Old correction details array (step-by-step explanations)
 * @param correctionFormat - Old correction format (feedback messages)
 * @param warnings - Array to collect conversion warnings
 * @param stats - Statistics object to track conversions
 * @returns QuestionCorrection object or undefined if nothing to convert
 */
function transformCorrection(
	correctionDetails: CorrectionDetail[] | undefined,
	correctionFormat: CorrectionFormat | undefined,
	warnings: string[],
	stats: TransformStats
): QuestionCorrection | undefined {
	const correction: QuestionCorrection = {};
	let conversionCount = 0;

	// Transform feedback from correctionFormats
	if (correctionFormat) {
		correction.feedback = {};

		if (correctionFormat.correct?.length) {
			// Convert first correct message with all syntax converters
			const converted = convertLegacySyntax(correctionFormat.correct[0], warnings);
			correction.feedback.correct = templateMarkdown(converted);
			conversionCount++;
		}

		if (correctionFormat.uncorrect?.length) {
			// Convert first incorrect message with all syntax converters
			const converted = convertLegacySyntax(correctionFormat.uncorrect[0], warnings);
			correction.feedback.incorrect = templateMarkdown(converted);
			conversionCount++;
		}

		// Remove feedback object if empty
		if (!correction.feedback.correct && !correction.feedback.incorrect) {
			delete correction.feedback;
		}
	}

	// Transform steps from correctionDetailss
	if (correctionDetails?.length) {
		correction.steps = correctionDetails.map((detail) => {
			const converted = convertLegacySyntax(detail.text, warnings);
			conversionCount++;
			return templateMarkdown(converted);
		});
	}

	// Track conversion stats
	stats.correctionConversions += conversionCount;

	// Return undefined if nothing was converted
	if (!correction.feedback && !correction.steps) {
		return undefined;
	}

	return correction;
}

/**
 * Convert correction details to TemplateMarkdown string
 *
 * @deprecated Use transformCorrection instead for full QuestionCorrection support
 */
function _convertCorrection(
	correctionDetails: CorrectionDetail[] | undefined,
	warnings: string[]
): TemplateMarkdown | undefined {
	if (!correctionDetails || correctionDetails.length === 0) {
		return undefined;
	}

	const parts: string[] = [];

	for (const detail of correctionDetails) {
		const conversionResult = convertTinyCASToNew(detail.text);

		if (!conversionResult.success) {
			warnings.push(`Failed to convert correction: ${conversionResult.errors?.join(', ')}`);
			parts.push(detail.text);
		} else {
			parts.push(conversionResult.converted || detail.text);
		}
	}

	// Join correction parts with double newline
	return templateMarkdown(parts.join('\n\n'));
}

// ============================================================================
// OPTIONS CONVERSION
// ============================================================================

/**
 * Convert old validation options to new format
 *
 * Maps old TinyMath options to new ConstraintOptions structure:
 * - require-* options → constraint: 'strict'
 * - no-penalty-for-* options → constraint: 'off'
 * - Display/generation options → defaultDisplayOptions
 * - Display options (enounce-no-spaces) → silently ignored
 */
function convertOptions(
	oldOptions: string[] | undefined,
	warnings: string[],
	oldFormats?: string[]
): {
	options?: QuestionTemplate['options'];
	defaultDisplayOptions?: DisplayOptions;
	requiredForm?: RequiredForm;
} {
	if (!oldOptions || oldOptions.length === 0) {
		return {};
	}

	const options: QuestionTemplate['options'] = {};
	const constraints: ConstraintOptions = {};
	const displayOptions: DisplayOptions = {};
	let requiredForm: RequiredForm | undefined;
	// Note: mappedCount tracked for potential debugging but not used in return
	let _mappedCount = 0;

	for (const option of oldOptions) {
		switch (option) {
			// ================================================================
			// CONSTRAINT OPTIONS - Spaces
			// ================================================================
			case 'require-correct-spaces':
				constraints.spaces = 'strict';
				_mappedCount++;
				break;
			case 'no-penalty-for-incorrect-spaces':
				constraints.spaces = 'off';
				_mappedCount++;
				break;

			// ================================================================
			// CONSTRAINT OPTIONS - Products
			// ================================================================
			case 'require-implicit-products':
				constraints.products = 'strict';
				_mappedCount++;
				break;
			case 'no-penalty-for-explicit-products':
				constraints.products = 'off';
				_mappedCount++;
				break;

			// ================================================================
			// CONSTRAINT OPTIONS - Brackets
			// ================================================================
			case 'require-no-extraneous-brackets':
				constraints.brackets = 'strict';
				_mappedCount++;
				break;
			case 'no-penalty-for-extraneous-brackets':
				constraints.brackets = 'off';
				_mappedCount++;
				break;
			case 'no-penalty-for-extraneous-brackets-in-first-negative-term':
				constraints.brackets = 'off';
				constraints.allowBracketsInFirstNegativeTerm = true;
				_mappedCount++;
				break;

			// ================================================================
			// CONSTRAINT OPTIONS - Zeros
			// ================================================================
			case 'require-no-extraneous-zeros':
				constraints.zeros = 'strict';
				_mappedCount++;
				break;
			case 'no-penalty-for-extraneous-zeros':
				constraints.zeros = 'off';
				_mappedCount++;
				break;

			// ================================================================
			// CONSTRAINT OPTIONS - Null terms (CE pattern matching)
			// ================================================================
			case 'require-no-null-terms':
				constraints.nullTerms = 'strict';
				_mappedCount++;
				break;
			case 'no-penalty-for-null-terms':
				constraints.nullTerms = 'off';
				_mappedCount++;
				break;

			// ================================================================
			// CONSTRAINT OPTIONS - Factor one (CE pattern matching)
			// ================================================================
			case 'require-no-factor-one':
				constraints.factorOne = 'strict';
				_mappedCount++;
				break;
			case 'no-penalty-for-factor-one':
				constraints.factorOne = 'off';
				_mappedCount++;
				break;

			// ================================================================
			// CONSTRAINT OPTIONS - Factor zero (CE pattern matching)
			// ================================================================
			case 'require-no-factor-zero':
				constraints.factorZero = 'strict';
				_mappedCount++;
				break;
			case 'no-penalty-for-factor-zero':
				constraints.factorZero = 'off';
				_mappedCount++;
				break;

			// ================================================================
			// CONSTRAINT OPTIONS - Signs (CE pattern matching)
			// ================================================================
			case 'require-no-extraneous-signs':
				constraints.signs = 'strict';
				_mappedCount++;
				break;
			case 'no-penalty-for-extraneous-signs':
				constraints.signs = 'off';
				_mappedCount++;
				break;

			// ================================================================
			// FRACTION OPTIONS → constraints.reducedFractions
			// ================================================================
			case 'require-reduced-fractions':
				// Require fractions to be reduced to lowest terms
				constraints.reducedFractions = 'strict';
				_mappedCount++;
				break;
			case 'no-penalty-for-non-reduced-fractions':
				// Don't penalize non-reduced fractions
				constraints.reducedFractions = 'off';
				_mappedCount++;
				break;

			// ================================================================
			// SHUFFLE CHOICES - Implemented
			// ================================================================
			case 'no-shuffle-choices':
				options.shuffleChoices = false;
				_mappedCount++;
				break;

			// ================================================================
			// UNIT CONSTRAINT - Implemented (same pattern as other constraints)
			// ================================================================
			case 'require-specific-unit':
				constraints.unit = 'strict';
				_mappedCount++;
				break;
			case 'no-penalty-for-not-respected-unit':
				constraints.unit = 'off';
				_mappedCount++;
				break;

			// ================================================================
			// NOT IMPLEMENTED - VALIDATION OPTIONS (generate warnings)
			// ================================================================
			case 'solutions-order-not-important':
				if (oldFormats && oldFormats.length > 0) {
					// Question has a formats field (e.g. "$e[2;99]*$e[2;99]")
					// This is a single-answer question with multiple valid solutions.
					// Convert format to requiredForm pattern + use numerical equivalence.
					// The old format "$e[2;99]*$e[2;99]" becomes a product-of-integers pattern.
					requiredForm = { pattern: 'a:inN & gte(2) * b:inN & gte(2)' };
					_mappedCount++;
				} else {
					// Multi-answer question where order doesn't matter
					// (e.g., absolute value equations, polynomial roots)
					options.orderIndependent = true;
					_mappedCount++;
				}
				break;
			case 'disallow-factors-permutation':
				// Redundant with products constraint since the LaTeX parser
				// rejects wrong-order implicit multiplication (e.g. a3, √2·3).
				// The only way to write wrong-order factors is with explicit ×,
				// which products:'strict' already catches.
				if (!constraints.products || constraints.products !== 'strict') {
					constraints.products = 'strict';
				}
				_mappedCount++;
				break;
			case 'penalty-for-factors-permutation':
				// Redundant with products constraint (same reasoning as above).
				// Default products mode is 'warn' which gives partial credit,
				// matching the old penalty behavior.
				_mappedCount++;
				break;
			case 'disallow-terms-permutation':
			case 'disallow-terms-and-factors-permutation':
			case 'penalty-for-terms-permutation':
			case 'penalty-for-terms-and-factors-permutation':
				// No questions use these (0 occurrences) — ignore silently
				_mappedCount++;
				break;
			case 'one-single-form-solution':
				// Requires structural match (strictlyEquals in old system).
				// The solution "0-&1" must be written exactly as 0 minus something.
				requiredForm = { pattern: '0 - a' };
				_mappedCount++;
				break;

			// ================================================================
			// DISPLAY GENERATION OPTIONS → defaultDisplayOptions
			// ================================================================
			case 'shuffle-terms':
				displayOptions.shuffleTerms = true;
				_mappedCount++;
				break;
			case 'shuffle-factors':
				displayOptions.shuffleFactors = true;
				_mappedCount++;
				break;
			case 'shuffle-terms-and-factors':
				displayOptions.shuffleTermsAndFactors = true;
				_mappedCount++;
				break;
			case 'shallow-shuffle-terms':
				displayOptions.shallowShuffleTerms = true;
				_mappedCount++;
				break;
			case 'shallow-shuffle-factors':
				displayOptions.shallowShuffleFactors = true;
				_mappedCount++;
				break;
			case 'remove-null-terms':
				displayOptions.removeNullTerms = true;
				_mappedCount++;
				break;

			// ================================================================
			// NOT IMPLEMENTED - GENERATION OPTIONS (generate warnings)
			// ================================================================
			case 'exhaust':
				// TODO: Generate all possible variations without repetition
				warnings.push(`TODO: ${option} - exhaustive generation not yet implemented`);
				break;

			// ================================================================
			// LATEX FORMATTING OPTIONS → defaultDisplayOptions
			// ================================================================
			case 'exp-no-spaces':
				displayOptions.removeSpaces = true;
				_mappedCount++;
				break;
			case 'exp-remove-unecessary-brackets':
				displayOptions.removeUnnecessaryBrackets = true;
				_mappedCount++;
				break;
			// ================================================================
			// DISPLAY OPTIONS - Silently ignored (cosmetic only)
			// ================================================================
			case 'exp-allow-unecessary-zeros':
			case 'enounce-no-spaces':
				// Display formatting options - cosmetic only, safe to ignore
				_mappedCount++;
				break;

			// ================================================================
			// LEGACY OPTIONS - Silently ignored (not needed)
			// ================================================================
			case 'allow-same-expression':
			case 'allow-same-enounce':
			case 'multiples':
				// Legacy generation uniqueness options - not needed in new system
				_mappedCount++;
				break;

			default:
				warnings.push(`Unknown option: ${option} - needs manual review`);
		}
	}

	// Add constraints to options if any were set
	if (Object.keys(constraints).length > 0) {
		options.constraints = constraints;
	}

	// Build result object
	const hasOptions = Object.keys(options).length > 0;
	const hasDisplayOptions = Object.keys(displayOptions).length > 0;

	return {
		options: hasOptions ? options : undefined,
		defaultDisplayOptions: hasDisplayOptions ? displayOptions : undefined,
		requiredForm
	};
}

// ============================================================================
// TESTANSWERS CONVERSION
// ============================================================================

/**
 * Convert old testAnswerss patterns to typed ValidationRule objects
 *
 * Handles these patterns from old questions:
 * - `&answer>0` → PredicateRule or RangeRule
 * - `&answer!=0 && &answer!=1` → CustomExpressionRule (exclude values)
 * - `mod(&1;&answer)=0` → DivisorRule
 * - Complex boolean expressions → CustomExpressionRule
 *
 * @param testAnswers - Array of test answer expressions for a variation
 * @param warnings - Array to collect warnings
 * @returns Array of ValidationRule objects, or undefined if no valid rules
 */
function convertTestAnswers(
	testAnswers: string[] | undefined,
	warnings: string[]
): ValidationRule[] | undefined {
	if (!testAnswers || testAnswers.length === 0) {
		return undefined;
	}

	const rules: ValidationRule[] = [];

	for (const expr of testAnswers) {
		const rule = parseTestAnswerExpression(expr, warnings);
		if (rule) {
			rules.push(rule);
		}
	}

	return rules.length > 0 ? rules : undefined;
}

/**
 * Parse a single testAnswer expression and convert to ValidationRule
 *
 * @param expression - The test answer expression
 * @param warnings - Array to collect warnings
 * @returns A ValidationRule or undefined if parsing failed
 */
function parseTestAnswerExpression(
	expression: string,
	warnings: string[]
): ValidationRule | undefined {
	// Normalize the expression
	const normalized = expression.trim();

	// Pattern: &answer>0 (positive check)
	if (/^&answer\s*>\s*0$/i.test(normalized)) {
		return {
			type: 'predicate',
			predicate: 'isPositive'
		};
	}

	// Pattern: &answer>=0 (non-negative)
	if (/^&answer\s*>=\s*0$/i.test(normalized)) {
		return {
			type: 'range',
			min: '0',
			max: 'Infinity',
			inclusive: true
		};
	}

	// Pattern: &answer<0 (negative check)
	if (/^&answer\s*<\s*0$/i.test(normalized)) {
		return {
			type: 'predicate',
			predicate: 'isNegative'
		};
	}

	// Pattern: mod(&var;&answer)=0 (divisor check)
	// e.g., mod(&1;&answer)=0 → answer divides &1
	const divisorMatch = normalized.match(/mod\s*\(\s*(&\d+(?:\*&\d+)*)\s*;\s*&answer\s*\)\s*=\s*0/i);
	if (divisorMatch) {
		const dividend = convertVariableReference(divisorMatch[1]);
		return {
			type: 'divisor',
			dividend
		};
	}

	// Pattern: &answer > min && &answer < max (range check)
	const rangeMatch = normalized.match(
		/&answer\s*([><]=?)\s*(\d+|&\d+)\s*&&\s*&answer\s*([><]=?)\s*(\d+|&\d+)/i
	);
	if (rangeMatch) {
		const [, op1, val1, op2, val2] = rangeMatch;
		let min = '',
			max = '';
		let inclusive = false;

		// Figure out which is min and which is max
		if (op1.includes('>') && op2.includes('<')) {
			min = convertVariableReference(val1);
			max = convertVariableReference(val2);
			inclusive = op1.includes('=') || op2.includes('=');
		} else if (op1.includes('<') && op2.includes('>')) {
			min = convertVariableReference(val2);
			max = convertVariableReference(val1);
			inclusive = op1.includes('=') || op2.includes('=');
		}

		if (min && max) {
			return {
				type: 'range',
				min,
				max,
				inclusive
			};
		}
	}

	// For complex expressions, use CustomExpressionRule as fallback
	// Convert old syntax to new syntax first
	const convertedExpr = convertTestAnswerSyntax(normalized);

	warnings.push(`testAnswer expression converted to custom rule: ${expression}`);

	return {
		type: 'custom',
		expression: convertedExpr,
		description: `Legacy testAnswer: ${expression}`
	};
}

/**
 * Convert old testAnswer syntax to new format
 *
 * - &answer → answer
 * - &N → {{varN}} (variable reference)
 * - mod(a;b) → (a % b)
 * - != → !== (for consistency)
 *
 * @param expression - Old testAnswer expression
 * @returns Converted expression
 */
function convertTestAnswerSyntax(expression: string): string {
	let result = expression;

	// Convert &answer to 'answer'
	result = result.replace(/&answer/gi, 'answer');

	// Convert &N to letter name (a, b, c, ...) using bare variable names
	// This is consistent with how variables are named in the rest of the transformation
	result = result.replace(/&(\d+)/g, (_, num) => numberToLetterName(parseInt(num, 10)));

	// Convert mod(a;b) to (a % b === 0 ? true : false) or keep as mod function call
	result = result.replace(/mod\s*\(\s*([^;]+)\s*;\s*([^)]+)\s*\)\s*=\s*0/gi, '($1 % $2 === 0)');

	// Convert != to !== for strict comparison
	result = result.replace(/!=/g, '!==');

	return result;
}

/**
 * Convert old variable reference (&1, &2, etc.) to letter names
 *
 * @param varRef - Old variable reference like "&1" or "&1*&2"
 * @returns Letter name like "a" or "a * b"
 */
function convertVariableReference(varRef: string): string {
	// Handle compound expressions like &1*&2
	if (varRef.includes('*')) {
		return varRef.replace(/&(\d+)/g, (_, num) => numberToLetterName(parseInt(num, 10)));
	}

	// Simple variable reference
	const match = varRef.match(/^&(\d+)$/);
	if (match) {
		return numberToLetterName(parseInt(match[1], 10));
	}

	// Numeric literal
	if (/^\d+$/.test(varRef)) {
		return varRef;
	}

	// Unknown format, return as-is
	return varRef;
}

// ============================================================================
// CATEGORY ASSIGNMENT
// ============================================================================

/**
 * Assign category based on old question structure
 */
function assignCategory(oldQuestion: QuestionBase): {
	theme: string;
	domain: string;
	subdomain?: string;
	level: number;
} {
	// Use _migration metadata when available (injected by export script)
	const migration = (oldQuestion as Record<string, unknown>)._migration as
		| { theme: string; domain: string; subdomain?: string; level: number }
		| undefined;
	if (migration?.theme && migration?.domain && typeof migration?.level === 'number') {
		return {
			theme: migration.theme,
			domain: migration.domain,
			subdomain: migration.subdomain,
			level: migration.level
		};
	}

	// Fallback: guess from description and grade
	const description = oldQuestion.description.toLowerCase();

	// Try to detect theme from description
	let theme = 'Nombres';
	let domain = 'Arithmétique';
	let subdomain: string | undefined;

	if (description.includes('fraction')) {
		theme = 'Nombres';
		domain = 'Fractions';
	} else if (description.includes('équation') || description.includes('equation')) {
		theme = 'Algèbre';
		domain = 'Équations';
	} else if (
		description.includes('géométr') ||
		description.includes('angle') ||
		description.includes('triangle')
	) {
		theme = 'Géométrie';
		domain = 'Figures planes';
	} else if (description.includes('fonction')) {
		theme = 'Fonctions';
		domain = 'Généralités';
	} else if (description.includes('probabilité') || description.includes('statistique')) {
		theme = 'Probabilités et statistiques';
		domain = 'Probabilités';
	} else if (description.includes('addition') || description.includes('soustraction')) {
		theme = 'Nombres';
		domain = 'Opérations';
		subdomain = description.includes('addition') ? 'Addition' : 'Soustraction';
	} else if (description.includes('multiplication') || description.includes('division')) {
		theme = 'Nombres';
		domain = 'Opérations';
		subdomain = description.includes('multiplication') ? 'Multiplication' : 'Division';
	}

	// Assign level based on grade
	const gradeLevel = oldQuestion.grade;
	let level = 1;

	if (['CP', 'CE1'].includes(gradeLevel)) {
		level = 1;
	} else if (['CE2', 'CM1', 'CM2'].includes(gradeLevel)) {
		level = 2;
	} else if (['6', '5'].includes(gradeLevel)) {
		level = 3;
	} else if (['4', '3'].includes(gradeLevel)) {
		level = 4;
	} else if (['2', 'SPE_1', 'SPE_T'].includes(gradeLevel)) {
		level = 5;
	} else {
		level = 6;
	}

	return { theme, domain, subdomain, level };
}

// ============================================================================
// SHARED FIELDS DETECTION
// ============================================================================

/**
 * Result of shared fields detection
 */
interface SharedFieldsResult {
	/** Shared defaults that apply to all variations */
	shared: SharedVariationDefaults;
	/** Per-variation data that differs between variations */
	perVariation: Partial<QuestionVariation>[];
}

/**
 * Detect which fields are shared across all variations.
 *
 * In TinyMath, an array with 1 element for N variations means the field is shared.
 * For example:
 * - `enounces.length === 1` with `variationCount > 1` → shared statement
 * - `variabless.length === 1` with `variationCount > 1` → shared variables
 * - `solutionss.length === 1` with `variationCount > 1` → shared solution
 * - etc.
 *
 * @param oldQuestion - The old TinyMath question
 * @param variationCount - Number of variations detected
 * @param questionType - The detected question type
 * @param imageMapping - Optional mapping for image URLs
 * @param warnings - Array to collect warnings
 * @param stats - Stats object to track conversions
 * @returns Object containing shared defaults and per-variation data
 */
function detectSharedFields(
	oldQuestion: QuestionBase,
	variationCount: number,
	migrationMode: MigrationMode,
	imageMapping: ImageUrlMapping | undefined,
	warnings: string[],
	stats: TransformStats
): SharedFieldsResult {
	const shared: SharedVariationDefaults = {};
	const perVariation: Partial<QuestionVariation>[] = Array.from(
		{ length: variationCount },
		() => ({})
	);

	// Get images array (shared across all variations in old format)
	const images = oldQuestion.images;

	// ---- Detect enounces sharing (→ statement) ----
	const enounces = oldQuestion.enounces || [];
	const expressions = oldQuestion.expressions || [];
	const answerFields = oldQuestion.answerFields || [];

	// Collect expression variables to add to perVariation later (after regular variables)
	const expressionVariables: (QuestionVariable | undefined)[] = [];

	if (migrationMode === 'answer_field') {
		// AnswerField mode: convert answerField to statement with $?$
		// The answerField replaces the expression in the statement
		const answerFieldIsShared = answerFields.length === 1 && variationCount > 1;
		const enounceIsShared = enounces.length === 1 && variationCount > 1;

		if (answerFieldIsShared && (enounceIsShared || enounces.length === 0)) {
			// Shared answerField
			const enonce = enounces[0];
			const convertedField = convertAnswerFieldToStatement(answerFields[0], warnings);
			const parts: string[] = [];
			if (enonce) {
				const enonceResult = convertTinyCASToNew(enonce);
				parts.push(enonceResult.converted || enonce);
			}
			parts.push(convertedField);
			shared.statement = templateMarkdown(fixMathDelimiters(parts.join('\n\n')));
			for (let i = 0; i < variationCount; i++) {
				perVariation[i].statement = shared.statement;
				expressionVariables.push(undefined); // No expression variable for answerField
			}
		} else {
			// Per-variation answerField
			for (let i = 0; i < variationCount; i++) {
				const enonce = enounces[i] || enounces[0];
				const af = answerFields[i] || answerFields[0];
				const convertedField = convertAnswerFieldToStatement(af, warnings);
				const parts: string[] = [];
				if (enonce) {
					const enonceResult = convertTinyCASToNew(enonce);
					parts.push(enonceResult.converted || enonce);
				}
				parts.push(convertedField);
				perVariation[i].statement = templateMarkdown(fixMathDelimiters(parts.join('\n\n')));
				expressionVariables.push(undefined); // No expression variable for answerField
			}
		}
	} else {
		// Standard mode: enounce + expression → statement
		const enounceIsShared = enounces.length === 1 && variationCount > 1;
		const expressionIsShared =
			(expressions.length === 0 || expressions.length === 1) && variationCount > 1;
		const statementIsShared =
			(enounceIsShared || enounces.length === 0) &&
			(expressionIsShared || expressions.length === 0);

		if (statementIsShared) {
			// Shared enounce AND shared/no expression - generate statement once
			const enonce = enounces[0];
			const expression = expressions[0];
			const result = convertStatement(
				enonce,
				expression,
				1, // Always expression1 when shared
				images,
				imageMapping,
				warnings,
				stats
			);
			shared.statement = result.statement;
			// All variations share the same statement and expression variable
			for (let i = 0; i < variationCount; i++) {
				perVariation[i].statement = result.statement;
				expressionVariables.push(result.expressionVariable);
			}
		} else {
			// Per-variation statements or expressions
			for (let i = 0; i < variationCount; i++) {
				const enonce = enounces[i] || enounces[0];
				const expression = expressions[i] || expressions[0];
				const result = convertStatement(
					enonce,
					expression,
					i + 1, // expressionIndex varies per variation
					images,
					imageMapping,
					warnings,
					stats
				);
				perVariation[i].statement = result.statement;
				expressionVariables.push(result.expressionVariable);
			}
		}
	}

	// ---- Detect variabless sharing (→ variables) ----
	const variabless = oldQuestion.variabless || [];
	const variablesIsShared = variabless.length === 1 && variationCount > 1;

	if (variablesIsShared) {
		const convertedVars = convertVariables(variabless[0], warnings);
		if (convertedVars && convertedVars.length > 0) {
			shared.variables = convertedVars;
			stats.variables += convertedVars.length;
		}
	} else {
		for (let i = 0; i < variationCount; i++) {
			const variables = variabless[i] || variabless[0];
			const convertedVars = convertVariables(variables, warnings);
			if (convertedVars && convertedVars.length > 0) {
				perVariation[i].variables = convertedVars;
				stats.variables += convertedVars.length;
			}
		}
	}

	// ---- Add expression variables AFTER regular variables (for correct resolution order) ----
	for (let i = 0; i < variationCount; i++) {
		const exprVar = expressionVariables[i];
		if (exprVar) {
			if (!perVariation[i].variables) {
				perVariation[i].variables = [];
			}
			perVariation[i].variables!.push(exprVar);
		}
	}

	// ---- Handle expressions2 (creates expression2 variable for QCM with 2 expressions) ----
	const expressions2 = oldQuestion.expressions2 || [];
	if (expressions2.length > 0) {
		for (let i = 0; i < variationCount; i++) {
			const expr2 = expressions2[i] || expressions2[0];
			if (expr2) {
				const conversionResult = convertTinyCASToNew(expr2);
				const afterTinyCAS = conversionResult.converted || expr2;
				const bareExpr = toBareVariableSyntax(toSimplifiedSyntax(afterTinyCAS));

				const expr2Var: QuestionVariable = {
					name: `expression${2}`,
					expression: bareExpr
				};

				if (!perVariation[i].variables) {
					perVariation[i].variables = [];
				}
				perVariation[i].variables!.push(expr2Var);

				// Update statement to also reference expression2
				const currentStatement = String(perVariation[i].statement ?? shared.statement ?? '');
				if (!currentStatement.includes('{{expression2}}')) {
					const updatedStatement = currentStatement + '\n\n$${{expression2}}$$';
					perVariation[i].statement = templateMarkdown(updatedStatement);
				}
			}
		}
	}

	// ---- Detect solutionss sharing (→ solution) ----
	// Only create solution for multiple_choice. For fill_in_blanks modes,
	// blanks[] is the source of truth (created in createVariationsWithShared).
	const solutionss = oldQuestion.solutionss || [];
	const solutionIsShared = solutionss.length === 1 && variationCount > 1;

	if (migrationMode === 'multiple_choice') {
		// MC needs solution (correct answer index/indices)
		if (solutionss.length > 0) {
			if (solutionIsShared) {
				shared.correctChoiceIndex = convertSolution(solutionss[0], 'multiple_choice', warnings);
			} else {
				for (let i = 0; i < variationCount; i++) {
					const solutions = solutionss[i] || solutionss[0];
					perVariation[i].correctChoiceIndex = convertSolution(
						solutions,
						'multiple_choice',
						warnings
					);
				}
			}
		}
	}
	// For non-MC modes: blanks[] will be created in createVariationsWithShared

	// ---- Detect correction sharing (correctionDetailss + correctionFormats) ----
	const correctionDetailss = oldQuestion.correctionDetailss || [];
	const correctionFormats = oldQuestion.correctionFormats || [];
	const hasCorrections = correctionDetailss.length > 0 || correctionFormats.length > 0;

	// Correction is shared if both arrays have 0 or 1 elements for multiple variations
	const detailsIsShared = correctionDetailss.length <= 1 && variationCount > 1;
	const formatsIsShared = correctionFormats.length <= 1 && variationCount > 1;
	const correctionIsShared = detailsIsShared && formatsIsShared;

	if (correctionIsShared && hasCorrections) {
		// Multiple variations, single correction → shared
		const questionCorrection = transformCorrection(
			correctionDetailss[0],
			correctionFormats[0],
			warnings,
			stats
		);
		if (questionCorrection) {
			shared.correction = questionCorrection;
		}
	} else if (correctionDetailss.length > 1 || correctionFormats.length > 1) {
		// Multiple corrections → per-variation
		for (let i = 0; i < variationCount; i++) {
			const correctionDetails = correctionDetailss[i] || correctionDetailss[0];
			const correctionFormat = correctionFormats[i] || correctionFormats[0];
			const questionCorrection = transformCorrection(
				correctionDetails,
				correctionFormat,
				warnings,
				stats
			);
			if (questionCorrection) {
				perVariation[i].correction = questionCorrection;
			}
		}
	} else if (variationCount === 1 && hasCorrections) {
		// Single variation with correction → per-variation[0]
		const questionCorrection = transformCorrection(
			correctionDetailss[0],
			correctionFormats[0],
			warnings,
			stats
		);
		if (questionCorrection) {
			perVariation[0].correction = questionCorrection;
		}
	}

	// ---- Detect choices sharing (for multiple_choice) ----
	const choicess = oldQuestion.choicess || [];
	const choicesIsShared = choicess.length === 1 && variationCount > 1;

	if (migrationMode === 'multiple_choice' && choicess.length > 0) {
		// For QCM, choices don't have isCorrect - the correct choice is determined
		// at runtime by evaluating the solution (which contains the correct index)
		if (choicesIsShared) {
			shared.choices = convertChoices(choicess[0], imageMapping, warnings, stats);
		} else {
			for (let i = 0; i < variationCount; i++) {
				const choices = choicess[i] || choicess[0];
				perVariation[i].choices = convertChoices(choices, imageMapping, warnings, stats);
			}
		}
	}

	// ---- Detect testAnswerss sharing (→ validationRules) ----
	const testAnswerss = oldQuestion.testAnswerss || [];
	const testAnswersIsShared = testAnswerss.length === 1 && variationCount > 1;

	if (testAnswerss.length > 0) {
		if (testAnswersIsShared) {
			const validationRules = convertTestAnswers(testAnswerss[0], warnings);
			if (validationRules && validationRules.length > 0) {
				shared.validationRules = validationRules;
			}
		} else {
			for (let i = 0; i < variationCount; i++) {
				const testAnswers = testAnswerss[i] || testAnswerss[0];
				const validationRules = convertTestAnswers(testAnswers, warnings);
				if (validationRules && validationRules.length > 0) {
					perVariation[i].validationRules = validationRules;
				}
			}
		}
	}

	return { shared, perVariation };
}

/**
 * Check if shared object has any meaningful content
 */
function hasSharedContent(shared: SharedVariationDefaults): boolean {
	return !!(
		shared.statement ||
		(shared.variables && shared.variables.length > 0) ||
		shared.correctChoiceIndex !== undefined ||
		shared.correction ||
		(shared.choices && shared.choices.length > 0) ||
		(shared.validationRules && shared.validationRules.length > 0) ||
		(shared.answerFormats && Object.keys(shared.answerFormats).length > 0) ||
		shared.blankDefaults ||
		shared.requiredForm
	);
}

// ============================================================================
// VARIATION CREATION
// ============================================================================

/**
 * Create variations from old question structure with shared field detection
 *
 * @param oldQuestion - The old question object
 * @param questionType - Detected question type
 * @param imageMapping - Optional mapping from old image paths to new URLs
 * @param warnings - Array to collect warnings
 * @param stats - Stats object to track conversions
 * @returns Object containing variations and optionally shared defaults
 */
function createVariationsWithShared(
	oldQuestion: QuestionBase,
	migrationMode: MigrationMode,
	imageMapping: ImageUrlMapping | undefined,
	warnings: string[],
	stats: TransformStats
): { variations: QuestionVariation[]; shared?: SharedVariationDefaults } {
	const variationCount = getVariationCount(oldQuestion);
	stats.variations = variationCount;

	// Detect shared fields
	const { shared, perVariation } = detectSharedFields(
		oldQuestion,
		variationCount,
		migrationMode,
		imageMapping,
		warnings,
		stats
	);

	// Handle blanks based on migration mode
	const expressions = oldQuestion.expressions || [];
	const solutionss = oldQuestion.solutionss || [];
	const oldAnswerFormats = oldQuestion.answerFormats || [];

	if (migrationMode === 'fill_in') {
		// Fill-in: expressions with ? → blanks from expression
		for (let i = 0; i < variationCount; i++) {
			const expression = expressions[i] || expressions[0];
			const solutions = solutionss[i] || solutionss[0];
			if (expression) {
				const blanks = extractBlanks(expression, solutions, warnings);
				if (blanks && blanks.length > 0) {
					perVariation[i].blanks = blanks;
				}
			}
		}
	} else if (migrationMode === 'result_rewrite') {
		// Result/rewrite: blanks from solutionss, answerFormats extracted
		const hasSharedAnswerFormat = oldAnswerFormats.length === 1 && variationCount > 1;
		const sharedAnswerFormat = oldAnswerFormats[0]; // undefined when no formats

		// Extract answerFormats to shared when single format for multiple variations
		if (hasSharedAnswerFormat && sharedAnswerFormat) {
			const exprVarName = expressions.length <= 1 ? 'expression1' : undefined;
			if (exprVarName) {
				shared.answerFormats = { [exprVarName]: sharedAnswerFormat };
			}
		}

		for (let i = 0; i < variationCount; i++) {
			const solutions = solutionss[i] || solutionss[0];
			const answerFormat = oldAnswerFormats[i] || oldAnswerFormats[0];
			const exprVarName = expressions.length <= 1 ? 'expression1' : `expression${i + 1}`;

			const blanks = extractBlanksFromSolutions(solutions, answerFormat, exprVarName, warnings);
			if (blanks.length > 0) {
				perVariation[i].blanks = blanks;
			}

			// Per-variation answerFormats (when not shared)
			if (answerFormat && !hasSharedAnswerFormat) {
				perVariation[i].answerFormats = { [exprVarName]: answerFormat };
			}
		}
	} else if (migrationMode === 'answer_field') {
		// AnswerField: blanks from solutionss, count from $$...$$ in answerField
		const answerFields = oldQuestion.answerFields || [];

		for (let i = 0; i < variationCount; i++) {
			const solutions = solutionss[i] || solutionss[0];
			const af = answerFields[i] || answerFields[0];

			// Count blanks from $$...$$ markers in answerField
			const blankCount = af ? (af.match(/\$\$\.\.\.\$\$/g) || []).length : 0;

			if (solutions && solutions.length > 0 && blankCount > 0) {
				const blanks = extractBlanksFromSolutions(
					solutions,
					undefined, // No answerFormat for answerFields
					undefined, // No expression variable
					warnings,
					blankCount
				);
				if (blanks.length > 0) {
					perVariation[i].blanks = blanks;
				}
			}
		}
	}

	// Build variations array from per-variation data
	const variations: QuestionVariation[] = perVariation.map((pv, index) => {
		// Start with required fields - use shared fallback or throw error
		const statement = pv.statement || shared.statement;
		const correctChoiceIndex = pv.correctChoiceIndex ?? shared.correctChoiceIndex;

		if (!statement) {
			warnings.push(`Variation ${index}: missing statement`);
		}
		// Only warn about missing correctChoiceIndex for multiple_choice
		if (correctChoiceIndex === undefined && migrationMode === 'multiple_choice') {
			warnings.push(`Variation ${index}: missing correctChoiceIndex`);
		}

		const variation: QuestionVariation = {
			statement: statement || templateMarkdown('')
		};

		// correctChoiceIndex only for multiple_choice
		if (correctChoiceIndex !== undefined) {
			variation.correctChoiceIndex = correctChoiceIndex;
		}

		// Add optional fields only if they exist and are NOT shared
		if (pv.variables && pv.variables.length > 0) {
			variation.variables = pv.variables;
		}
		if (pv.correction) {
			variation.correction = pv.correction;
		}
		if (pv.choices && pv.choices.length > 0) {
			variation.choices = pv.choices;
		}
		if (pv.validationRules && pv.validationRules.length > 0) {
			variation.validationRules = pv.validationRules;
		}
		if (pv.blanks && pv.blanks.length > 0) {
			variation.blanks = pv.blanks;
		}
		if (pv.answerFormats && Object.keys(pv.answerFormats).length > 0) {
			variation.answerFormats = pv.answerFormats;
		}

		return variation;
	});

	// Return shared only if it has meaningful content
	return {
		variations,
		shared: hasSharedContent(shared) ? shared : undefined
	};
}

/**
 * Extract blank positions and answers from expression with ?
 */
function extractBlanks(
	expression: string,
	solutions: (string | number)[] | undefined,
	warnings: string[]
): QuestionVariation['blanks'] {
	const blanks: NonNullable<QuestionVariation['blanks']> = [];

	// Count ? marks in expression
	const questionMarks = (expression.match(/\?/g) || []).length;

	if (questionMarks === 0) {
		warnings.push('Fill-in-blanks detected but no ? marks found in expression');
		return undefined;
	}

	// Each ? corresponds to a solution
	for (let i = 0; i < questionMarks; i++) {
		const answer = solutions?.[i];
		if (answer !== undefined) {
			const conversionResult = convertTinyCASToNew(String(answer));
			blanks.push({
				position: i,
				expectedAnswer: conversionResult.converted || String(answer)
			});
		} else {
			warnings.push(`Missing solution for blank at position ${i}`);
			blanks.push({
				position: i,
				expectedAnswer: ''
			});
		}
	}

	return blanks.length > 0 ? blanks : undefined;
}

// ============================================================================
// MAIN TRANSFORMER
// ============================================================================

/**
 * Transform a single old question to new format
 *
 * @param oldQuestion - The old TinyMath question object
 * @param questionIndex - Index of this question in the batch
 * @param options - Transformation options
 * @param options.skipImages - If true, skip questions with images
 * @param options.skipCustomValidation - If true, skip questions with testAnswers
 * @param options.imageUrlMapping - Optional mapping from old image paths to new Supabase URLs
 * @returns Transformation result with template, warnings, errors, and stats
 */
export function transformQuestion(
	oldQuestion: QuestionBase,
	questionIndex: number,
	options?: {
		skipImages?: boolean;
		skipCustomValidation?: boolean;
		imageUrlMapping?: ImageUrlMapping;
	}
): TransformResult {
	const warnings: string[] = [];
	const errors: string[] = [];
	const stats: TransformStats = {
		variations: 0,
		variables: 0,
		syntaxConversions: 0,
		optionsMapped: 0,
		displayOptionsMapped: 0,
		correctionConversions: 0,
		detectedType: '',
		hasImages: false,
		hasCustomValidation: false,
		imagesConverted: 0,
		imagesMissing: 0,
		asciiMathConverted: 0
	};

	try {
		// Check for unsupported features
		if (hasImages(oldQuestion)) {
			stats.hasImages = true;
			if (options?.skipImages && !options?.imageUrlMapping) {
				// Only skip if no image mapping provided
				errors.push('Question contains images - skipping for Phase 1');
				return { success: false, errors, stats };
			} else if (!options?.imageUrlMapping) {
				warnings.push('Question contains images - will need manual review');
			}
			// If imageUrlMapping is provided, proceed with conversion
		}

		if (hasTestAnswers(oldQuestion)) {
			stats.hasCustomValidation = true;
			if (options?.skipCustomValidation) {
				errors.push('Question has custom validation - skipping for Phase 1');
				return { success: false, errors, stats };
			} else {
				warnings.push(
					'Question has custom validation (testAnswers) - needs Phase 4 implementation'
				);
			}
		}

		// Detect migration mode + legacy type for stats
		const migrationMode = detectMigrationMode(oldQuestion);
		stats.detectedType = detectQuestionType(oldQuestion);

		// Create variations with shared field detection
		const sharedResult = createVariationsWithShared(
			oldQuestion,
			migrationMode,
			options?.imageUrlMapping,
			warnings,
			stats
		);
		const variations = sharedResult.variations;
		let shared = sharedResult.shared;

		if (variations.length === 0) {
			errors.push('No variations could be created');
			return { success: false, errors, warnings, stats };
		}

		// Convert options
		const {
			options: convertedOptions,
			defaultDisplayOptions,
			requiredForm
		} = convertOptions(oldQuestion.options, warnings, oldQuestion.formats);
		if (convertedOptions) {
			stats.optionsMapped = Object.keys(convertedOptions).length;
		}
		if (defaultDisplayOptions) {
			stats.displayOptionsMapped = Object.keys(defaultDisplayOptions).length;

			// Attach displayOptions to expression variables (not template-level defaultDisplayOptions)
			// In the old system, display options like exp-no-spaces, exp-remove-unecessary-brackets,
			// shuffle-terms, remove-null-terms all apply to the expression field,
			// which is now a variable named "expressionN".
			for (const variation of variations) {
				if (variation.variables) {
					for (const variable of variation.variables) {
						if (variable.name.startsWith('expression')) {
							variable.displayOptions = { ...defaultDisplayOptions };
						}
					}
				}
			}
			// Also check shared variables
			if (shared?.variables) {
				for (const variable of shared.variables) {
					if (variable.name.startsWith('expression')) {
						variable.displayOptions = { ...defaultDisplayOptions };
					}
				}
			}
		}

		// Apply requiredForm to shared (applies to all variations)
		if (requiredForm) {
			if (!shared) {
				shared = {};
			}
			shared.requiredForm = requiredForm;
		}

		// Assign category
		const category = assignCategory(oldQuestion);

		// Create template (without id/audit fields - will be auto-generated by database)
		// Apply fixMathDelimiters to title, description, and help text
		// NOTE: `type` is no longer stored — it's inferred from structure (choices present → MC)
		const template: Omit<QuestionTemplate, 'id' | 'created_at' | 'updated_at' | 'created_by'> = {
			title: fixMathDelimiters(oldQuestion.description),
			description: oldQuestion.subdescription
				? fixMathDelimiters(oldQuestion.subdescription)
				: undefined,
			shared, // Include shared defaults when fields are reused across variations
			variations,
			exerciseInstruction: oldQuestion.help ? fixMathDelimiters(oldQuestion.help) : undefined,
			options: convertedOptions,
			// displayOptions are attached to expression variables directly, not at template level
			grades: [mapGrade(oldQuestion.grade)],
			...category,
			status: 'draft', // Import as draft for review
			multipleAnswers: oldQuestion.multipleAnswers
		};

		// Add optional fields
		if (oldQuestion.defaultDelay > 0) {
			template.delay = oldQuestion.defaultDelay;
		}

		// Add precision for decimal questions (via shared blankDefaults)
		if (oldQuestion['result-type'] === 'decimal') {
			if (!template.shared) template.shared = {};
			template.shared.blankDefaults = {
				...template.shared.blankDefaults,
				precision: { type: 'decimal', digits: 2 }
			};
			warnings.push('Decimal precision set to 2 places by default - verify if correct');
		}

		return {
			success: true,
			template,
			warnings: warnings.length > 0 ? warnings : undefined,
			stats
		};
	} catch (error) {
		errors.push(`Unexpected error: ${error instanceof Error ? error.message : String(error)}`);
		return {
			success: false,
			errors,
			warnings: warnings.length > 0 ? warnings : undefined,
			stats
		};
	}
}

// ============================================================================
// BATCH TRANSFORMATION
// ============================================================================

/**
 * Transform multiple questions in batch
 *
 * @param questions - Array of old TinyMath questions to transform
 * @param options - Transformation options
 * @param options.skipImages - If true, skip questions with images (unless mapping provided)
 * @param options.skipCustomValidation - If true, skip questions with testAnswers
 * @param options.imageUrlMapping - Optional mapping from old image paths to new URLs
 * @param options.onProgress - Progress callback
 * @returns Results array and summary statistics
 */
export function transformQuestionBatch(
	questions: QuestionBase[],
	options?: {
		skipImages?: boolean;
		skipCustomValidation?: boolean;
		imageUrlMapping?: ImageUrlMapping;
		onProgress?: (current: number, total: number) => void;
	}
): {
	results: TransformResult[];
	summary: {
		total: number;
		successful: number;
		failed: number;
		warnings: number;
		skippedImages: number;
		skippedCustomValidation: number;
		imagesConverted: number;
		imagesMissing: number;
	};
} {
	const results: TransformResult[] = [];
	const summary = {
		total: questions.length,
		successful: 0,
		failed: 0,
		warnings: 0,
		skippedImages: 0,
		skippedCustomValidation: 0,
		imagesConverted: 0,
		imagesMissing: 0
	};

	for (let i = 0; i < questions.length; i++) {
		// Report progress
		if (options?.onProgress) {
			options.onProgress(i + 1, questions.length);
		}

		// Transform question
		const result = transformQuestion(questions[i], i, {
			skipImages: options?.skipImages,
			skipCustomValidation: options?.skipCustomValidation,
			imageUrlMapping: options?.imageUrlMapping
		});

		results.push(result);

		// Update summary
		if (result.success) {
			summary.successful++;
			if (result.warnings && result.warnings.length > 0) {
				summary.warnings++;
			}
			// Track image conversion stats
			if (result.stats) {
				summary.imagesConverted += result.stats.imagesConverted;
				summary.imagesMissing += result.stats.imagesMissing;
			}
		} else {
			summary.failed++;

			// Check why it failed
			if (result.stats?.hasImages) {
				summary.skippedImages++;
			}
			if (result.stats?.hasCustomValidation) {
				summary.skippedCustomValidation++;
			}
		}
	}

	return { results, summary };
}

// ============================================================================
// VALIDATION
// ============================================================================

/**
 * Validate a transformed template
 */
export function validateTransformedTemplate(template: QuestionTemplate): {
	valid: boolean;
	errors: string[];
} {
	const errors: string[] = [];

	// Check required fields
	if (!template.title) {
		errors.push('Missing title');
	}

	if (!template.variations || template.variations.length === 0) {
		errors.push('No variations provided');
	}

	if (!template.grades || template.grades.length === 0) {
		errors.push('No grades specified');
	}

	if (!template.theme) {
		errors.push('Missing theme');
	}

	if (!template.domain) {
		errors.push('Missing domain');
	}

	if (typeof template.level !== 'number' || template.level < 1) {
		errors.push('Invalid level');
	}

	if (!template.status) {
		errors.push('Missing status');
	}

	// Validate each variation (type inferred from structure)
	template.variations.forEach((variation, index) => {
		if (!variation.statement || variation.statement.length === 0) {
			errors.push(`Variation ${index}: missing statement`);
		}

		// For multiple_choice, choices must be present
		if (variation.choices && variation.choices.length > 0) {
			// This is a multiple_choice variation — correctChoiceIndex is required
			if (variation.correctChoiceIndex === undefined || variation.correctChoiceIndex === null) {
				errors.push(`Variation ${index}: missing correctChoiceIndex for multiple_choice`);
			}
		}
	});

	return {
		valid: errors.length === 0,
		errors
	};
}

// ============================================================================
// EXPORT
// ============================================================================

export default {
	transformQuestion,
	transformQuestionBatch,
	validateTransformedTemplate
};
