/**
 * Question Transformer - TinyMath to UbuMaths v2
 * ===============================================
 *
 * Comprehensive transformer for converting old TinyMath QuestionBase objects
 * to new UbuMaths v2 QuestionTemplate objects as part of Phase 1.4 of the
 * migration project.
 *
 * Features:
 * - Automatic question type detection
 * - Variable syntax conversion
 * - Answer format transformation
 * - Validation option mapping
 * - Comprehensive error handling
 * - Warning generation for manual review items
 *
 * @module migration/question-transformer
 */

import type {
	QuestionBase,
	OldGrade,
	Choice,
	CorrectionDetail,
	CorrectionFormat,
	Variables,
	// eslint-disable-next-line @typescript-eslint/no-unused-vars
	VariableName
} from './old-question-types';

import type {
	QuestionTemplate,
	QuestionType,
	QuestionVariation,
	QuestionVariable,
	QuestionCorrection,
	SharedVariationDefaults,
	// eslint-disable-next-line @typescript-eslint/no-unused-vars
	PrecisionType,
	AlgebraicTransformType,
	ValidationRule,
	ConstraintOptions
} from '$lib/questions/types';

import type { DisplayOptions, TemplateMarkdown } from '$lib/ubumark';
import { templateMarkdown } from '$lib/ubumark';

import {
	hasChoices,
	hasMultipleAnswers,
	hasFillInBlanks,
	hasAnswerFields,
	hasImages,
	// eslint-disable-next-line @typescript-eslint/no-unused-vars
	hasVariables,
	hasTestAnswers,
	getVariationCount,
	// eslint-disable-next-line @typescript-eslint/no-unused-vars
	detectQuestionType as detectOldQuestionType
} from './old-question-types';

// eslint-disable-next-line @typescript-eslint/no-unused-vars
import { convertTinyCASToNew, type ConversionResult } from './syntax-converter';
import { convertPlaceholders } from './placeholder-converter';
import { convertConditionals } from './conditional-converter';
import { convertAsciiMathToLatexSafe } from './ascii-math-converter';

// ============================================================================
// IMAGE URL MAPPING TYPE
// ============================================================================

/**
 * Mapping from old image paths to new Supabase Storage URLs
 *
 * The mapping supports multiple path formats for the same image:
 * - Full absolute path: /Users/david/Coding/js/ubumaths/static/images/questions/...
 * - Relative path: entiers/reperage/...
 * - With leading slash: /entiers/reperage/...
 * - With /images prefix: /images/entiers/reperage/...
 */
export type ImageUrlMapping = Record<string, string>;

/**
 * Look up new URL for an old image path
 *
 * Tries multiple path formats to find a match:
 * 1. Exact path as provided
 * 2. Without leading slash
 * 3. With /images/ prefix removed
 * 4. Normalized relative path
 *
 * @param oldPath - The old image path from the question
 * @param mapping - The image URL mapping object
 * @returns The new Supabase Storage URL, or undefined if not found
 */
function lookupImageUrl(oldPath: string, mapping: ImageUrlMapping): string | undefined {
	// Try exact match first
	if (mapping[oldPath]) {
		return mapping[oldPath];
	}

	// Try without leading slash
	const withoutLeadingSlash = oldPath.replace(/^\//, '');
	if (mapping[withoutLeadingSlash]) {
		return mapping[withoutLeadingSlash];
	}

	// Try with /images/ prefix removed
	const withoutImages = oldPath.replace(/^\/?images\//, '');
	if (mapping[withoutImages]) {
		return mapping[withoutImages];
	}

	// Try adding /images/ prefix
	const withImages = `/images/${withoutLeadingSlash}`;
	if (mapping[withImages]) {
		return mapping[withImages];
	}

	// Not found
	return undefined;
}

/**
 * Convert an old image path to markdown image syntax with new URL
 *
 * @param oldPath - The old image path
 * @param mapping - The image URL mapping object
 * @param altText - Alternative text for the image
 * @returns Markdown image syntax or undefined if not found
 */
function convertImageToMarkdown(
	oldPath: string,
	mapping: ImageUrlMapping | undefined,
	altText: string
): string | undefined {
	if (!mapping) {
		return undefined;
	}

	const newUrl = lookupImageUrl(oldPath, mapping);
	if (newUrl) {
		return `![${altText}](${newUrl})`;
	}

	return undefined;
}

// ============================================================================
// RESULT TYPES
// ============================================================================

/**
 * Result of a question transformation
 */
export interface TransformResult {
	/** Whether transformation succeeded */
	success: boolean;

	/** Transformed template if successful (without id/audit fields - will be generated by database) */
	template?: Omit<QuestionTemplate, 'id' | 'created_at' | 'updated_at' | 'created_by'>;

	/** List of warnings about items needing review */
	warnings?: string[];

	/** List of errors that prevented transformation */
	errors?: string[];

	/** Statistics about the transformation */
	stats?: TransformStats;
}

/**
 * Statistics about a transformation
 */
export interface TransformStats {
	/** Number of variations created */
	variations: number;

	/** Number of variables converted */
	variables: number;

	/** Number of syntax conversions performed */
	syntaxConversions: number;

	/** Number of validation options mapped */
	optionsMapped: number;

	/** Number of display options mapped to defaultDisplayOptions */
	displayOptionsMapped: number;

	/** Number of correction syntax conversions (placeholders + conditionals) */
	correctionConversions: number;

	/** Question type detected */
	detectedType: string;

	/** Whether images were skipped */
	hasImages: boolean;

	/** Whether custom validation was detected */
	hasCustomValidation: boolean;

	/** Number of images converted using the mapping */
	imagesConverted: number;

	/** Number of images that could not be found in mapping */
	imagesMissing: number;

	/** Number of AsciiMath to LaTeX conversions performed */
	asciiMathConverted: number;
}

// ============================================================================
// GRADE MAPPING
// ============================================================================

import type { GradeCode } from '$lib/types/grades';

/**
 * Map old grade format to new unified GradeCode format
 *
 * Old system used 'SPE_1', 'SPE_T', 'STMG'
 * New system uses '1_SPE', 'T_SPE', 'T_STMG'
 */
function mapGrade(oldGrade: OldGrade): GradeCode {
	const gradeMap: Record<OldGrade, GradeCode> = {
		CP: 'CP',
		CE1: 'CE1',
		CE2: 'CE2',
		CM1: 'CM1',
		CM2: 'CM2',
		'6': '6',
		'5': '5',
		'4': '4',
		'3': '3',
		'2': '2',
		// Legacy names mapped to new format
		SPE_1: '1_SPE', // Old 'SPE_1' -> New '1_SPE'
		SPE_T: 'T_SPE', // Old 'SPE_T' -> New 'T_SPE'
		T_EXP: 'T_EXP',
		T_COMP: 'T_COMP',
		STMG: 'T_STMG' // Old 'STMG' -> New 'T_STMG' (assuming Terminale STMG)
	};

	return gradeMap[oldGrade] || 'CM1'; // Default to CM1 if unknown
}

// ============================================================================
// QUESTION TYPE DETECTION
// ============================================================================

/**
 * Detect new question type from old question structure
 */
function detectQuestionType(oldQuestion: QuestionBase): QuestionType {
	// Multiple choice with multiple answers
	if (hasMultipleAnswers(oldQuestion)) {
		return 'multiple_choice';
	}

	// Single choice
	if (hasChoices(oldQuestion)) {
		return 'multiple_choice';
	}

	// Fill in blanks (expressions with ?)
	if (hasFillInBlanks(oldQuestion)) {
		return 'fill_in_blanks';
	}

	// Decimal result type
	if (oldQuestion['result-type'] === 'decimal') {
		return 'numerical_decimal';
	}

	// Has custom answer fields - usually means specific format required
	if (hasAnswerFields(oldQuestion)) {
		// Check if answer field suggests algebraic transformation
		const answerField = oldQuestion.answerFields?.[0] || '';
		if (answerField.includes('factoriser') || answerField.includes('développer')) {
			return 'algebraic_transform';
		}
		return 'numerical_exact';
	}

	// Default to numerical exact
	return 'numerical_exact';
}

// ============================================================================
// VARIABLE CONVERSION
// ============================================================================

/**
 * Convert a 1-based number to a letter name (Excel column style)
 * 1→a, 2→b, ..., 26→z, 27→aa, 28→ab, etc.
 */
export function numberToLetterName(num: number): string {
	let result = '';
	let n = num;
	while (n > 0) {
		n--; // Adjust for 0-based indexing
		result = String.fromCharCode(97 + (n % 26)) + result;
		n = Math.floor(n / 26);
	}
	return result;
}

/**
 * Convert old variable definitions to new format
 */
function convertVariables(
	oldVars: Variables | undefined,
	warnings: string[]
): QuestionVariable[] | undefined {
	if (!oldVars) return undefined;

	const variables: QuestionVariable[] = [];

	for (const [varName, expression] of Object.entries(oldVars)) {
		// Remove & prefix from variable name and convert numeric to letter
		const rawName = varName.substring(1);
		const name = /^\d+$/.test(rawName) ? numberToLetterName(parseInt(rawName, 10)) : rawName;

		// Convert TinyCAS syntax to new syntax
		const conversionResult = convertTinyCASToNew(expression);

		if (!conversionResult.success) {
			warnings.push(
				`Failed to convert variable ${varName}: ${conversionResult.errors?.join(', ')}`
			);
			// Use original expression as fallback
			variables.push({
				name,
				expression
			});
		} else {
			if (conversionResult.warnings) {
				warnings.push(...conversionResult.warnings.map((w) => `Variable ${varName}: ${w}`));
			}

			// Convert AsciiMath to LaTeX
			const afterTinyCAS = conversionResult.converted || expression;
			const latexResult = convertAsciiMathToLatexSafe(afterTinyCAS);

			variables.push({
				name,
				expression: latexResult.converted
			});
		}
	}

	return variables.length > 0 ? variables : undefined;
}

// ============================================================================
// STATEMENT CONVERSION
// ============================================================================

/**
 * Result of statement conversion including extracted expression variable
 */
interface StatementResult {
	/** The converted statement with expression reference */
	statement: TemplateMarkdown;
	/** The extracted expression as a variable (if expression was provided) */
	expressionVariable?: QuestionVariable;
}

/**
 * Convert statement and expression to TemplateMarkdown string.
 * Expression is extracted as a separate variable and referenced in the statement.
 *
 * @param enonce - The question text (enounce)
 * @param expression - The mathematical expression (will become a variable)
 * @param expressionIndex - Index for naming the expression variable (expression1, expression2...)
 * @param images - Array of image paths for this variation
 * @param imageMapping - Mapping from old paths to new URLs
 * @param warnings - Array to collect warnings
 * @param stats - Stats object to track image conversions
 * @returns StatementResult with statement and optional expression variable
 */
function convertStatement(
	enonce: string | undefined,
	expression: string | undefined,
	expressionIndex: number,
	images: string[] | undefined,
	imageMapping: ImageUrlMapping | undefined,
	warnings: string[],
	stats: TransformStats
): StatementResult {
	const parts: string[] = [];
	let expressionVariable: QuestionVariable | undefined;

	// Process enonce (statement text)
	if (enonce) {
		const conversionResult = convertTinyCASToNew(enonce);

		if (!conversionResult.success) {
			warnings.push(`Failed to convert statement: ${conversionResult.errors?.join(', ')}`);
			parts.push(enonce);
		} else {
			if (conversionResult.warnings) {
				warnings.push(...conversionResult.warnings.map((w) => `Statement: ${w}`));
			}
			parts.push(conversionResult.converted || enonce);
		}
	}

	// Process expression - extract as variable and add reference to statement
	if (expression) {
		const conversionResult = convertTinyCASToNew(expression);
		const varName = `expression${expressionIndex}`;

		if (!conversionResult.success) {
			warnings.push(`Failed to convert expression: ${conversionResult.errors?.join(', ')}`);
			// Still create variable with original expression
			expressionVariable = {
				name: varName,
				expression: expression
			};
		} else {
			if (conversionResult.warnings) {
				warnings.push(...conversionResult.warnings.map((w) => `Expression: ${w}`));
			}
			// Convert AsciiMath to LaTeX
			const afterTinyCAS = conversionResult.converted || expression;
			const latexResult = convertAsciiMathToLatexSafe(afterTinyCAS);
			stats.asciiMathConverted++;

			expressionVariable = {
				name: varName,
				expression: latexResult.converted
			};
		}

		// Add reference to statement - check for existing $$ delimiters in the expression
		const exprContent = expressionVariable.expression;
		const hasDisplayDelimiters = exprContent.includes('$$');

		if (hasDisplayDelimiters) {
			// Expression already has $$ - just reference the variable
			parts.push('{{' + varName + '}}');
		} else {
			// Wrap reference in $$ for display math
			parts.push('$${{' + varName + '}}$$');
		}
	}

	// Process images
	if (images && images.length > 0) {
		for (let i = 0; i < images.length; i++) {
			const imagePath = images[i];
			const imageMarkdown = convertImageToMarkdown(
				imagePath,
				imageMapping,
				`Question image ${i + 1}`
			);

			if (imageMarkdown) {
				parts.push(imageMarkdown);
				stats.imagesConverted++;
			} else {
				// Image not found in mapping
				stats.imagesMissing++;
				if (imageMapping) {
					warnings.push(`Image not found in mapping: ${imagePath}`);
				}
				// Include original path as fallback
				parts.push(`![Question image ${i + 1}](${imagePath})`);
			}
		}
	}

	// Fallback if nothing was provided
	if (parts.length === 0) {
		warnings.push('No statement or expression provided');
		return {
			statement: templateMarkdown('Question content missing'),
			expressionVariable: undefined
		};
	}

	// Join parts with double newline (paragraph break)
	return {
		statement: templateMarkdown(parts.join('\n\n')),
		expressionVariable
	};
}

// ============================================================================
// SOLUTION CONVERSION
// ============================================================================

/**
 * Convert solution(s) to new format.
 * Note: This converts the expected solution (from solutionss), not student answers.
 */
function convertSolution(
	solutions: (string | number)[] | undefined,
	questionType: QuestionType,
	warnings: string[]
): string | string[] {
	if (!solutions || solutions.length === 0) {
		warnings.push('No solutions provided');
		return questionType === 'multiple_choice' ? ['0'] : '';
	}

	// For multiple choice, solutions are indices
	if (questionType === 'multiple_choice') {
		return solutions.map((s) => String(s));
	}

	// For other types, convert the expression syntax
	const solutionValue = String(solutions[0]);
	const conversionResult = convertTinyCASToNew(solutionValue);

	if (!conversionResult.success) {
		warnings.push(`Failed to convert solution: ${conversionResult.errors?.join(', ')}`);
		return solutionValue;
	}

	if (conversionResult.warnings) {
		warnings.push(...conversionResult.warnings.map((w) => `Solution: ${w}`));
	}

	// Convert AsciiMath to LaTeX
	const afterTinyCAS = conversionResult.converted || solutionValue;
	const latexResult = convertAsciiMathToLatexSafe(afterTinyCAS);

	return latexResult.converted;
}

// ============================================================================
// CHOICES CONVERSION
// ============================================================================

/**
 * Convert choices for multiple choice questions
 *
 * @param choices - Array of choice objects from old question
 * @param correctIndices - Indices of correct choices
 * @param imageMapping - Mapping from old image paths to new URLs
 * @param warnings - Array to collect warnings
 * @param stats - Stats object to track image conversions
 * @returns Array of converted choices
 */
function convertChoices(
	choices: Choice[] | undefined,
	imageMapping: ImageUrlMapping | undefined,
	warnings: string[],
	stats: TransformStats
): QuestionVariation['choices'] {
	if (!choices || choices.length === 0) {
		return undefined;
	}

	// Note: isCorrect is no longer set here - the correct choice is determined
	// at runtime by evaluating the solution (which contains the correct index)
	return choices.map((choice, index) => {
		let content: TemplateMarkdown;

		if (choice.text) {
			const conversionResult = convertTinyCASToNew(choice.text);
			if (!conversionResult.success && conversionResult.errors) {
				warnings.push(`Choice ${index}: ${conversionResult.errors.join(', ')}`);
			}
			content = templateMarkdown(conversionResult.converted || choice.text);
		} else if (choice.image) {
			// Convert image using mapping if available
			const imageMarkdown = convertImageToMarkdown(
				choice.image,
				imageMapping,
				`Choice ${index + 1}`
			);

			if (imageMarkdown) {
				content = templateMarkdown(imageMarkdown);
				stats.imagesConverted++;
			} else {
				// Fallback to original path
				stats.imagesMissing++;
				if (imageMapping) {
					warnings.push(`Choice image not found in mapping: ${choice.image}`);
				}
				content = templateMarkdown(`![Choice ${index + 1}](${choice.image})`);
			}
		} else {
			content = templateMarkdown(`Choice ${index + 1}`);
		}

		return {
			content
		};
	});
}

// ============================================================================
// CORRECTION CONVERSION
// ============================================================================

/**
 * Apply all legacy syntax conversions to a text string
 *
 * Conversion order:
 * 1. TinyCAS syntax (variable references, evaluations)
 * 2. Placeholder syntax (&sol, &answer, &expression, etc.)
 * 3. Conditional syntax (@@condition ?? text@@)
 *
 * @param text - The text to convert
 * @param warnings - Array to collect conversion warnings
 * @returns The converted text with all legacy syntax transformed to new format
 */
function convertLegacySyntax(text: string, warnings: string[]): string {
	if (!text) return text;

	// Step 1: Convert TinyCAS syntax
	const casResult = convertTinyCASToNew(text);
	let converted = text;

	if (!casResult.success) {
		warnings.push(`TinyCAS conversion warning: ${casResult.errors?.join(', ')}`);
	} else {
		converted = casResult.converted || text;
		if (casResult.warnings) {
			warnings.push(...casResult.warnings.map((w) => `TinyCAS: ${w}`));
		}
	}

	// Step 2: Convert placeholder syntax (&sol, &answer, etc.)
	const placeholderResult = convertPlaceholders(converted);
	converted = placeholderResult.converted;

	// Step 3: Convert conditional syntax (@@cond ?? text@@)
	const conditionalResult = convertConditionals(converted);
	converted = conditionalResult.converted;

	return converted;
}

/**
 * Transform old correction fields to unified QuestionCorrection
 *
 * Maps:
 * - correctionFormats.correct -> feedback.correct
 * - correctionFormats.uncorrect -> feedback.incorrect
 * - correctionDetailss -> steps
 *
 * @param correctionDetails - Old correction details array (step-by-step explanations)
 * @param correctionFormat - Old correction format (feedback messages)
 * @param warnings - Array to collect conversion warnings
 * @param stats - Statistics object to track conversions
 * @returns QuestionCorrection object or undefined if nothing to convert
 */
function transformCorrection(
	correctionDetails: CorrectionDetail[] | undefined,
	correctionFormat: CorrectionFormat | undefined,
	warnings: string[],
	stats: TransformStats
): QuestionCorrection | undefined {
	const correction: QuestionCorrection = {};
	let conversionCount = 0;

	// Transform feedback from correctionFormats
	if (correctionFormat) {
		correction.feedback = {};

		if (correctionFormat.correct?.length) {
			// Convert first correct message with all syntax converters
			const converted = convertLegacySyntax(correctionFormat.correct[0], warnings);
			correction.feedback.correct = templateMarkdown(converted);
			conversionCount++;
		}

		if (correctionFormat.uncorrect?.length) {
			// Convert first incorrect message with all syntax converters
			const converted = convertLegacySyntax(correctionFormat.uncorrect[0], warnings);
			correction.feedback.incorrect = templateMarkdown(converted);
			conversionCount++;
		}

		// Remove feedback object if empty
		if (!correction.feedback.correct && !correction.feedback.incorrect) {
			delete correction.feedback;
		}
	}

	// Transform steps from correctionDetailss
	if (correctionDetails?.length) {
		correction.steps = correctionDetails.map((detail) => {
			const converted = convertLegacySyntax(detail.text, warnings);
			conversionCount++;
			return templateMarkdown(converted);
		});
	}

	// Track conversion stats
	stats.correctionConversions += conversionCount;

	// Return undefined if nothing was converted
	if (!correction.feedback && !correction.steps) {
		return undefined;
	}

	return correction;
}

/**
 * Convert correction details to TemplateMarkdown string
 *
 * @deprecated Use transformCorrection instead for full QuestionCorrection support
 */
function _convertCorrection(
	correctionDetails: CorrectionDetail[] | undefined,
	warnings: string[]
): TemplateMarkdown | undefined {
	if (!correctionDetails || correctionDetails.length === 0) {
		return undefined;
	}

	const parts: string[] = [];

	for (const detail of correctionDetails) {
		const conversionResult = convertTinyCASToNew(detail.text);

		if (!conversionResult.success) {
			warnings.push(`Failed to convert correction: ${conversionResult.errors?.join(', ')}`);
			parts.push(detail.text);
		} else {
			parts.push(conversionResult.converted || detail.text);
		}
	}

	// Join correction parts with double newline
	return templateMarkdown(parts.join('\n\n'));
}

// ============================================================================
// OPTIONS CONVERSION
// ============================================================================

/**
 * Convert old validation options to new format
 *
 * Maps old TinyMath options to new ConstraintOptions structure:
 * - require-* options → constraint: 'strict'
 * - no-penalty-for-* options → constraint: 'off'
 * - Display/generation options → defaultDisplayOptions
 * - Display options (enounce-no-spaces) → silently ignored
 */
function convertOptions(
	oldOptions: string[] | undefined,
	warnings: string[]
): { options?: QuestionTemplate['options']; defaultDisplayOptions?: DisplayOptions } {
	if (!oldOptions || oldOptions.length === 0) {
		return {};
	}

	const options: QuestionTemplate['options'] = {};
	const constraints: ConstraintOptions = {};
	const displayOptions: DisplayOptions = {};
	// Note: mappedCount tracked for potential debugging but not used in return
	let _mappedCount = 0;

	for (const option of oldOptions) {
		switch (option) {
			// ================================================================
			// CONSTRAINT OPTIONS - Spaces
			// ================================================================
			case 'require-correct-spaces':
				constraints.spaces = 'strict';
				_mappedCount++;
				break;
			case 'no-penalty-for-incorrect-spaces':
				constraints.spaces = 'off';
				_mappedCount++;
				break;

			// ================================================================
			// CONSTRAINT OPTIONS - Products
			// ================================================================
			case 'require-implicit-products':
				constraints.products = 'strict';
				_mappedCount++;
				break;
			case 'no-penalty-for-explicit-products':
				constraints.products = 'off';
				_mappedCount++;
				break;

			// ================================================================
			// CONSTRAINT OPTIONS - Brackets
			// ================================================================
			case 'require-no-extraneous-brackets':
				constraints.brackets = 'strict';
				_mappedCount++;
				break;
			case 'no-penalty-for-extraneous-brackets':
				constraints.brackets = 'off';
				_mappedCount++;
				break;
			case 'no-penalty-for-extraneous-brackets-in-first-negative-term':
				constraints.brackets = 'off';
				constraints.allowBracketsInFirstNegativeTerm = true;
				_mappedCount++;
				break;

			// ================================================================
			// CONSTRAINT OPTIONS - Zeros
			// ================================================================
			case 'require-no-extraneous-zeros':
				constraints.zeros = 'strict';
				_mappedCount++;
				break;
			case 'no-penalty-for-extraneous-zeros':
				constraints.zeros = 'off';
				_mappedCount++;
				break;

			// ================================================================
			// CONSTRAINT OPTIONS - Null terms (CE pattern matching)
			// ================================================================
			case 'require-no-null-terms':
				constraints.nullTerms = 'strict';
				_mappedCount++;
				break;
			case 'no-penalty-for-null-terms':
				constraints.nullTerms = 'off';
				_mappedCount++;
				break;

			// ================================================================
			// CONSTRAINT OPTIONS - Factor one (CE pattern matching)
			// ================================================================
			case 'require-no-factor-one':
				constraints.factorOne = 'strict';
				_mappedCount++;
				break;
			case 'no-penalty-for-factor-one':
				constraints.factorOne = 'off';
				_mappedCount++;
				break;

			// ================================================================
			// CONSTRAINT OPTIONS - Factor zero (CE pattern matching)
			// ================================================================
			case 'require-no-factor-zero':
				constraints.factorZero = 'strict';
				_mappedCount++;
				break;
			case 'no-penalty-for-factor-zero':
				constraints.factorZero = 'off';
				_mappedCount++;
				break;

			// ================================================================
			// CONSTRAINT OPTIONS - Signs (CE pattern matching)
			// ================================================================
			case 'require-no-extraneous-signs':
				constraints.signs = 'strict';
				_mappedCount++;
				break;
			case 'no-penalty-for-extraneous-signs':
				constraints.signs = 'off';
				_mappedCount++;
				break;

			// ================================================================
			// FRACTION OPTIONS → constraints.reducedFractions
			// ================================================================
			case 'require-reduced-fractions':
				// Require fractions to be reduced to lowest terms
				constraints.reducedFractions = 'strict';
				_mappedCount++;
				break;
			case 'no-penalty-for-non-reduced-fractions':
				// Don't penalize non-reduced fractions
				constraints.reducedFractions = 'off';
				_mappedCount++;
				break;

			// ================================================================
			// SHUFFLE CHOICES - Implemented
			// ================================================================
			case 'no-shuffle-choices':
				options.shuffleChoices = false;
				_mappedCount++;
				break;

			// ================================================================
			// UNIT OPTIONS - Implemented
			// ================================================================
			case 'require-specific-unit':
				if (!options.unitOptions) options.unitOptions = {};
				options.unitOptions.requireExactUnit = true;
				_mappedCount++;
				break;
			case 'no-penalty-for-not-respected-unit':
				if (!options.unitOptions) options.unitOptions = {};
				options.unitOptions.requireExactUnit = false;
				_mappedCount++;
				break;

			// ================================================================
			// NOT IMPLEMENTED - VALIDATION OPTIONS (generate warnings)
			// ================================================================
			case 'solutions-order-not-important':
				// TODO: Allows multiple answers in any order (not about form)
				warnings.push(`TODO: ${option} - answer order validation not yet implemented`);
				break;
			case 'disallow-terms-permutation':
			case 'disallow-factors-permutation':
			case 'disallow-terms-and-factors-permutation':
			case 'penalty-for-terms-permutation':
			case 'penalty-for-factors-permutation':
			case 'penalty-for-terms-and-factors-permutation':
				// TODO: Validate that factors/terms are in specific order
				warnings.push(`TODO: ${option} - permutation validation not yet implemented`);
				break;
			case 'one-single-form-solution':
				// TODO: Requires exact form match (strictlyEquals)
				warnings.push(`TODO: ${option} - strict form validation not yet implemented`);
				break;

			// ================================================================
			// DISPLAY GENERATION OPTIONS → defaultDisplayOptions
			// ================================================================
			case 'shuffle-terms':
				displayOptions.shuffleTerms = true;
				_mappedCount++;
				break;
			case 'shuffle-factors':
				displayOptions.shuffleFactors = true;
				_mappedCount++;
				break;
			case 'shuffle-terms-and-factors':
				displayOptions.shuffleTermsAndFactors = true;
				_mappedCount++;
				break;
			case 'shallow-shuffle-terms':
				displayOptions.shallowShuffleTerms = true;
				_mappedCount++;
				break;
			case 'shallow-shuffle-factors':
				displayOptions.shallowShuffleFactors = true;
				_mappedCount++;
				break;
			case 'remove-null-terms':
				displayOptions.removeNullTerms = true;
				_mappedCount++;
				break;

			// ================================================================
			// NOT IMPLEMENTED - GENERATION OPTIONS (generate warnings)
			// ================================================================
			case 'exhaust':
				// TODO: Generate all possible variations without repetition
				warnings.push(`TODO: ${option} - exhaustive generation not yet implemented`);
				break;

			// ================================================================
			// LATEX FORMATTING OPTIONS → defaultDisplayOptions
			// ================================================================
			case 'exp-no-spaces':
				displayOptions.addSpaces = false;
				_mappedCount++;
				break;
			case 'exp-allow-unecessary-zeros':
				displayOptions.keepUnnecessaryZeros = true;
				_mappedCount++;
				break;

			// ================================================================
			// DISPLAY OPTIONS - Silently ignored (cosmetic only)
			// ================================================================
			case 'enounce-no-spaces':
			case 'exp-remove-unecessary-brackets':
				// Display formatting options - cosmetic only, safe to ignore
				_mappedCount++;
				break;

			// ================================================================
			// LEGACY OPTIONS - Silently ignored (not needed)
			// ================================================================
			case 'allow-same-expression':
			case 'allow-same-enounce':
			case 'multiples':
				// Legacy generation uniqueness options - not needed in new system
				_mappedCount++;
				break;

			default:
				warnings.push(`Unknown option: ${option} - needs manual review`);
		}
	}

	// Add constraints to options if any were set
	if (Object.keys(constraints).length > 0) {
		options.constraints = constraints;
	}

	// Build result object
	const hasOptions = Object.keys(options).length > 0;
	const hasDisplayOptions = Object.keys(displayOptions).length > 0;

	return {
		options: hasOptions ? options : undefined,
		defaultDisplayOptions: hasDisplayOptions ? displayOptions : undefined
	};
}

// ============================================================================
// TESTANSWERS CONVERSION
// ============================================================================

/**
 * Convert old testAnswerss patterns to typed ValidationRule objects
 *
 * Handles these patterns from old questions:
 * - `&answer>0` → PredicateRule or RangeRule
 * - `&answer!=0 && &answer!=1` → CustomExpressionRule (exclude values)
 * - `mod(&1;&answer)=0` → DivisorRule
 * - Complex boolean expressions → CustomExpressionRule
 *
 * @param testAnswers - Array of test answer expressions for a variation
 * @param warnings - Array to collect warnings
 * @returns Array of ValidationRule objects, or undefined if no valid rules
 */
function convertTestAnswers(
	testAnswers: string[] | undefined,
	warnings: string[]
): ValidationRule[] | undefined {
	if (!testAnswers || testAnswers.length === 0) {
		return undefined;
	}

	const rules: ValidationRule[] = [];

	for (const expr of testAnswers) {
		const rule = parseTestAnswerExpression(expr, warnings);
		if (rule) {
			rules.push(rule);
		}
	}

	return rules.length > 0 ? rules : undefined;
}

/**
 * Parse a single testAnswer expression and convert to ValidationRule
 *
 * @param expression - The test answer expression
 * @param warnings - Array to collect warnings
 * @returns A ValidationRule or undefined if parsing failed
 */
function parseTestAnswerExpression(
	expression: string,
	warnings: string[]
): ValidationRule | undefined {
	// Normalize the expression
	const normalized = expression.trim();

	// Pattern: &answer>0 (positive check)
	if (/^&answer\s*>\s*0$/i.test(normalized)) {
		return {
			type: 'predicate',
			predicate: 'isPositive'
		};
	}

	// Pattern: &answer>=0 (non-negative)
	if (/^&answer\s*>=\s*0$/i.test(normalized)) {
		return {
			type: 'range',
			min: '0',
			max: 'Infinity',
			inclusive: true
		};
	}

	// Pattern: &answer<0 (negative check)
	if (/^&answer\s*<\s*0$/i.test(normalized)) {
		return {
			type: 'predicate',
			predicate: 'isNegative'
		};
	}

	// Pattern: mod(&var;&answer)=0 (divisor check)
	// e.g., mod(&1;&answer)=0 → answer divides &1
	const divisorMatch = normalized.match(/mod\s*\(\s*(&\d+(?:\*&\d+)*)\s*;\s*&answer\s*\)\s*=\s*0/i);
	if (divisorMatch) {
		const dividend = convertVariableReference(divisorMatch[1]);
		return {
			type: 'divisor',
			dividend
		};
	}

	// Pattern: &answer > min && &answer < max (range check)
	const rangeMatch = normalized.match(
		/&answer\s*([><]=?)\s*(\d+|&\d+)\s*&&\s*&answer\s*([><]=?)\s*(\d+|&\d+)/i
	);
	if (rangeMatch) {
		const [, op1, val1, op2, val2] = rangeMatch;
		let min = '',
			max = '';
		let inclusive = false;

		// Figure out which is min and which is max
		if (op1.includes('>') && op2.includes('<')) {
			min = convertVariableReference(val1);
			max = convertVariableReference(val2);
			inclusive = op1.includes('=') || op2.includes('=');
		} else if (op1.includes('<') && op2.includes('>')) {
			min = convertVariableReference(val2);
			max = convertVariableReference(val1);
			inclusive = op1.includes('=') || op2.includes('=');
		}

		if (min && max) {
			return {
				type: 'range',
				min,
				max,
				inclusive
			};
		}
	}

	// For complex expressions, use CustomExpressionRule as fallback
	// Convert old syntax to new syntax first
	const convertedExpr = convertTestAnswerSyntax(normalized);

	warnings.push(`testAnswer expression converted to custom rule: ${expression}`);

	return {
		type: 'custom',
		expression: convertedExpr,
		description: `Legacy testAnswer: ${expression}`
	};
}

/**
 * Convert old testAnswer syntax to new format
 *
 * - &answer → answer
 * - &N → {{varN}} (variable reference)
 * - mod(a;b) → (a % b)
 * - != → !== (for consistency)
 *
 * @param expression - Old testAnswer expression
 * @returns Converted expression
 */
function convertTestAnswerSyntax(expression: string): string {
	let result = expression;

	// Convert &answer to 'answer'
	result = result.replace(/&answer/gi, 'answer');

	// Convert &N*&M to {{varN}} * {{varM}}
	result = result.replace(/&(\d+)\s*\*\s*&(\d+)/g, '{{var$1}} * {{var$2}}');

	// Convert &N to {{varN}}
	result = result.replace(/&(\d+)/g, '{{var$1}}');

	// Convert mod(a;b) to (a % b === 0 ? true : false) or keep as mod function call
	result = result.replace(/mod\s*\(\s*([^;]+)\s*;\s*([^)]+)\s*\)\s*=\s*0/gi, '($1 % $2 === 0)');

	// Convert != to !== for strict comparison
	result = result.replace(/!=/g, '!==');

	return result;
}

/**
 * Convert old variable reference (&1, &2, etc.) to new template syntax
 *
 * @param varRef - Old variable reference like "&1" or "&1*&2"
 * @returns New template syntax like "{{var1}}" or "{{var1}} * {{var2}}"
 */
function convertVariableReference(varRef: string): string {
	// Handle compound expressions like &1*&2
	if (varRef.includes('*')) {
		return varRef.replace(/&(\d+)/g, '{{var$1}}');
	}

	// Simple variable reference
	const match = varRef.match(/^&(\d+)$/);
	if (match) {
		return `{{var${match[1]}}}`;
	}

	// Numeric literal
	if (/^\d+$/.test(varRef)) {
		return varRef;
	}

	// Unknown format, return as-is
	return varRef;
}

// ============================================================================
// CATEGORY ASSIGNMENT
// ============================================================================

/**
 * Assign category based on old question structure
 */
function assignCategory(oldQuestion: QuestionBase): {
	theme: string;
	domain: string;
	subdomain?: string;
	level: number;
} {
	// For Phase 1, use simple defaults based on grade and description
	// Later phases can implement more sophisticated extraction

	const description = oldQuestion.description.toLowerCase();

	// Try to detect theme from description
	let theme = 'Nombres';
	let domain = 'Arithmétique';
	let subdomain: string | undefined;

	if (description.includes('fraction')) {
		theme = 'Nombres';
		domain = 'Fractions';
	} else if (description.includes('équation') || description.includes('equation')) {
		theme = 'Algèbre';
		domain = 'Équations';
	} else if (
		description.includes('géométr') ||
		description.includes('angle') ||
		description.includes('triangle')
	) {
		theme = 'Géométrie';
		domain = 'Figures planes';
	} else if (description.includes('fonction')) {
		theme = 'Fonctions';
		domain = 'Généralités';
	} else if (description.includes('probabilité') || description.includes('statistique')) {
		theme = 'Probabilités et statistiques';
		domain = 'Probabilités';
	} else if (description.includes('addition') || description.includes('soustraction')) {
		theme = 'Nombres';
		domain = 'Opérations';
		subdomain = description.includes('addition') ? 'Addition' : 'Soustraction';
	} else if (description.includes('multiplication') || description.includes('division')) {
		theme = 'Nombres';
		domain = 'Opérations';
		subdomain = description.includes('multiplication') ? 'Multiplication' : 'Division';
	}

	// Assign level based on grade
	const gradeLevel = oldQuestion.grade;
	let level = 1;

	if (['CP', 'CE1'].includes(gradeLevel)) {
		level = 1;
	} else if (['CE2', 'CM1', 'CM2'].includes(gradeLevel)) {
		level = 2;
	} else if (['6', '5'].includes(gradeLevel)) {
		level = 3;
	} else if (['4', '3'].includes(gradeLevel)) {
		level = 4;
	} else if (['2', 'SPE_1', 'SPE_T'].includes(gradeLevel)) {
		level = 5;
	} else {
		level = 6;
	}

	return { theme, domain, subdomain, level };
}

// ============================================================================
// SHARED FIELDS DETECTION
// ============================================================================

/**
 * Result of shared fields detection
 */
interface SharedFieldsResult {
	/** Shared defaults that apply to all variations */
	shared: SharedVariationDefaults;
	/** Per-variation data that differs between variations */
	perVariation: Partial<QuestionVariation>[];
}

/**
 * Detect which fields are shared across all variations.
 *
 * In TinyMath, an array with 1 element for N variations means the field is shared.
 * For example:
 * - `enounces.length === 1` with `variationCount > 1` → shared statement
 * - `variabless.length === 1` with `variationCount > 1` → shared variables
 * - `solutionss.length === 1` with `variationCount > 1` → shared solution
 * - etc.
 *
 * @param oldQuestion - The old TinyMath question
 * @param variationCount - Number of variations detected
 * @param questionType - The detected question type
 * @param imageMapping - Optional mapping for image URLs
 * @param warnings - Array to collect warnings
 * @param stats - Stats object to track conversions
 * @returns Object containing shared defaults and per-variation data
 */
function detectSharedFields(
	oldQuestion: QuestionBase,
	variationCount: number,
	questionType: QuestionType,
	imageMapping: ImageUrlMapping | undefined,
	warnings: string[],
	stats: TransformStats
): SharedFieldsResult {
	const shared: SharedVariationDefaults = {};
	const perVariation: Partial<QuestionVariation>[] = Array.from(
		{ length: variationCount },
		() => ({})
	);

	// Get images array (shared across all variations in old format)
	const images = oldQuestion.images;

	// ---- Detect enounces sharing (→ statement) ----
	const enounces = oldQuestion.enounces || [];
	const expressions = oldQuestion.expressions || [];

	// Statement is shared if enounce is shared (expression variables are always per-variation)
	const enounceIsShared = enounces.length === 1 && variationCount > 1;
	const expressionIsShared =
		(expressions.length === 0 || expressions.length === 1) && variationCount > 1;
	const statementIsShared =
		(enounceIsShared || enounces.length === 0) && (expressionIsShared || expressions.length === 0);

	// Collect expression variables to add to perVariation later (after regular variables)
	const expressionVariables: (QuestionVariable | undefined)[] = [];

	if (statementIsShared) {
		// Shared enounce AND shared/no expression - generate statement once
		const enonce = enounces[0];
		const expression = expressions[0];
		const result = convertStatement(
			enonce,
			expression,
			1, // Always expression1 when shared
			images,
			imageMapping,
			warnings,
			stats
		);
		shared.statement = result.statement;
		// All variations share the same statement and expression variable
		for (let i = 0; i < variationCount; i++) {
			perVariation[i].statement = result.statement;
			expressionVariables.push(result.expressionVariable);
		}
	} else {
		// Per-variation statements or expressions
		for (let i = 0; i < variationCount; i++) {
			const enonce = enounces[i] || enounces[0];
			const expression = expressions[i] || expressions[0];
			const result = convertStatement(
				enonce,
				expression,
				i + 1, // expressionIndex varies per variation
				images,
				imageMapping,
				warnings,
				stats
			);
			perVariation[i].statement = result.statement;
			expressionVariables.push(result.expressionVariable);
		}
	}

	// ---- Detect variabless sharing (→ variables) ----
	const variabless = oldQuestion.variabless || [];
	const variablesIsShared = variabless.length === 1 && variationCount > 1;

	if (variablesIsShared) {
		const convertedVars = convertVariables(variabless[0], warnings);
		if (convertedVars && convertedVars.length > 0) {
			shared.variables = convertedVars;
			stats.variables += convertedVars.length;
		}
	} else {
		for (let i = 0; i < variationCount; i++) {
			const variables = variabless[i] || variabless[0];
			const convertedVars = convertVariables(variables, warnings);
			if (convertedVars && convertedVars.length > 0) {
				perVariation[i].variables = convertedVars;
				stats.variables += convertedVars.length;
			}
		}
	}

	// ---- Add expression variables AFTER regular variables (for correct resolution order) ----
	for (let i = 0; i < variationCount; i++) {
		const exprVar = expressionVariables[i];
		if (exprVar) {
			if (!perVariation[i].variables) {
				perVariation[i].variables = [];
			}
			perVariation[i].variables!.push(exprVar);
		}
	}

	// ---- Detect solutionss sharing (→ solution) ----
	const solutionss = oldQuestion.solutionss || [];
	const solutionIsShared = solutionss.length === 1 && variationCount > 1;

	if (solutionss.length > 0) {
		// Case: solutionss exists
		if (solutionIsShared) {
			shared.solution = convertSolution(solutionss[0], questionType, warnings);
		} else {
			for (let i = 0; i < variationCount; i++) {
				const solutions = solutionss[i] || solutionss[0];
				perVariation[i].solution = convertSolution(solutions, questionType, warnings);
			}
		}
	} else if (expressions.length > 0) {
		// Fallback: no solutionss but expressions exist
		// The solution is the evaluated expression value (use eval to compute the result)
		const expressionIsSharedForSolution = expressions.length === 1 && variationCount > 1;

		if (expressionIsSharedForSolution) {
			shared.solution = '{{eval:expression1}}';
		} else {
			for (let i = 0; i < variationCount; i++) {
				perVariation[i].solution = `{{eval:expression${i + 1}}}`;
			}
		}
	}

	// ---- Detect correction sharing (correctionDetailss + correctionFormats) ----
	const correctionDetailss = oldQuestion.correctionDetailss || [];
	const correctionFormats = oldQuestion.correctionFormats || [];

	// Correction is shared if both arrays have 0 or 1 elements for multiple variations
	const detailsIsShared = correctionDetailss.length <= 1 && variationCount > 1;
	const formatsIsShared = correctionFormats.length <= 1 && variationCount > 1;
	const correctionIsShared = detailsIsShared && formatsIsShared;

	if (correctionIsShared && (correctionDetailss.length > 0 || correctionFormats.length > 0)) {
		const questionCorrection = transformCorrection(
			correctionDetailss[0],
			correctionFormats[0],
			warnings,
			stats
		);
		if (questionCorrection) {
			shared.correction = questionCorrection;
		}
	} else if (correctionDetailss.length > 1 || correctionFormats.length > 1) {
		for (let i = 0; i < variationCount; i++) {
			const correctionDetails = correctionDetailss[i] || correctionDetailss[0];
			const correctionFormat = correctionFormats[i] || correctionFormats[0];
			const questionCorrection = transformCorrection(
				correctionDetails,
				correctionFormat,
				warnings,
				stats
			);
			if (questionCorrection) {
				perVariation[i].correction = questionCorrection;
			}
		}
	}

	// ---- Detect choices sharing (for multiple_choice) ----
	const choicess = oldQuestion.choicess || [];
	const choicesIsShared = choicess.length === 1 && variationCount > 1;

	if (questionType === 'multiple_choice' && choicess.length > 0) {
		// For QCM, choices don't have isCorrect - the correct choice is determined
		// at runtime by evaluating the solution (which contains the correct index)
		if (choicesIsShared) {
			shared.choices = convertChoices(choicess[0], imageMapping, warnings, stats);
		} else {
			for (let i = 0; i < variationCount; i++) {
				const choices = choicess[i] || choicess[0];
				perVariation[i].choices = convertChoices(choices, imageMapping, warnings, stats);
			}
		}
	}

	// ---- Detect testAnswerss sharing (→ validationRules) ----
	const testAnswerss = oldQuestion.testAnswerss || [];
	const testAnswersIsShared = testAnswerss.length === 1 && variationCount > 1;

	if (testAnswerss.length > 0) {
		if (testAnswersIsShared) {
			const validationRules = convertTestAnswers(testAnswerss[0], warnings);
			if (validationRules && validationRules.length > 0) {
				shared.validationRules = validationRules;
			}
		} else {
			for (let i = 0; i < variationCount; i++) {
				const testAnswers = testAnswerss[i] || testAnswerss[0];
				const validationRules = convertTestAnswers(testAnswers, warnings);
				if (validationRules && validationRules.length > 0) {
					perVariation[i].validationRules = validationRules;
				}
			}
		}
	}

	return { shared, perVariation };
}

/**
 * Check if shared object has any meaningful content
 */
function hasSharedContent(shared: SharedVariationDefaults): boolean {
	return !!(
		shared.statement ||
		(shared.variables && shared.variables.length > 0) ||
		shared.solution !== undefined ||
		shared.correction ||
		(shared.choices && shared.choices.length > 0) ||
		(shared.validationRules && shared.validationRules.length > 0)
	);
}

// ============================================================================
// VARIATION CREATION
// ============================================================================

/**
 * Create variations from old question structure with shared field detection
 *
 * @param oldQuestion - The old question object
 * @param questionType - Detected question type
 * @param imageMapping - Optional mapping from old image paths to new URLs
 * @param warnings - Array to collect warnings
 * @param stats - Stats object to track conversions
 * @returns Object containing variations and optionally shared defaults
 */
function createVariationsWithShared(
	oldQuestion: QuestionBase,
	questionType: QuestionType,
	imageMapping: ImageUrlMapping | undefined,
	warnings: string[],
	stats: TransformStats
): { variations: QuestionVariation[]; shared?: SharedVariationDefaults } {
	const variationCount = getVariationCount(oldQuestion);
	stats.variations = variationCount;

	// Detect shared fields
	const { shared, perVariation } = detectSharedFields(
		oldQuestion,
		variationCount,
		questionType,
		imageMapping,
		warnings,
		stats
	);

	// Handle fill_in_blanks - blanks are always per-variation
	const expressions = oldQuestion.expressions || [];
	const solutionss = oldQuestion.solutionss || [];

	if (questionType === 'fill_in_blanks') {
		for (let i = 0; i < variationCount; i++) {
			const expression = expressions[i] || expressions[0];
			const solutions = solutionss[i] || solutionss[0];
			if (expression) {
				const blanks = extractBlanks(expression, solutions, warnings);
				if (blanks && blanks.length > 0) {
					perVariation[i].blanks = blanks;
				}
			}
		}
	}

	// Build variations array from per-variation data
	const variations: QuestionVariation[] = perVariation.map((pv, index) => {
		// Start with required fields - use shared fallback or throw error
		const statement = pv.statement || shared.statement;
		const solution = pv.solution ?? shared.solution;

		if (!statement) {
			warnings.push(`Variation ${index}: missing statement`);
		}
		if (solution === undefined) {
			warnings.push(`Variation ${index}: missing solution`);
		}

		const variation: QuestionVariation = {
			statement: statement || templateMarkdown(''),
			solution: solution ?? ''
		};

		// Add optional fields only if they exist and are NOT shared
		if (pv.variables && pv.variables.length > 0) {
			variation.variables = pv.variables;
		}
		if (pv.correction) {
			variation.correction = pv.correction;
		}
		if (pv.choices && pv.choices.length > 0) {
			variation.choices = pv.choices;
		}
		if (pv.validationRules && pv.validationRules.length > 0) {
			variation.validationRules = pv.validationRules;
		}
		if (pv.blanks && pv.blanks.length > 0) {
			variation.blanks = pv.blanks;
		}

		return variation;
	});

	// Return shared only if it has meaningful content
	return {
		variations,
		shared: hasSharedContent(shared) ? shared : undefined
	};
}

/**
 * Extract blank positions and answers from expression with ?
 */
function extractBlanks(
	expression: string,
	solutions: (string | number)[] | undefined,
	warnings: string[]
): QuestionVariation['blanks'] {
	const blanks: NonNullable<QuestionVariation['blanks']> = [];

	// Count ? marks in expression
	const questionMarks = (expression.match(/\?/g) || []).length;

	if (questionMarks === 0) {
		warnings.push('Fill-in-blanks detected but no ? marks found in expression');
		return undefined;
	}

	// Each ? corresponds to a solution
	for (let i = 0; i < questionMarks; i++) {
		const answer = solutions?.[i];
		if (answer !== undefined) {
			const conversionResult = convertTinyCASToNew(String(answer));
			blanks.push({
				position: i,
				expectedAnswer: conversionResult.converted || String(answer)
			});
		} else {
			warnings.push(`Missing solution for blank at position ${i}`);
			blanks.push({
				position: i,
				expectedAnswer: ''
			});
		}
	}

	return blanks.length > 0 ? blanks : undefined;
}

// ============================================================================
// MAIN TRANSFORMER
// ============================================================================

/**
 * Transform a single old question to new format
 *
 * @param oldQuestion - The old TinyMath question object
 * @param questionIndex - Index of this question in the batch
 * @param options - Transformation options
 * @param options.skipImages - If true, skip questions with images
 * @param options.skipCustomValidation - If true, skip questions with testAnswers
 * @param options.imageUrlMapping - Optional mapping from old image paths to new Supabase URLs
 * @returns Transformation result with template, warnings, errors, and stats
 */
export function transformQuestion(
	oldQuestion: QuestionBase,
	questionIndex: number,
	options?: {
		skipImages?: boolean;
		skipCustomValidation?: boolean;
		imageUrlMapping?: ImageUrlMapping;
	}
): TransformResult {
	const warnings: string[] = [];
	const errors: string[] = [];
	const stats: TransformStats = {
		variations: 0,
		variables: 0,
		syntaxConversions: 0,
		optionsMapped: 0,
		displayOptionsMapped: 0,
		correctionConversions: 0,
		detectedType: '',
		hasImages: false,
		hasCustomValidation: false,
		imagesConverted: 0,
		imagesMissing: 0,
		asciiMathConverted: 0
	};

	try {
		// Check for unsupported features
		if (hasImages(oldQuestion)) {
			stats.hasImages = true;
			if (options?.skipImages && !options?.imageUrlMapping) {
				// Only skip if no image mapping provided
				errors.push('Question contains images - skipping for Phase 1');
				return { success: false, errors, stats };
			} else if (!options?.imageUrlMapping) {
				warnings.push('Question contains images - will need manual review');
			}
			// If imageUrlMapping is provided, proceed with conversion
		}

		if (hasTestAnswers(oldQuestion)) {
			stats.hasCustomValidation = true;
			if (options?.skipCustomValidation) {
				errors.push('Question has custom validation - skipping for Phase 1');
				return { success: false, errors, stats };
			} else {
				warnings.push(
					'Question has custom validation (testAnswers) - needs Phase 4 implementation'
				);
			}
		}

		// Detect question type
		const questionType = detectQuestionType(oldQuestion);
		stats.detectedType = questionType;

		// Create variations with shared field detection
		const { variations, shared } = createVariationsWithShared(
			oldQuestion,
			questionType,
			options?.imageUrlMapping,
			warnings,
			stats
		);

		if (variations.length === 0) {
			errors.push('No variations could be created');
			return { success: false, errors, warnings, stats };
		}

		// Convert options
		const { options: convertedOptions, defaultDisplayOptions } = convertOptions(
			oldQuestion.options,
			warnings
		);
		if (convertedOptions) {
			stats.optionsMapped = Object.keys(convertedOptions).length;
		}
		if (defaultDisplayOptions) {
			stats.displayOptionsMapped = Object.keys(defaultDisplayOptions).length;
		}

		// Assign category
		const category = assignCategory(oldQuestion);

		// Determine if algebraic transform type is needed
		let transformType: AlgebraicTransformType | undefined;
		if (questionType === 'algebraic_transform') {
			const description = oldQuestion.description.toLowerCase();
			if (description.includes('factoriser')) {
				transformType = 'factor';
			} else if (description.includes('développer')) {
				transformType = 'expand';
			} else if (description.includes('simplifier')) {
				transformType = 'simplify';
			} else if (description.includes('résoudre') || description.includes('resoudre')) {
				transformType = 'solve';
			}
		}

		// Create template (without id/audit fields - will be auto-generated by database)
		const template: Omit<QuestionTemplate, 'id' | 'created_at' | 'updated_at' | 'created_by'> = {
			type: questionType,
			title: oldQuestion.description,
			description: oldQuestion.subdescription,
			shared, // Include shared defaults when fields are reused across variations
			variations,
			exerciseInstruction: oldQuestion.help,
			options: convertedOptions,
			defaultDisplayOptions,
			grades: [mapGrade(oldQuestion.grade)],
			...category,
			status: 'draft', // Import as draft for review
			multipleAnswers: oldQuestion.multipleAnswers
		};

		// Add optional fields
		if (oldQuestion.defaultDelay > 0) {
			template.delay = oldQuestion.defaultDelay;
		}

		if (transformType) {
			template.transformType = transformType;
		}

		// Add precision for decimal questions
		if (questionType === 'numerical_decimal') {
			template.precision = { type: 'decimal', digits: 2 }; // Default to 2 decimal places
			warnings.push('Decimal precision set to 2 places by default - verify if correct');
		}

		return {
			success: true,
			template,
			warnings: warnings.length > 0 ? warnings : undefined,
			stats
		};
	} catch (error) {
		errors.push(`Unexpected error: ${error instanceof Error ? error.message : String(error)}`);
		return {
			success: false,
			errors,
			warnings: warnings.length > 0 ? warnings : undefined,
			stats
		};
	}
}

// ============================================================================
// BATCH TRANSFORMATION
// ============================================================================

/**
 * Transform multiple questions in batch
 *
 * @param questions - Array of old TinyMath questions to transform
 * @param options - Transformation options
 * @param options.skipImages - If true, skip questions with images (unless mapping provided)
 * @param options.skipCustomValidation - If true, skip questions with testAnswers
 * @param options.imageUrlMapping - Optional mapping from old image paths to new URLs
 * @param options.onProgress - Progress callback
 * @returns Results array and summary statistics
 */
export function transformQuestionBatch(
	questions: QuestionBase[],
	options?: {
		skipImages?: boolean;
		skipCustomValidation?: boolean;
		imageUrlMapping?: ImageUrlMapping;
		onProgress?: (current: number, total: number) => void;
	}
): {
	results: TransformResult[];
	summary: {
		total: number;
		successful: number;
		failed: number;
		warnings: number;
		skippedImages: number;
		skippedCustomValidation: number;
		imagesConverted: number;
		imagesMissing: number;
	};
} {
	const results: TransformResult[] = [];
	const summary = {
		total: questions.length,
		successful: 0,
		failed: 0,
		warnings: 0,
		skippedImages: 0,
		skippedCustomValidation: 0,
		imagesConverted: 0,
		imagesMissing: 0
	};

	for (let i = 0; i < questions.length; i++) {
		// Report progress
		if (options?.onProgress) {
			options.onProgress(i + 1, questions.length);
		}

		// Transform question
		const result = transformQuestion(questions[i], i, {
			skipImages: options?.skipImages,
			skipCustomValidation: options?.skipCustomValidation,
			imageUrlMapping: options?.imageUrlMapping
		});

		results.push(result);

		// Update summary
		if (result.success) {
			summary.successful++;
			if (result.warnings && result.warnings.length > 0) {
				summary.warnings++;
			}
			// Track image conversion stats
			if (result.stats) {
				summary.imagesConverted += result.stats.imagesConverted;
				summary.imagesMissing += result.stats.imagesMissing;
			}
		} else {
			summary.failed++;

			// Check why it failed
			if (result.stats?.hasImages) {
				summary.skippedImages++;
			}
			if (result.stats?.hasCustomValidation) {
				summary.skippedCustomValidation++;
			}
		}
	}

	return { results, summary };
}

// ============================================================================
// VALIDATION
// ============================================================================

/**
 * Validate a transformed template
 */
export function validateTransformedTemplate(template: QuestionTemplate): {
	valid: boolean;
	errors: string[];
} {
	const errors: string[] = [];

	// Check required fields
	if (!template.type) {
		errors.push('Missing question type');
	}

	if (!template.title) {
		errors.push('Missing title');
	}

	if (!template.variations || template.variations.length === 0) {
		errors.push('No variations provided');
	}

	if (!template.grades || template.grades.length === 0) {
		errors.push('No grades specified');
	}

	if (!template.theme) {
		errors.push('Missing theme');
	}

	if (!template.domain) {
		errors.push('Missing domain');
	}

	if (typeof template.level !== 'number' || template.level < 1) {
		errors.push('Invalid level');
	}

	if (!template.status) {
		errors.push('Missing status');
	}

	// Validate each variation
	template.variations.forEach((variation, index) => {
		if (!variation.statement || variation.statement.length === 0) {
			errors.push(`Variation ${index}: missing statement`);
		}

		if (variation.solution === undefined || variation.solution === null) {
			errors.push(`Variation ${index}: missing solution`);
		}

		// Type-specific validation
		if (template.type === 'multiple_choice' && !variation.choices) {
			errors.push(`Variation ${index}: multiple choice question missing choices`);
		}

		if (template.type === 'fill_in_blanks' && !variation.blanks) {
			errors.push(`Variation ${index}: fill-in-blanks question missing blanks`);
		}
	});

	return {
		valid: errors.length === 0,
		errors
	};
}

// ============================================================================
// EXPORT
// ============================================================================

export default {
	transformQuestion,
	transformQuestionBatch,
	validateTransformedTemplate
};
