/**
 * Global resource search — server side.
 *
 * Thin wrapper over the `search_resources` SQL function (migration
 * 20260908120000). Shared by `GET /api/search` and the teacher search page so
 * the two can never drift apart.
 *
 * The function is `SECURITY INVOKER` and reads the `resources` view, which is
 * `security_invoker = true`: results are already filtered by the caller's RLS.
 * Restricting the search to teachers and admins is a **product** decision
 * enforced at the route level, not the thing that keeps a student's data safe.
 *
 * @module server/search
 */

import type { SupabaseClient } from '@supabase/supabase-js';
import type { Database } from '$lib/types/database';
import type { ResourceKind } from '$lib/resources/kinds';

/**
 * One row of the `resources` view.
 *
 * Declared here rather than in `database.ts`, which is generated by
 * `pnpm db:types` and must never be hand-edited. Once the migration is live in
 * production and the types are regenerated, this stays as the documented shape
 * the app relies on.
 */
export interface ResourceSearchRow {
	kind: ResourceKind;
	id: string;
	/** Never empty: the view falls back to the slug, then to a placeholder. */
	title: string;
	subtitle: string | null;
	grades: string[] | null;
	status: string | null;
	is_public: boolean;
	owner_id: string | null;
	slug: string | null;
	updated_at: string | null;
}

export interface SearchResourcesParams {
	/** Texte libre. Facultatif dès lors qu'au moins un tag est fourni. */
	query: string;
	kinds?: ResourceKind[];
	/** Noms de tags ; la comparaison se fait sur leur forme canonique. */
	tags?: string[];
	limit?: number;
}

/**
 * Shape of the RPC as the generated types will describe it once
 * `pnpm db:types` has run against a database carrying the migration. Until
 * then the generated `Database` type has no entry for the function, so the call
 * is made through this narrow adapter rather than with `any`.
 */
type SearchRpc = (
	fn: 'search_resources',
	args: {
		p_query: string;
		p_kinds: string[] | null;
		p_tags: string[] | null;
		p_limit: number;
	}
) => PromiseLike<{ data: ResourceSearchRow[] | null; error: { message: string } | null }>;

/**
 * Search resources by title and metadata.
 *
 * @returns rows the caller is allowed to read, most relevant first
 * @throws never — a database failure is returned as an empty list plus the error
 */
export async function searchResources(
	supabase: SupabaseClient<Database>,
	{ query, kinds, tags, limit = 20 }: SearchResourcesParams
): Promise<{ rows: ResourceSearchRow[]; error: string | null }> {
	const rpc = supabase.rpc as unknown as SearchRpc;

	const { data, error } = await rpc('search_resources', {
		p_query: query,
		p_kinds: kinds && kinds.length > 0 ? kinds : null,
		p_tags: tags && tags.length > 0 ? tags : null,
		p_limit: limit
	});

	if (error) {
		console.error('[search] search_resources failed:', error);
		return { rows: [], error: 'Échec de la recherche' };
	}

	return { rows: data ?? [], error: null };
}
