#!/usr/bin/env tsx
/**
 * Question Image Migration Script
 * ================================
 *
 * Converts PNG question images to WebP format and uploads to Supabase Storage.
 *
 * Context:
 * - 214 unique images referenced in old questions system
 * - All PNG format (100%)
 * - Converting PNG → WebP with quality 85 for ~70% size reduction
 * - Target: Supabase Storage bucket 'question-images'
 *
 * IMPORTANT: Source images are NOT in this repository!
 * You must obtain them first (see README for instructions).
 *
 * Prerequisites:
 *   1. Run: pnpm tsx scripts/extract-question-image-refs.ts
 *      This generates scripts/question-images-list.json
 *   2. Obtain source images (download from production, backup, or generate)
 *   3. Place images in one of the configured source directories
 *   4. Install sharp: pnpm add -D sharp (only needed for --execute)
 *   5. Set env vars: PUBLIC_SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY
 *   6. Create bucket 'question-images' in Supabase Storage
 *
 * Usage:
 *   pnpm tsx scripts/migrate-question-images.ts --dry-run   # Preview
 *   pnpm tsx scripts/migrate-question-images.ts --execute   # Migrate
 *
 * Output:
 *   - Uploads images to Supabase Storage
 *   - Generates mapping file: scripts/image-url-mapping.json
 *
 * @see scripts/README-question-images.md - Full documentation
 * @see scripts/question-images-list.json - List of all referenced images
 * @see docs/wip/question-migration-analysis.md (Section 22) - Analysis
 */

import { createClient } from '@supabase/supabase-js';
import * as dotenv from 'dotenv';
import * as fs from 'fs/promises';
import * as path from 'path';
import { glob } from 'glob';

dotenv.config();

// ============================================================================
// CONFIGURATION
// ============================================================================

const CONFIG = {
	// Source directories (possible locations for question images)
	sourceDirs: [
		'static/questions',
		'static/images/questions',
		'extern/new-tinymath/apps/ubumaths/public/images',
		'extern/new-tinymath/apps/ubumaths/static/images'
	],
	// File containing image references from questions.ts
	// This should be generated by analyzing the old questions file
	imageListFile: 'scripts/question-images-list.json',
	// Target Supabase Storage bucket
	bucket: 'question-images',
	// WebP quality (0-100) - 85 is recommended for diagrams
	quality: 85,
	// WebP compression effort (0-6) - higher = smaller files but slower
	effort: 6,
	// Batch size for uploads (reduced to avoid network timeouts)
	batchSize: 3,
	// Retry settings for failed uploads
	maxRetries: 3,
	retryDelayMs: 2000,
	// Output mapping file
	mappingFile: 'scripts/image-url-mapping.json',
	// Supported source formats
	supportedFormats: ['png', 'jpg', 'jpeg'],
	// Exclude patterns (to avoid migrating non-question images)
	excludePatterns: [
		'**/avatars/**',
		'**/navadra/**',
		'**/vips/**',
		'**/*logo*',
		'**/*avatar*',
		'**/pomodoro*',
		'**/pile.png',
		'**/workflow.png',
		'**/spiral-pi.png',
		'**/methodes-*.png',
		'**/*good-job*',
		'**/*great*',
		'**/*keep-on*',
		'**/*try-again*',
		'**/coup-double.png',
		'**/gidouille.png',
		'**/stackblitz-*'
	]
};

// Check for mode flags
const isDryRun = process.argv.includes('--dry-run');
const isExecute = process.argv.includes('--execute');

if (!isDryRun && !isExecute) {
	console.log('❌ Error: Please specify either --dry-run or --execute flag\n');
	console.log('Usage:');
	console.log('  pnpm tsx scripts/migrate-question-images.ts --dry-run   # Preview changes');
	console.log('  pnpm tsx scripts/migrate-question-images.ts --execute   # Apply migration\n');
	process.exit(1);
}

// Environment variables (only check in execute mode)
const supabaseUrl = process.env.PUBLIC_SUPABASE_URL;
const supabaseServiceKey = process.env.SUPABASE_SERVICE_ROLE_KEY;

if (isExecute && (!supabaseUrl || !supabaseServiceKey)) {
	console.error('❌ Missing required environment variables:');
	console.error('   - PUBLIC_SUPABASE_URL');
	console.error('   - SUPABASE_SERVICE_ROLE_KEY');
	process.exit(1);
}

// ============================================================================
// TYPES
// ============================================================================

interface MigrationResult {
	sourcePath: string;
	targetPath: string;
	originalSize: number;
	convertedSize: number;
	reduction: number; // Percentage
	success: boolean;
	error?: string;
	publicUrl?: string;
}

interface MigrationStats {
	total: number;
	succeeded: number;
	failed: number;
	skipped: number;
	totalOriginalBytes: number;
	totalConvertedBytes: number;
	averageReduction: number;
}

interface UrlMapping {
	[oldPath: string]: string; // oldPath -> new public URL
}

// ============================================================================
// IMAGE DISCOVERY
// ============================================================================

/**
 * Check if a file path matches any exclude pattern
 */
function isExcluded(filePath: string): boolean {
	const normalizedPath = path.normalize(filePath);

	for (const pattern of CONFIG.excludePatterns) {
		// Convert glob pattern to regex
		const regexPattern = pattern.replace(/\*\*/g, '.*').replace(/\*/g, '[^/]*').replace(/\?/g, '.');

		const regex = new RegExp(regexPattern);

		if (regex.test(normalizedPath)) {
			return true;
		}
	}

	return false;
}

/**
 * Find all source images in configured directories
 */
async function findSourceImages(): Promise<string[]> {
	console.log('🔍 Searching for source images...\n');

	const allImages: string[] = [];
	let _totalFound = 0;
	let totalExcluded = 0;

	for (const dir of CONFIG.sourceDirs) {
		const fullPath = path.resolve(dir);

		// Check if directory exists
		try {
			await fs.access(fullPath);
		} catch {
			console.log(`⏭️  Skipping non-existent directory: ${dir}`);
			continue;
		}

		// Find images in this directory
		for (const ext of CONFIG.supportedFormats) {
			const pattern = path.join(fullPath, `**/*.${ext}`);
			const images = await glob(pattern, {
				ignore: CONFIG.excludePatterns
			});

			// Additional filtering with custom exclude logic
			const filtered = images.filter((img) => {
				if (isExcluded(img)) {
					totalExcluded++;
					return false;
				}
				return true;
			});

			allImages.push(...filtered);
			_totalFound += images.length;
		}

		console.log(`   ${dir}: ${allImages.length} images (${totalExcluded} excluded)`);
	}

	// Remove duplicates and sort
	const uniqueImages = [...new Set(allImages)].sort();

	console.log(`\n✅ Found ${uniqueImages.length} unique question image(s)`);
	console.log(`   (Excluded ${totalExcluded} non-question images)\n`);

	return uniqueImages;
}

// ============================================================================
// IMAGE CONVERSION (Dry-run compatible)
// ============================================================================

/**
 * Convert image to WebP format
 * In dry-run mode, only calculates estimated size without sharp
 */
async function convertToWebP(sourcePath: string): Promise<Buffer | null> {
	if (isDryRun) {
		// In dry-run mode, we don't actually convert
		// Just return null to skip conversion
		return null;
	}

	// NOTE: sharp must be installed for execute mode
	// Run: pnpm add -D sharp
	try {
		const sharp = (await import('sharp')).default;

		return await sharp(sourcePath)
			.webp({
				quality: CONFIG.quality,
				effort: CONFIG.effort
			})
			.toBuffer();
	} catch (error) {
		if ((error as NodeJS.ErrnoException).code === 'ERR_MODULE_NOT_FOUND') {
			console.error('\n❌ Error: sharp package not found');
			console.error('   Install with: pnpm add -D sharp\n');
			process.exit(1);
		}
		throw error;
	}
}

// ============================================================================
// SUPABASE UPLOAD
// ============================================================================

/**
 * Delay helper for retry logic
 */
function delay(ms: number): Promise<void> {
	return new Promise((resolve) => setTimeout(resolve, ms));
}

/**
 * Upload image buffer to Supabase Storage with retry logic
 * Returns public URL
 */
async function uploadToSupabase(
	supabase: ReturnType<typeof createClient>,
	buffer: Buffer,
	targetPath: string
): Promise<string> {
	let lastError: Error | null = null;

	for (let attempt = 1; attempt <= CONFIG.maxRetries; attempt++) {
		try {
			// Upload to storage
			const { error: uploadError } = await supabase.storage
				.from(CONFIG.bucket)
				.upload(targetPath, buffer, {
					contentType: 'image/webp',
					cacheControl: '31536000', // 1 year (immutable images)
					upsert: true // Allow re-running script
				});

			if (uploadError) {
				throw new Error(`Upload failed: ${uploadError.message}`);
			}

			// Get public URL
			const {
				data: { publicUrl }
			} = supabase.storage.from(CONFIG.bucket).getPublicUrl(targetPath);

			return publicUrl;
		} catch (error) {
			lastError = error instanceof Error ? error : new Error(String(error));

			if (attempt < CONFIG.maxRetries) {
				const waitTime = CONFIG.retryDelayMs * attempt; // Exponential backoff
				console.log(`   ⚠️  Retry ${attempt}/${CONFIG.maxRetries} in ${waitTime}ms...`);
				await delay(waitTime);
			}
		}
	}

	throw lastError || new Error('Upload failed after retries');
}

// ============================================================================
// MIGRATION LOGIC
// ============================================================================

/**
 * Generate target path for an image
 * Preserves directory structure within source
 */
function generateTargetPath(sourcePath: string): string {
	// Find which source directory this image comes from
	for (const dir of CONFIG.sourceDirs) {
		const fullDir = path.resolve(dir);
		if (sourcePath.startsWith(fullDir)) {
			// Get relative path from source directory
			const relativePath = path.relative(fullDir, sourcePath);

			// Replace extension with .webp
			const targetPath = relativePath.replace(/\.(png|jpg|jpeg)$/i, '.webp');

			return targetPath;
		}
	}

	// Fallback: use basename with webp extension
	const basename = path.basename(sourcePath, path.extname(sourcePath));
	return `${basename}.webp`;
}

/**
 * Migrate a single image
 */
async function migrateImage(
	sourcePath: string,
	supabase: ReturnType<typeof createClient> | null
): Promise<MigrationResult> {
	const targetPath = generateTargetPath(sourcePath);

	try {
		// Get original file stats
		const stats = await fs.stat(sourcePath);
		const originalSize = stats.size;

		// Convert to WebP
		const webpBuffer = await convertToWebP(sourcePath);

		if (isDryRun) {
			// Dry run mode: estimate conversion
			const estimatedSize = Math.round(originalSize * 0.3); // WebP is ~30% of PNG
			const reduction = ((originalSize - estimatedSize) / originalSize) * 100;

			return {
				sourcePath,
				targetPath,
				originalSize,
				convertedSize: estimatedSize,
				reduction,
				success: true
			};
		}

		// Execute mode: actual conversion
		if (!webpBuffer || !supabase) {
			throw new Error('Missing buffer or Supabase client');
		}

		const convertedSize = webpBuffer.length;
		const reduction = ((originalSize - convertedSize) / originalSize) * 100;

		// Upload to Supabase
		const publicUrl = await uploadToSupabase(supabase, webpBuffer, targetPath);

		return {
			sourcePath,
			targetPath,
			originalSize,
			convertedSize,
			reduction,
			success: true,
			publicUrl
		};
	} catch (error) {
		return {
			sourcePath,
			targetPath,
			originalSize: 0,
			convertedSize: 0,
			reduction: 0,
			success: false,
			error: error instanceof Error ? error.message : String(error)
		};
	}
}

// ============================================================================
// BATCH PROCESSING
// ============================================================================

/**
 * Process images in batches
 */
async function processInBatches(
	images: string[],
	supabase: ReturnType<typeof createClient> | null
): Promise<MigrationResult[]> {
	const results: MigrationResult[] = [];
	const batches = Math.ceil(images.length / CONFIG.batchSize);

	console.log(`📦 Processing ${images.length} images in ${batches} batch(es)...\n`);

	for (let i = 0; i < images.length; i += CONFIG.batchSize) {
		const batch = images.slice(i, i + CONFIG.batchSize);
		const batchNumber = Math.floor(i / CONFIG.batchSize) + 1;

		console.log(`\n📦 Batch ${batchNumber}/${batches} (${batch.length} images)`);
		console.log('='.repeat(70));

		// Process batch in parallel
		const batchResults = await Promise.all(
			batch.map(async (imagePath) => {
				const result = await migrateImage(imagePath, supabase);

				// Log individual result
				const status = result.success ? '✅' : '❌';
				const sizeInfo = result.success
					? `${formatBytes(result.originalSize)} → ${formatBytes(result.convertedSize)} (-${result.reduction.toFixed(1)}%)`
					: result.error;

				console.log(`${status} ${path.basename(result.sourcePath)}`);
				console.log(`   ${sizeInfo}`);
				if (result.publicUrl) {
					console.log(`   URL: ${result.publicUrl}`);
				}

				return result;
			})
		);

		results.push(...batchResults);
	}

	return results;
}

// ============================================================================
// REPORTING
// ============================================================================

/**
 * Format bytes to human-readable string
 */
function formatBytes(bytes: number): string {
	if (bytes === 0) return '0 B';
	const k = 1024;
	const sizes = ['B', 'KB', 'MB'];
	const i = Math.floor(Math.log(bytes) / Math.log(k));
	return `${(bytes / Math.pow(k, i)).toFixed(2)} ${sizes[i]}`;
}

/**
 * Calculate migration statistics
 */
function calculateStats(results: MigrationResult[]): MigrationStats {
	const succeeded = results.filter((r) => r.success);
	const failed = results.filter((r) => !r.success);

	const totalOriginalBytes = succeeded.reduce((sum, r) => sum + r.originalSize, 0);
	const totalConvertedBytes = succeeded.reduce((sum, r) => sum + r.convertedSize, 0);

	const averageReduction =
		succeeded.length > 0
			? succeeded.reduce((sum, r) => sum + r.reduction, 0) / succeeded.length
			: 0;

	return {
		total: results.length,
		succeeded: succeeded.length,
		failed: failed.length,
		skipped: 0,
		totalOriginalBytes,
		totalConvertedBytes,
		averageReduction
	};
}

/**
 * Print migration summary
 */
function printSummary(stats: MigrationStats, mode: 'dry-run' | 'execute'): void {
	console.log('\n' + '='.repeat(70));
	console.log(`📊 Migration Summary (${mode.toUpperCase()})`);
	console.log('='.repeat(70));
	console.log(`Total images:         ${stats.total}`);
	console.log(`✅ Succeeded:         ${stats.succeeded}`);
	console.log(`❌ Failed:            ${stats.failed}`);
	console.log(`⏭️  Skipped:           ${stats.skipped}`);
	console.log('');
	console.log(`Original size:        ${formatBytes(stats.totalOriginalBytes)}`);
	console.log(`Converted size:       ${formatBytes(stats.totalConvertedBytes)}`);
	console.log(
		`Space saved:          ${formatBytes(stats.totalOriginalBytes - stats.totalConvertedBytes)} (${stats.averageReduction.toFixed(1)}% avg reduction)`
	);
	console.log('='.repeat(70) + '\n');
}

/**
 * Generate URL mapping file
 */
async function generateUrlMapping(results: MigrationResult[]): Promise<void> {
	const mapping: UrlMapping = {};

	for (const result of results) {
		if (result.success && result.publicUrl) {
			// Map old path to new public URL
			mapping[result.sourcePath] = result.publicUrl;

			// Also map relative paths from various base directories
			for (const dir of CONFIG.sourceDirs) {
				const fullDir = path.resolve(dir);
				if (result.sourcePath.startsWith(fullDir)) {
					const relativePath = path.relative(fullDir, result.sourcePath);
					mapping[relativePath] = result.publicUrl;
					mapping[`/${relativePath}`] = result.publicUrl;
					mapping[`/images/${relativePath}`] = result.publicUrl;
				}
			}
		}
	}

	// Write mapping file
	const mappingPath = path.resolve(CONFIG.mappingFile);
	await fs.writeFile(mappingPath, JSON.stringify(mapping, null, 2), 'utf-8');

	console.log(`📝 URL mapping written to: ${CONFIG.mappingFile}`);
	console.log(`   ${Object.keys(mapping).length} mappings generated\n`);
}

// ============================================================================
// MAIN
// ============================================================================

async function main() {
	console.log('🚀 Question Image Migration Script');
	console.log('='.repeat(70));
	console.log(
		`Mode: ${isDryRun ? '🧪 DRY RUN (no actual changes)' : '✍️  EXECUTE (will upload to Supabase)'}\n`
	);

	// 1. Find all source images
	const images = await findSourceImages();

	if (images.length === 0) {
		console.log('✅ No images found to migrate.');
		return;
	}

	// 2. Initialize Supabase client (only in execute mode)
	let supabase: ReturnType<typeof createClient> | null = null;

	if (isExecute) {
		supabase = createClient(supabaseUrl!, supabaseServiceKey!, {
			auth: {
				autoRefreshToken: false,
				persistSession: false
			}
		});

		// Verify bucket exists
		const { data: buckets, error } = await supabase.storage.listBuckets();
		if (error) {
			console.error('❌ Error accessing Supabase Storage:', error.message);
			process.exit(1);
		}

		const bucketExists = buckets?.some((b) => b.name === CONFIG.bucket);
		if (!bucketExists) {
			console.error(`❌ Error: Bucket '${CONFIG.bucket}' does not exist in Supabase Storage`);
			console.error('   Create it in the Supabase Dashboard first.');
			process.exit(1);
		}

		console.log(`✅ Connected to Supabase Storage (bucket: ${CONFIG.bucket})\n`);
	}

	// 3. Process images
	const results = await processInBatches(images, supabase);

	// 4. Calculate and print statistics
	const stats = calculateStats(results);
	printSummary(stats, isDryRun ? 'dry-run' : 'execute');

	// 5. Generate URL mapping (only in execute mode)
	if (isExecute) {
		await generateUrlMapping(results);
	}

	// 6. Final messages
	if (isDryRun) {
		console.log('🧪 DRY RUN COMPLETE - No changes were made');
		console.log('💡 To apply migration, run with --execute flag');
		console.log('   Note: Install sharp first with: pnpm add -D sharp\n');
	} else {
		if (stats.failed > 0) {
			console.log('⚠️  Some images failed to migrate. Review errors above.');
			process.exit(1);
		} else {
			console.log('🎉 Migration completed successfully!');
			console.log('✅ All images converted to WebP and uploaded to Supabase Storage');
			console.log(`📝 URL mapping saved to ${CONFIG.mappingFile}\n`);
		}
	}
}

// ============================================================================
// ENTRY POINT
// ============================================================================

main().catch((error) => {
	console.error('❌ Fatal error:', error);
	process.exit(1);
});
