import type { Game } from './types'

import {
	CP,
	CM1,
	CM2,
	SIXIEME,
	SECONDE,
	CINQUIEME,
	QUATRIEME,
	CE1,
	CE2,
	TROISIEME,
	PREMIERE_SPE_MATHS,
	TERMINALE_SPE_MATHS,
} from '$lib/grades.js'

const games: Record<string, Game> = {
	'1 - opérations simples': [
		{
			description: '',
			enounces: [''],
			expressions: ['18:18'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['100:50'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['33:11'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['28:7'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['45:9'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['36:6'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['56:8'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['2*2*2'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['81:9'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['90-80'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['59-48'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['48:4'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['39:3'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['90-76'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['60:4'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['50-34'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['30:13'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['3*2*3'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['40-21'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['90-70'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['84:4'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['77-55'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['69:3'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['2*2*2*3'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['75:3'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['40-14'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['3*3*3'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['2*7*2'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['50-21'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['3*5*2'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['60-29'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['4*4*2'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['16+17'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['17*2'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['7*5'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['12*3'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['18+19'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['2*19'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['78:2'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['23+17'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['15+26'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['6*7'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['90-47'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['11*4'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['9*5'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['23*2'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['13+34'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['96:2'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['7*7'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['5*5*2'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['36+15'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['26*2'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['31+22'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['18*3'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['80-25'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['8*7'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['38+19'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['2*29'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['9+30+20'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['12*5'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['100-39'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['44:18'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['7*9'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['8*8'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['100-35'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['3*22'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['58+9'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['4*17'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['3*23'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['98-28'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['90-19'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['8*9'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['82-9'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['37*2'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['25*3'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['38*2'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['7+50+20'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['19+59'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['100-21'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['2*5*8'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['9*9'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['97-15'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['16+67'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['36+48'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['5*17'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['99-13'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['100-13'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['2*2*2*11'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['25+64'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['12+78'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
	],
	'2 - fractions': [
		{
			description: '',
			enounces: [''],
			expressions: ['{1/100}*100'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['0,2*10'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['{3/10}*10'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['{1/7}*28'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['450:90'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['{2/3}*9'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['770:110'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: ['Le quart de $$32$$'],
			solutionss: [['8']],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: ['Le dixième de $$90$$'],
			solutionss: [['9']],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: ['Le centième de $$1000$$'],
			solutionss: [['10']],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: ['La somme de $$8$$ et $$3$$'],
			solutionss: [['11']],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: ['$$6$$ fois le nombre $$2$$'],
			solutionss: [['12']],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: ['Le quotient de $$26$$ par $$2$$'],
			solutionss: [['13']],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: ['La différence entre $$30$$ et $$16$$'],
			solutionss: [['14']],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: ['$$30$$ ôtés de$$45$$'],
			solutionss: [['15']],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['160*{1/10}'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['{17/100}*100'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: ['Une dizaine et huit unités'],
			solutionss: [['18']],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['38:2'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: ['Le tiers de 60'],
			solutionss: [['20']],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: ['$$63$$ partagés en $$3$$ parts égales'],
			solutionss: [['21']],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['20-2+4'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['46-11-12'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: ['$$15$$ ajoutés à $$9$$'],
			solutionss: [['24']],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: ['$$3$$ ajoutés au double de $$11$$'],
			solutionss: [['25']],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: ['Le double de $$13$$'],
			solutionss: [['26']],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['3*3*3'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['6*8-20'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['90/3-1'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['900:30'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['100-69'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['8*7-8*3'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['4*2+5*5'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['17+17'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['4*9-1'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['2*2*3*3'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['74*{1/2}'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['76:2'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['3*10+3*3'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['4000:100'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['10+10+10+11'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['42*5-42*4'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['88:2-1'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['11+11+11+11'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['3*5*3'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['4600*0,01'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['32+15'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['9+38+1'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['7*7'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['1000:20'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['3*17'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['151-99'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['200-147'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['0,6*0,9*100'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['110*{1/2}'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['2*56-56'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['7*57-6*57'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['0,58*100'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['70-11'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['2*2*3*5'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['{1/4}*244'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['{1/2}*124'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['7*10-7'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['8*4*2'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['130:2'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['6+6*10'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['120-53'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['8+2*30'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['23*3'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['7000*{1/100}'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['35+1+35'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['6*12'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['18+35+20'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['2*37'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['3*25'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['7,6*10'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['8*10-3'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['780*0,1'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['19+2*30'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['0,8*100'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['27*3'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['164:2'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['249:3'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['12*7'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['67+17+1'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['100-10-4'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['39+48'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['7*11+11'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['100-11'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['900*{1/10}'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
	],
	'3 - nombres relatifs': [
		{
			description: '',
			enounces: [''],
			expressions: ['(-1)^2'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['(1/2)^2*8'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['22*3-21*3'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['2^5:2^3'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['(-2)^2+(-1)^2'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['42*{1/7}'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['-49:(-7)'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['2^3'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['(-3)^2'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['-1:(-0,1)'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: ['Le tiers de $$11*3$$'],
			solutionss: [['11']],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: ["L'opposé de $$-4*3$$"],
			solutionss: [['12']],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: ['$$50%$$ de $$26$$'],
			solutionss: [['13']],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['2^4-2^1'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['-100*(-0,15)'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['5^2-3^2'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: ["L'opposé de $$-17$$"],
			solutionss: [['17']],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: ['Le double de $$(-3)^2$$'],
			solutionss: [['18']],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['-(-2-17)'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: ['La moitié du quart de $$160$$'],
			solutionss: [['20']],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['(-10)*(-2,1)'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['(-5)^2-3'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['(-2)*(-4)+3*5'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: ['$$50%$$ de $$48$$'],
			solutionss: [['24']],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['5^2'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: ['$$26%$$ de $$100$$'],
			solutionss: [['26']],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['3^3'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['1-(-3)^3'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['-(1-30)'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['(-3)*(-10)'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: ['$$10%%$$ de $$310$$'],
			solutionss: [['31']],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['15+17'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['0,3*1,1*100'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['5^2+3^2'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['70*{1/2}'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['(-2)^2*(-3)^2'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['-13+50'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: ["L'opposé de l'inverse de $$-{1/38}$$"],
			solutionss: [['38']],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['0,3*130'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['0,2*0,2*1000'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['{1/10}*410'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['(-6)^2+6'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['4*(-2)+51'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['11*8-11*4'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: ['Le triple de la moitié de $$30$$'],
			solutionss: [['45']],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: ["L'opposé de $$2*(-23)$$"],
			solutionss: [['46']],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['52+(-5)'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['5^2*2+(-2)'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['(-7)^2'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['2*5^2'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['50+1^3'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: ["L'opposé de $$4,8-56,8$$"],
			solutionss: [['52']],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['-1-2+56'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['(-6)*(-10)-6'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['5*13-5*2'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: ["L'opposé de $$4-60$$"],
			solutionss: [['56']],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['60-4+1'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: ["L'opposé de $$-50-8$$"],
			solutionss: [['58']],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: ["L'opposé de $$1-6*10$$"],
			solutionss: [['59']],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['2*(-10+40)'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['5^0*61'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['62^1'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['-7*(-9)'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['69,2-5,2'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['7*10-5'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['-2-2+70'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: ["L'opposé de $$-67$$"],
			solutionss: [['67']],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['8*9+(-4)'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['-11+80'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['{1/3}*210'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['-10+81'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['-720:(-10)'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['8*9+1'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['30+60-16'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['3*5*5'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['7*10-(-6)'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['13*7-2*7'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['68+10'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['100-20-1'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['-10-10+100'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['(-9)^2'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['8*10-(-2)'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['90-100+93'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['(-2)*(-42)'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['10^2-3*5'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['6+8*10'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['83-(-4)'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['9^2+7'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['-2+91'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['(-2)*(-5)*(-3)^2'],
			defaultDelay: 10,
			grade: SIXIEME,
		},
	],
	'4 - équations': [
		{
			description: '',
			enounces: [''],
			expressions: ['2x-x+4=5'],
			solutionss: [['1']],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['x-x/2=1'],
			solutionss: [['2']],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['x-3x=-6'],
			solutionss: [['3']],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['-x*15=-60'],
			solutionss: [['4']],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['0,4x=2'],
			solutionss: [['5']],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['{-x+6}/5=0'],
			solutionss: [['6']],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['-x*(-2)=14'],
			solutionss: [['7']],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['x*{1/4}=2'],
			solutionss: [['8']],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['x*{{-1}/3}=-3'],
			solutionss: [['9']],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['7,8x=78'],
			solutionss: [['10']],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['-x-4=-15'],
			solutionss: [['11']],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['x+2x+7x=120'],
			solutionss: [['12']],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['2x+1=27'],
			solutionss: [['13']],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['x+x=14+14'],
			solutionss: [['14']],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['5x=75'],
			solutionss: [['15']],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['10x-1=159'],
			solutionss: [['16']],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['-x-6=-23'],
			solutionss: [['17']],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['2x-6=30'],
			solutionss: [['18']],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['-x+5=-14'],
			solutionss: [['19']],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['x*0,2=4'],
			solutionss: [['20']],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['3x=9*7'],
			solutionss: [['21']],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['{2x}/4=11'],
			solutionss: [['22']],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['x*10^{-2}=0,23'],
			solutionss: [['23']],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['x/0,1=240'],
			solutionss: [['24']],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['x/100=0,25'],
			solutionss: [['25']],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['{-x+26}/5=0'],
			solutionss: [['26']],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['{x-27}/3=0'],
			solutionss: [['27']],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['{x-1}/27=1'],
			solutionss: [['28']],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['x+(-3)=26'],
			solutionss: [['29']],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['2x+40=100'],
			solutionss: [['30']],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['{-x}/31=-1'],
			solutionss: [['31']],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['x/{-32}=-1'],
			solutionss: [['32']],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['3x=99'],
			solutionss: [['33']],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['-2x=-68'],
			solutionss: [['34']],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['x/1000=0,035'],
			solutionss: [['35']],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['{2x}/20=3,6'],
			solutionss: [['36']],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['x-(-4)=41'],
			solutionss: [['37']],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['-x+7=-31'],
			solutionss: [['38']],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['x/3=13'],
			solutionss: [['39']],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['30x=1200'],
			solutionss: [['40']],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['90-x=49'],
			solutionss: [['41']],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['-2x+4=-80'],
			solutionss: [['42']],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['2x+14=100'],
			solutionss: [['43']],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['20x=880'],
			solutionss: [['44']],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['{-x}/15=-3'],
			solutionss: [['45']],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['-2x+1=-91'],
			solutionss: [['46']],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['-x+18=-29'],
			solutionss: [['47']],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['-2x=-96'],
			solutionss: [['48']],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['x/{-7}=-7'],
			solutionss: [['49']],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['1000=20x'],
			solutionss: [['50']],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['x/3=17'],
			solutionss: [['51']],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['0,5x=26'],
			solutionss: [['52']],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['x-4=49'],
			solutionss: [['53']],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['-x-2=-56'],
			solutionss: [['54']],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['0,2x=11'],
			solutionss: [['55']],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['2x+1=113'],
			solutionss: [['56']],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['101-x=44'],
			solutionss: [['57']],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['-{x/2}=-29'],
			solutionss: [['58']],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['-x+3=-56'],
			solutionss: [['59']],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['x+5x=360'],
			solutionss: [['60']],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['x-1=60'],
			solutionss: [['61']],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['{1/2}x=31'],
			solutionss: [['62']],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['x/9=7'],
			solutionss: [['63']],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['x/8=8'],
			solutionss: [['64']],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['x/5=13'],
			solutionss: [['65']],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['-x-6=-72'],
			solutionss: [['66']],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['-x=-67'],
			solutionss: [['67']],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['2x=136'],
			solutionss: [['68']],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['x/3=23'],
			solutionss: [['69']],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['5000x=350000'],
			solutionss: [['70']],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['-3-x=-74'],
			solutionss: [['71']],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['x+72=144'],
			solutionss: [['72']],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['93-x=20'],
			solutionss: [['73']],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['x/2-1=36'],
			solutionss: [['74']],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['x/3+1=26'],
			solutionss: [['75']],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['x-(-4)=80'],
			solutionss: [['76']],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['{-x}/7=-11'],
			solutionss: [['77']],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['-x=-78'],
			solutionss: [['78']],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['x+11=90'],
			solutionss: [['79']],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['{2x}/80=2'],
			solutionss: [['80']],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['{-x}/{-9}=9'],
			solutionss: [['81']],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['x+x=164'],
			solutionss: [['82']],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['x/83=1'],
			solutionss: [['83']],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['{1/4}x=21'],
			solutionss: [['84']],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['x+15=100'],
			solutionss: [['85']],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['-x-14=-100'],
			solutionss: [['86']],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['100-x=13'],
			solutionss: [['87']],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['{1/11}x=8'],
			solutionss: [['88']],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['x-11=78'],
			solutionss: [['89']],
			defaultDelay: 10,
			grade: SIXIEME,
		},
		{
			description: '',
			enounces: [''],
			expressions: ['40x=3600'],
			solutionss: [['90']],
			defaultDelay: 10,
			grade: SIXIEME,
		},
	],
}

export default games
