-- Retrait des droits HÉRITÉS de `anon` (visiteur non connecté) — option b
-- ==============================================================================
--
-- Contexte : la migration 20261001120000 a coupé les droits par défaut de `anon`
-- pour les FUTURS objets. Restaient les droits déjà accordés (hérités) : la
-- plupart des tables de `public` donnaient tout à `anon` (lecture, écriture,
-- suppression) sans AUCUNE policy pour `anon` — seule la RLS les rendait
-- inertes — et 143 fonctions restaient exécutables par `anon` (entrée `anon=X`
-- explicite et/ou EXECUTE via PUBLIC).
--
-- QUI PERD QUOI (inventaire mesuré en prod le 2026-10-01) :
--   - `anon` perd TOUT droit sur 143 relations de `public` qui n'ont aucune
--     policy visant `anon` ou `public` : 141 tables et vues (security_invoker),
--     la vue matérialisée `student_achievement_stats`, la séquence
--     `riddles_riddle_number_seq`. Avant : la RLS lui rendait zéro ligne (ou un
--     refus d'écriture). Après : « permission denied » (42501). Aucune donnée
--     visible ne change : il n'en voyait déjà aucune.
--   - `anon` et PUBLIC perdent EXECUTE sur 143 fonctions de `public` : triggers,
--     calculs, RPC appelées seulement par des routes authentifiées (grep `src`
--     du 2026-10-01 : generate_join_code, get_accessible_kanban_boards,
--     mark_checkpoint_hint_revealed, rag_hybrid_search, reorder_curriculum_*,
--     upsert_checkpoint_run — toutes derrière une session). Les triggers ne
--     vérifient pas EXECUTE au déclenchement : ils continuent de tourner.
--     Aucune de ces fonctions n'apparaît dans une policy, un DEFAULT, un index ou
--     une vue (pg_depend, prod). `is_valid_grade_array` sert dans 4 CHECK
--     (exercises, question_templates, rag_documents, worksheets) : `anon`
--     n'écrit dans aucune de ces tables.
--   - Autres rôles connectés qui passaient par PUBLIC (ex. lecteur MCP
--     read-only) perdent aussi EXECUTE sur ces 143 fonctions. `postgres`
--     (propriétaire, pg_cron) n'est pas concerné.
--
-- QUI GARDE QUOI :
--   - `authenticated` et `service_role` : inchangés. Ils ont déjà un GRANT
--     EXECUTE explicite sur les 143 fonctions en prod ; il est rejoué ci-dessous
--     pour ne pas dépendre de PUBLIC. Leurs droits sur les tables ne sont pas
--     touchés.
--   - `anon` garde ses droits sur les tables qui ont une policy pour lui ou pour
--     `public` (dont les 3 lues réellement sans connexion : question_templates,
--     resource_tags, parody_evaluations ; et tags). Les autres tables à policy
--     `public` seront traitées à part.
--   - `anon` garde EXECUTE sur les 4 RPC des pages publiques (toutes SECURITY
--     DEFINER) : get_consent_info, get_worksheet_by_share_token,
--     get_class_journal_by_share_token, get_exercise_by_share_token.
--
-- Additive au sens des données : aucune ligne n'est perdue, seuls des droits
-- inutilisés sont retirés.
--
-- Preuve : tests/integration/anon-option-b.test.ts.
--
-- ROLLBACK (droits exacts relevés en prod le 2026-10-01) :
--   grant select, insert, update, delete, references, trigger, maintain on table
--     public.account_deletion_audit,
--     public.achievement_events,
--     public.achievement_migrations,
--     public.app_config,
--     public.audit_logs,
--     public.background_job_runs,
--     public.bonus_history,
--     public.buddy_skins,
--     public.bug_reports,
--     public.bug_reports_config,
--     public.chapter_template_instantiations,
--     public.chapter_template_versions,
--     public.chapter_templates,
--     public.class_chapters,
--     public.class_google_classroom_links,
--     public.class_members,
--     public.classes,
--     public.coursework_categories,
--     public.coursework_materials,
--     public.curriculum_objectives,
--     public.curriculum_point_automatismes,
--     public.curriculum_points,
--     public.curriculum_themes,
--     public.daily_summaries,
--     public.evaluation_task_perimeter,
--     public.evaluation_tasks,
--     public.exercise_curriculum_points,
--     public.exercise_favorites,
--     public.exercise_templates,
--     public.game_2048_scores,
--     public.game_class_settings,
--     public.gidouilles_activity,
--     public.google_classroom_courses,
--     public.google_classroom_coursework,
--     public.google_classroom_material_attachments,
--     public.google_classroom_materials,
--     public.google_classroom_topics,
--     public.google_integrations,
--     public.journal_entry_activities,
--     public.journal_entry_points,
--     public.kanban_boards,
--     public.kanban_card_assignees,
--     public.kanban_card_tags,
--     public.kanban_cards,
--     public.kanban_columns,
--     public.kanban_tags,
--     public.marketplace_chat_messages,
--     public.marketplace_config,
--     public.marketplace_listing_views,
--     public.marketplace_listings,
--     public.marketplace_locked_cards,
--     public.marketplace_proposals,
--     public.marketplace_trade_offers,
--     public.marketplace_trades,
--     public.math_competence_subdimensions,
--     public.math_competences,
--     public.mathemo_scores,
--     public.message_template_versions,
--     public.message_templates,
--     public.migration_edits,
--     public.migration_images,
--     public.migration_tracking,
--     public.minesweeper_multiplayer_game_state,
--     public.minesweeper_multiplayer_matches,
--     public.minesweeper_multiplayer_queue,
--     public.minesweeper_player_stats,
--     public.minesweeper_reference_times_history,
--     public.minesweeper_student_achievements,
--     public.minesweeper_tournament_classes,
--     public.minesweeper_tournament_games,
--     public.minesweeper_tournaments,
--     public.observables,
--     public.orphaned_documents,
--     public.python_exercise_assignments,
--     public.python_exercise_mastery,
--     public.python_exercise_submissions,
--     public.python_submission_server_verdicts,
--     public.question_template_points,
--     public.rag_chunks,
--     public.rag_documents,
--     public.reward_events,
--     public.school_year_closures,
--     public.server_cache,
--     public.shared_coursework,
--     public.shared_coursework_students,
--     public.shared_materials,
--     public.skill_attempts,
--     public.srs_anti_fraud_flags,
--     public.srs_deck_sections,
--     public.student_buddies,
--     public.student_checklist_progress,
--     public.student_competence_level,
--     public.student_observable_state,
--     public.student_point_state,
--     public.student_warnings,
--     public.template_audit_log,
--     public.template_usage_stats,
--     public.terms_acceptances,
--     public.tutor_conversations,
--     public.tutor_messages,
--     public.user_favorite_templates,
--     public.user_preferences,
--     public.user_whiteboard_template_favorites,
--     public.vip_card_config,
--     public.vip_card_templates,
--     public.vip_cards_activity,
--     public.weekly_rewards,
--     public.whiteboard_export_counters,
--     public.whiteboard_templates,
--     public.worksheet_assignment_classes,
--     public.worksheet_assignment_exercise_settings,
--     public.worksheet_assignment_students,
--     public.worksheet_assignments,
--     public.worksheet_error_reports,
--     public.worksheet_exercises,
--     public.worksheet_instances,
--     public.worksheet_sections,
--     public.worksheet_templates,
--     public.worksheets,
--     public.active_student_warnings,
--     public.admin_error_stats_24h,
--     public.admin_job_failures,
--     public.admin_job_status,
--     public.admin_online_users,
--     public.admin_pg_cron_jobs,
--     public.admin_user_activity,
--     public.deck_stats_view,
--     public.game_scores_unified,
--     public.migration_review_tree,
--     public.minesweeper_achievements_compat,
--     public.minesweeper_leaderboard,
--     public.minesweeper_multiplayer_leaderboard,
--     public.minesweeper_student_achievement_progress,
--     public.minesweeper_student_achievements_compat,
--     public.minesweeper_tournament_standings,
--     public.riddle_progress,
--     public.riddle_stats,
--     public.riddle_student_history,
--     public.student_coursework_view,
--     public.student_point_state_v,
--     public.user_conversations_view
--     to anon;
--   grant insert, update, delete, references, trigger, maintain
--     on table public.student_achievement_stats to anon;   -- pas de SELECT : anon ne l'avait pas
--   grant usage, select, update on sequence public.riddles_riddle_number_seq to anon;
--   grant execute on function
--     public.add_student_to_class_chat(),
--     public.assign_curriculum_point_code(),
--     public.audit_trigger_func(),
--     public.auto_log_template_changes(),
--     public.award_gidouilles_on_victory(),
--     public.calculate_3bv(jsonb),
--     public.calculate_elo_change(integer,integer),
--     public.calculate_minesweeper_points(text,integer,integer,uuid),
--     public.calculate_riddle_gidouilles(integer,integer),
--     public.calculate_tournament_score(integer,integer,text,text),
--     public.calculate_week_boundaries(date,integer),
--     public.calculate_worksheet_total_points(uuid),
--     public.check_expired_items(),
--     public.check_max_attachments(),
--     public.check_max_attempts(),
--     public.check_profanity_simple(text),
--     public.check_python_files_limit(),
--     public.check_python_notebooks_limit(),
--     public.cleanup_kanban_assignees_on_class_leave(),
--     public.create_class_chat_room(),
--     public.create_error_report_notification(),
--     public.create_game_profile_for_new_user(),
--     public.create_initial_template_version(),
--     public.delete_exercise_images(),
--     public.enforce_kanban_tags_per_board_cap(),
--     public.enforce_single_teacher(),
--     public.ensure_single_active_deck(),
--     public.exercise_has_multiple_variations(uuid),
--     public.exercise_variation_count(uuid),
--     public.exercises_search_vector(text,text,text,text[]),
--     public.extract_plain_text_from_tiptap(jsonb),
--     public.generate_error_signature(text,text,text,integer),
--     public.generate_join_code(),
--     public.generate_reward_event_description(reward_type,reward_event_type,numeric,text,jsonb),
--     public.generate_reward_event_description(text,text,numeric),
--     public.generate_share_token(),
--     public.generate_variant_seed(uuid,uuid,integer),
--     public.get_accessible_kanban_boards(integer,timestamp with time zone),
--     public.get_cycle_for_grade(text),
--     public.get_minesweeper_reference_time(text,text),
--     public.guard_profile_role_change(),
--     public.handle_new_user(),
--     public.handle_teacher_overrides_updated_at(),
--     public.increment_proposal_count(),
--     public.increment_stats_change_counter(),
--     public.increment_template_instantiation_count(),
--     public.increment_tutor_message_count(),
--     public.is_exercise_parameterized(uuid),
--     public.is_valid_grade_array(text[]),
--     public.log_achievements_to_events(),
--     public.log_bonus_history_to_events(),
--     public.log_gidouilles_activity_to_events(),
--     public.log_vip_card_changes(),
--     public.log_vip_cards_to_events(),
--     public.log_warning_added_to_events(),
--     public.log_warning_removed_to_events(),
--     public.mark_checkpoint_hint_revealed(uuid,text),
--     public.normalize_grade_array(text[]),
--     public.normalize_grade_value(text),
--     public.orphan_chapter_documents(),
--     public.place_curriculum_objective_last(),
--     public.place_curriculum_point_last(),
--     public.place_curriculum_theme_last(),
--     public.populate_shared_coursework_names(),
--     public.populate_shared_material_names(),
--     public.prevent_worksheet_instance_tampering(),
--     public.process_message_content(),
--     public.purge_pending_student_on_activation(),
--     public.rag_hybrid_search(text,vector,text[],text[],integer,double precision,double precision),
--     public.rate_limit_submissions(),
--     public.reorder_curriculum_objectives(uuid,uuid[]),
--     public.reorder_curriculum_points(uuid,uuid[]),
--     public.reorder_curriculum_themes(text,uuid[]),
--     public.save_template_version(),
--     public.set_checklist_completed_at_insert(),
--     public.set_checklist_completed_at(),
--     public.set_error_signature(),
--     public.set_listing_expiry(),
--     public.set_minesweeper_started_at(),
--     public.set_offer_number(),
--     public.set_submission_attempt_number(),
--     public.set_trade_validation_timestamp(),
--     public.skill_attempts_after_insert(),
--     public.sync_class_members_to_class_ids(),
--     public.trg_minesweeper_tournaments_updated_at(),
--     public.update_challenge_statistics(),
--     public.update_completion_last_viewed(),
--     public.update_constructions_updated_at(),
--     public.update_conversation_last_message(),
--     public.update_coursework_categories_updated_at(),
--     public.update_daily_summaries_updated_at(),
--     public.update_error_occurrence(),
--     public.update_exercises_updated_at(),
--     public.update_folder_message_count(),
--     public.update_friendships_updated_at(),
--     public.update_game_player_last_played(),
--     public.update_google_classroom_courses_updated_at(),
--     public.update_google_classroom_coursework_updated_at(),
--     public.update_google_classroom_materials_updated_at(),
--     public.update_google_classroom_topics_updated_at(),
--     public.update_google_integrations_updated_at(),
--     public.update_message_drafts_updated_at(),
--     public.update_message_search_index(),
--     public.update_message_template_updated_at(),
--     public.update_migration_tracking_updated_at(),
--     public.update_parental_consents_updated_at(),
--     public.update_parody_evaluations_updated_at(),
--     public.update_pem_updated_at(),
--     public.update_player_combat_stats(),
--     public.update_python_files_updated_at(),
--     public.update_python_mastery_on_submission(),
--     public.update_python_notebooks_updated_at(),
--     public.update_rag_documents_updated_at(),
--     public.update_riddles_updated_at(),
--     public.update_search_index_on_attachment(),
--     public.update_shared_coursework_on_course_rename(),
--     public.update_shared_coursework_on_teacher_rename(),
--     public.update_shared_coursework_updated_at(),
--     public.update_shared_material_course_name(),
--     public.update_shared_material_teacher_name(),
--     public.update_shared_materials_updated_at(),
--     public.update_spreadsheets_updated_at(),
--     public.update_student_buddies_updated_at(),
--     public.update_student_exercise_mastery_updated_at(),
--     public.update_student_progress_after_attempt(),
--     public.update_templates_updated_at(),
--     public.update_tutor_conversation_updated_at(),
--     public.update_updated_at_column(),
--     public.update_user_folders_updated_at(),
--     public.update_user_presence_updated_at(),
--     public.update_user_restrictions_updated_at(),
--     public.update_vip_cards_history(),
--     public.update_weekly_best_rewards_timestamp(),
--     public.update_whiteboard_template_updated_at(),
--     public.upsert_checkpoint_run(uuid,text,text,text),
--     public.upsert_error_occurrence(text,uuid,text,text,text,text,text,integer),
--     public.validate_locked_entity_reference(),
--     public.validate_minesweeper_win(jsonb,text)
--     to public, anon;
--   -- ces 5-là n'avaient pas d'entrée anon explicite (seulement PUBLIC) :
--   grant execute on function
--     public.cleanup_kanban_assignees_on_move(),
--     public.friendships_freeze_parties(),
--     public.guard_profile_role_on_insert(),
--     public.set_class_member_left_at(),
--     public.sync_class_chat_membership()
--     to public;
--

-- 1. Relations (141 tables et vues, 1 vue matérialisée, 1 séquence)

revoke all on table
	public.account_deletion_audit,
	public.achievement_events,
	public.achievement_migrations,
	public.app_config,
	public.audit_logs,
	public.background_job_runs,
	public.bonus_history,
	public.buddy_skins,
	public.bug_reports,
	public.bug_reports_config,
	public.chapter_template_instantiations,
	public.chapter_template_versions,
	public.chapter_templates,
	public.class_chapters,
	public.class_google_classroom_links,
	public.class_members,
	public.classes,
	public.coursework_categories,
	public.coursework_materials,
	public.curriculum_objectives,
	public.curriculum_point_automatismes,
	public.curriculum_points,
	public.curriculum_themes,
	public.daily_summaries,
	public.evaluation_task_perimeter,
	public.evaluation_tasks,
	public.exercise_curriculum_points,
	public.exercise_favorites,
	public.exercise_templates,
	public.game_2048_scores,
	public.game_class_settings,
	public.gidouilles_activity,
	public.google_classroom_courses,
	public.google_classroom_coursework,
	public.google_classroom_material_attachments,
	public.google_classroom_materials,
	public.google_classroom_topics,
	public.google_integrations,
	public.journal_entry_activities,
	public.journal_entry_points,
	public.kanban_boards,
	public.kanban_card_assignees,
	public.kanban_card_tags,
	public.kanban_cards,
	public.kanban_columns,
	public.kanban_tags,
	public.marketplace_chat_messages,
	public.marketplace_config,
	public.marketplace_listing_views,
	public.marketplace_listings,
	public.marketplace_locked_cards,
	public.marketplace_proposals,
	public.marketplace_trade_offers,
	public.marketplace_trades,
	public.math_competence_subdimensions,
	public.math_competences,
	public.mathemo_scores,
	public.message_template_versions,
	public.message_templates,
	public.migration_edits,
	public.migration_images,
	public.migration_tracking,
	public.minesweeper_multiplayer_game_state,
	public.minesweeper_multiplayer_matches,
	public.minesweeper_multiplayer_queue,
	public.minesweeper_player_stats,
	public.minesweeper_reference_times_history,
	public.minesweeper_student_achievements,
	public.minesweeper_tournament_classes,
	public.minesweeper_tournament_games,
	public.minesweeper_tournaments,
	public.observables,
	public.orphaned_documents,
	public.python_exercise_assignments,
	public.python_exercise_mastery,
	public.python_exercise_submissions,
	public.python_submission_server_verdicts,
	public.question_template_points,
	public.rag_chunks,
	public.rag_documents,
	public.reward_events,
	public.school_year_closures,
	public.server_cache,
	public.shared_coursework,
	public.shared_coursework_students,
	public.shared_materials,
	public.skill_attempts,
	public.srs_anti_fraud_flags,
	public.srs_deck_sections,
	public.student_buddies,
	public.student_checklist_progress,
	public.student_competence_level,
	public.student_observable_state,
	public.student_point_state,
	public.student_warnings,
	public.template_audit_log,
	public.template_usage_stats,
	public.terms_acceptances,
	public.tutor_conversations,
	public.tutor_messages,
	public.user_favorite_templates,
	public.user_preferences,
	public.user_whiteboard_template_favorites,
	public.vip_card_config,
	public.vip_card_templates,
	public.vip_cards_activity,
	public.weekly_rewards,
	public.whiteboard_export_counters,
	public.whiteboard_templates,
	public.worksheet_assignment_classes,
	public.worksheet_assignment_exercise_settings,
	public.worksheet_assignment_students,
	public.worksheet_assignments,
	public.worksheet_error_reports,
	public.worksheet_exercises,
	public.worksheet_instances,
	public.worksheet_sections,
	public.worksheet_templates,
	public.worksheets,
	public.active_student_warnings,
	public.admin_error_stats_24h,
	public.admin_job_failures,
	public.admin_job_status,
	public.admin_online_users,
	public.admin_pg_cron_jobs,
	public.admin_user_activity,
	public.deck_stats_view,
	public.game_scores_unified,
	public.migration_review_tree,
	public.minesweeper_achievements_compat,
	public.minesweeper_leaderboard,
	public.minesweeper_multiplayer_leaderboard,
	public.minesweeper_student_achievement_progress,
	public.minesweeper_student_achievements_compat,
	public.minesweeper_tournament_standings,
	public.riddle_progress,
	public.riddle_stats,
	public.riddle_student_history,
	public.student_coursework_view,
	public.student_point_state_v,
	public.user_conversations_view
from anon;

revoke all on table public.student_achievement_stats from anon;

revoke all on sequence public.riddles_riddle_number_seq from anon;

-- 2. Fonctions (143) : GRANT explicite d'abord (aucun effet en prod, où
--    authenticated et service_role l'ont déjà ; garantit qu'ils ne dépendent pas
--    de PUBLIC), puis retrait de PUBLIC et de anon.

grant execute on function
	public.add_student_to_class_chat(),
	public.assign_curriculum_point_code(),
	public.audit_trigger_func(),
	public.auto_log_template_changes(),
	public.award_gidouilles_on_victory(),
	public.calculate_3bv(jsonb),
	public.calculate_elo_change(integer,integer),
	public.calculate_minesweeper_points(text,integer,integer,uuid),
	public.calculate_riddle_gidouilles(integer,integer),
	public.calculate_tournament_score(integer,integer,text,text),
	public.calculate_week_boundaries(date,integer),
	public.calculate_worksheet_total_points(uuid),
	public.check_expired_items(),
	public.check_max_attachments(),
	public.check_max_attempts(),
	public.check_profanity_simple(text),
	public.check_python_files_limit(),
	public.check_python_notebooks_limit(),
	public.cleanup_kanban_assignees_on_class_leave(),
	public.cleanup_kanban_assignees_on_move(),
	public.create_class_chat_room(),
	public.create_error_report_notification(),
	public.create_game_profile_for_new_user(),
	public.create_initial_template_version(),
	public.delete_exercise_images(),
	public.enforce_kanban_tags_per_board_cap(),
	public.enforce_single_teacher(),
	public.ensure_single_active_deck(),
	public.exercise_has_multiple_variations(uuid),
	public.exercise_variation_count(uuid),
	public.exercises_search_vector(text,text,text,text[]),
	public.extract_plain_text_from_tiptap(jsonb),
	public.friendships_freeze_parties(),
	public.generate_error_signature(text,text,text,integer),
	public.generate_join_code(),
	public.generate_reward_event_description(reward_type,reward_event_type,numeric,text,jsonb),
	public.generate_reward_event_description(text,text,numeric),
	public.generate_share_token(),
	public.generate_variant_seed(uuid,uuid,integer),
	public.get_accessible_kanban_boards(integer,timestamp with time zone),
	public.get_cycle_for_grade(text),
	public.get_minesweeper_reference_time(text,text),
	public.guard_profile_role_change(),
	public.guard_profile_role_on_insert(),
	public.handle_new_user(),
	public.handle_teacher_overrides_updated_at(),
	public.increment_proposal_count(),
	public.increment_stats_change_counter(),
	public.increment_template_instantiation_count(),
	public.increment_tutor_message_count(),
	public.is_exercise_parameterized(uuid),
	public.is_valid_grade_array(text[]),
	public.log_achievements_to_events(),
	public.log_bonus_history_to_events(),
	public.log_gidouilles_activity_to_events(),
	public.log_vip_card_changes(),
	public.log_vip_cards_to_events(),
	public.log_warning_added_to_events(),
	public.log_warning_removed_to_events(),
	public.mark_checkpoint_hint_revealed(uuid,text),
	public.normalize_grade_array(text[]),
	public.normalize_grade_value(text),
	public.orphan_chapter_documents(),
	public.place_curriculum_objective_last(),
	public.place_curriculum_point_last(),
	public.place_curriculum_theme_last(),
	public.populate_shared_coursework_names(),
	public.populate_shared_material_names(),
	public.prevent_worksheet_instance_tampering(),
	public.process_message_content(),
	public.purge_pending_student_on_activation(),
	public.rag_hybrid_search(text,vector,text[],text[],integer,double precision,double precision),
	public.rate_limit_submissions(),
	public.reorder_curriculum_objectives(uuid,uuid[]),
	public.reorder_curriculum_points(uuid,uuid[]),
	public.reorder_curriculum_themes(text,uuid[]),
	public.save_template_version(),
	public.set_checklist_completed_at_insert(),
	public.set_checklist_completed_at(),
	public.set_class_member_left_at(),
	public.set_error_signature(),
	public.set_listing_expiry(),
	public.set_minesweeper_started_at(),
	public.set_offer_number(),
	public.set_submission_attempt_number(),
	public.set_trade_validation_timestamp(),
	public.skill_attempts_after_insert(),
	public.sync_class_chat_membership(),
	public.sync_class_members_to_class_ids(),
	public.trg_minesweeper_tournaments_updated_at(),
	public.update_challenge_statistics(),
	public.update_completion_last_viewed(),
	public.update_constructions_updated_at(),
	public.update_conversation_last_message(),
	public.update_coursework_categories_updated_at(),
	public.update_daily_summaries_updated_at(),
	public.update_error_occurrence(),
	public.update_exercises_updated_at(),
	public.update_folder_message_count(),
	public.update_friendships_updated_at(),
	public.update_game_player_last_played(),
	public.update_google_classroom_courses_updated_at(),
	public.update_google_classroom_coursework_updated_at(),
	public.update_google_classroom_materials_updated_at(),
	public.update_google_classroom_topics_updated_at(),
	public.update_google_integrations_updated_at(),
	public.update_message_drafts_updated_at(),
	public.update_message_search_index(),
	public.update_message_template_updated_at(),
	public.update_migration_tracking_updated_at(),
	public.update_parental_consents_updated_at(),
	public.update_parody_evaluations_updated_at(),
	public.update_pem_updated_at(),
	public.update_player_combat_stats(),
	public.update_python_files_updated_at(),
	public.update_python_mastery_on_submission(),
	public.update_python_notebooks_updated_at(),
	public.update_rag_documents_updated_at(),
	public.update_riddles_updated_at(),
	public.update_search_index_on_attachment(),
	public.update_shared_coursework_on_course_rename(),
	public.update_shared_coursework_on_teacher_rename(),
	public.update_shared_coursework_updated_at(),
	public.update_shared_material_course_name(),
	public.update_shared_material_teacher_name(),
	public.update_shared_materials_updated_at(),
	public.update_spreadsheets_updated_at(),
	public.update_student_buddies_updated_at(),
	public.update_student_exercise_mastery_updated_at(),
	public.update_student_progress_after_attempt(),
	public.update_templates_updated_at(),
	public.update_tutor_conversation_updated_at(),
	public.update_updated_at_column(),
	public.update_user_folders_updated_at(),
	public.update_user_presence_updated_at(),
	public.update_user_restrictions_updated_at(),
	public.update_vip_cards_history(),
	public.update_weekly_best_rewards_timestamp(),
	public.update_whiteboard_template_updated_at(),
	public.upsert_checkpoint_run(uuid,text,text,text),
	public.upsert_error_occurrence(text,uuid,text,text,text,text,text,integer),
	public.validate_locked_entity_reference(),
	public.validate_minesweeper_win(jsonb,text)
to authenticated, service_role;

revoke execute on function
	public.add_student_to_class_chat(),
	public.assign_curriculum_point_code(),
	public.audit_trigger_func(),
	public.auto_log_template_changes(),
	public.award_gidouilles_on_victory(),
	public.calculate_3bv(jsonb),
	public.calculate_elo_change(integer,integer),
	public.calculate_minesweeper_points(text,integer,integer,uuid),
	public.calculate_riddle_gidouilles(integer,integer),
	public.calculate_tournament_score(integer,integer,text,text),
	public.calculate_week_boundaries(date,integer),
	public.calculate_worksheet_total_points(uuid),
	public.check_expired_items(),
	public.check_max_attachments(),
	public.check_max_attempts(),
	public.check_profanity_simple(text),
	public.check_python_files_limit(),
	public.check_python_notebooks_limit(),
	public.cleanup_kanban_assignees_on_class_leave(),
	public.cleanup_kanban_assignees_on_move(),
	public.create_class_chat_room(),
	public.create_error_report_notification(),
	public.create_game_profile_for_new_user(),
	public.create_initial_template_version(),
	public.delete_exercise_images(),
	public.enforce_kanban_tags_per_board_cap(),
	public.enforce_single_teacher(),
	public.ensure_single_active_deck(),
	public.exercise_has_multiple_variations(uuid),
	public.exercise_variation_count(uuid),
	public.exercises_search_vector(text,text,text,text[]),
	public.extract_plain_text_from_tiptap(jsonb),
	public.friendships_freeze_parties(),
	public.generate_error_signature(text,text,text,integer),
	public.generate_join_code(),
	public.generate_reward_event_description(reward_type,reward_event_type,numeric,text,jsonb),
	public.generate_reward_event_description(text,text,numeric),
	public.generate_share_token(),
	public.generate_variant_seed(uuid,uuid,integer),
	public.get_accessible_kanban_boards(integer,timestamp with time zone),
	public.get_cycle_for_grade(text),
	public.get_minesweeper_reference_time(text,text),
	public.guard_profile_role_change(),
	public.guard_profile_role_on_insert(),
	public.handle_new_user(),
	public.handle_teacher_overrides_updated_at(),
	public.increment_proposal_count(),
	public.increment_stats_change_counter(),
	public.increment_template_instantiation_count(),
	public.increment_tutor_message_count(),
	public.is_exercise_parameterized(uuid),
	public.is_valid_grade_array(text[]),
	public.log_achievements_to_events(),
	public.log_bonus_history_to_events(),
	public.log_gidouilles_activity_to_events(),
	public.log_vip_card_changes(),
	public.log_vip_cards_to_events(),
	public.log_warning_added_to_events(),
	public.log_warning_removed_to_events(),
	public.mark_checkpoint_hint_revealed(uuid,text),
	public.normalize_grade_array(text[]),
	public.normalize_grade_value(text),
	public.orphan_chapter_documents(),
	public.place_curriculum_objective_last(),
	public.place_curriculum_point_last(),
	public.place_curriculum_theme_last(),
	public.populate_shared_coursework_names(),
	public.populate_shared_material_names(),
	public.prevent_worksheet_instance_tampering(),
	public.process_message_content(),
	public.purge_pending_student_on_activation(),
	public.rag_hybrid_search(text,vector,text[],text[],integer,double precision,double precision),
	public.rate_limit_submissions(),
	public.reorder_curriculum_objectives(uuid,uuid[]),
	public.reorder_curriculum_points(uuid,uuid[]),
	public.reorder_curriculum_themes(text,uuid[]),
	public.save_template_version(),
	public.set_checklist_completed_at_insert(),
	public.set_checklist_completed_at(),
	public.set_class_member_left_at(),
	public.set_error_signature(),
	public.set_listing_expiry(),
	public.set_minesweeper_started_at(),
	public.set_offer_number(),
	public.set_submission_attempt_number(),
	public.set_trade_validation_timestamp(),
	public.skill_attempts_after_insert(),
	public.sync_class_chat_membership(),
	public.sync_class_members_to_class_ids(),
	public.trg_minesweeper_tournaments_updated_at(),
	public.update_challenge_statistics(),
	public.update_completion_last_viewed(),
	public.update_constructions_updated_at(),
	public.update_conversation_last_message(),
	public.update_coursework_categories_updated_at(),
	public.update_daily_summaries_updated_at(),
	public.update_error_occurrence(),
	public.update_exercises_updated_at(),
	public.update_folder_message_count(),
	public.update_friendships_updated_at(),
	public.update_game_player_last_played(),
	public.update_google_classroom_courses_updated_at(),
	public.update_google_classroom_coursework_updated_at(),
	public.update_google_classroom_materials_updated_at(),
	public.update_google_classroom_topics_updated_at(),
	public.update_google_integrations_updated_at(),
	public.update_message_drafts_updated_at(),
	public.update_message_search_index(),
	public.update_message_template_updated_at(),
	public.update_migration_tracking_updated_at(),
	public.update_parental_consents_updated_at(),
	public.update_parody_evaluations_updated_at(),
	public.update_pem_updated_at(),
	public.update_player_combat_stats(),
	public.update_python_files_updated_at(),
	public.update_python_mastery_on_submission(),
	public.update_python_notebooks_updated_at(),
	public.update_rag_documents_updated_at(),
	public.update_riddles_updated_at(),
	public.update_search_index_on_attachment(),
	public.update_shared_coursework_on_course_rename(),
	public.update_shared_coursework_on_teacher_rename(),
	public.update_shared_coursework_updated_at(),
	public.update_shared_material_course_name(),
	public.update_shared_material_teacher_name(),
	public.update_shared_materials_updated_at(),
	public.update_spreadsheets_updated_at(),
	public.update_student_buddies_updated_at(),
	public.update_student_exercise_mastery_updated_at(),
	public.update_student_progress_after_attempt(),
	public.update_templates_updated_at(),
	public.update_tutor_conversation_updated_at(),
	public.update_updated_at_column(),
	public.update_user_folders_updated_at(),
	public.update_user_presence_updated_at(),
	public.update_user_restrictions_updated_at(),
	public.update_vip_cards_history(),
	public.update_weekly_best_rewards_timestamp(),
	public.update_whiteboard_template_updated_at(),
	public.upsert_checkpoint_run(uuid,text,text,text),
	public.upsert_error_occurrence(text,uuid,text,text,text,text,text,integer),
	public.validate_locked_entity_reference(),
	public.validate_minesweeper_win(jsonb,text)
from public, anon;

-- 3. Garde explicite : les 4 RPC appelées SANS connexion (pages publiques).
--    Déjà accordées en prod ; répété pour que l'intention soit lisible ici.

grant execute on function
	public.get_consent_info(uuid),
	public.get_worksheet_by_share_token(text, uuid),
	public.get_class_journal_by_share_token(text),
	public.get_exercise_by_share_token(text)
to anon;
