-- ============================================================================
-- Seed des points de programme de la 6e (programme de cycle 3, BOENJS du
-- 17 avril 2025) + RÉFÉRENCES d'automatismes vers les points CM et cycle 2.
-- ============================================================================
-- Source de vérité : docs/wip/arbre-notions/seed-6e.md (VALIDÉ par David le
-- 2026-10-08, A1-A4) ; fichier GÉNÉRÉ — ne pas éditer à la main. 97 points
-- (95 « Connaissances et capacités attendues » + 2 lignes d'Automatismes au
-- contenu neuf, en fluence), codes 6-101…6-197 (l'ancien seed 2020 garde
-- 6-001…6-095 jusqu'à l'étape 4 de C5 ; l'index d'unicité des codes est
-- global). Premier grade à références : 28 points CM1/CM2/CE1/CE2 référencés
-- dans curriculum_point_automatismes (grade '6') — le trigger de parcours
-- (C14) valide chaque cible, zéro ligne silencieuse impossible (bloc DO).
-- AUCUN changement de l'arbre (2026-10-07.13) ni des policies.
--
-- MIGRATION ADDITIVE (données seulement). Rollback :
--   delete from public.curriculum_point_automatismes where grade = '6';
--   delete from public.curriculum_points where code like '6-1%';
-- ⚠️ Ce rollback n'est anodin que tant qu'AUCUN usage ne s'accroche à ces
-- points : des tables de suivi élève référencent curriculum_points en ON
-- DELETE CASCADE. Dès qu'un élève ou un modèle y est rattaché, ce delete
-- devient DESTRUCTIF (données d'élèves mineurs) : arrêt obligatoire et accord
-- explicite de David (règle CLAUDE.md). Il emporterait AUSSI, en cascade et
-- sans message, les références d'automatismes d'AUTRES grades (5e…) qui
-- viseraient ces points 6-1xx.
-- ============================================================================

-- ---- 1. Les 97 points -------------------------------------------------------
insert into public.curriculum_points (code, name, kind, exigence, regime_acquisition, rubrique, grade, display_order, node_id)
values ($pt$6-101$pt$, $pt$Connaître et utiliser la valeur des chiffres selon leur rang dans l'écriture d'un nombre$pt$, 'savoir_faire', 'attendu', 'diversite', $pt$Nombres, calcul et résolution de problèmes > Les nombres entiers et décimaux$pt$, '6', 1, (select id from public.classification_nodes where kind = 'subnotion' and name = $pt$décomposer$pt$ and parent_id = (select id from public.classification_nodes where kind = 'notion' and name = $pt$Entiers : numération$pt$ and parent_id = (select id from public.classification_nodes where kind = 'branch' and name = $pt$Nombres et calculs$pt$))));
insert into public.curriculum_points (code, name, kind, exigence, regime_acquisition, rubrique, grade, display_order, node_id)
values ($pt$6-102$pt$, $pt$Connaître les liens entre les unités de numération unité, dizaine, centaine, millier, dixième, centième, millième$pt$, 'connaissance', 'attendu', 'diversite', $pt$Nombres, calcul et résolution de problèmes > Les nombres entiers et décimaux$pt$, '6', 2, (select id from public.classification_nodes where kind = 'subnotion' and name = $pt$décomposer$pt$ and parent_id = (select id from public.classification_nodes where kind = 'notion' and name = $pt$Décimaux : numération$pt$ and parent_id = (select id from public.classification_nodes where kind = 'branch' and name = $pt$Nombres et calculs$pt$))));
insert into public.curriculum_points (code, name, kind, exigence, regime_acquisition, rubrique, grade, display_order, node_id)
values ($pt$6-103$pt$, $pt$Connaître des grands nombres entiers$pt$, 'connaissance', 'attendu', 'diversite', $pt$Nombres, calcul et résolution de problèmes > Les nombres entiers et décimaux$pt$, '6', 3, (select id from public.classification_nodes where kind = 'subnotion' and name = $pt$écrire$pt$ and parent_id = (select id from public.classification_nodes where kind = 'notion' and name = $pt$Entiers : numération$pt$ and parent_id = (select id from public.classification_nodes where kind = 'branch' and name = $pt$Nombres et calculs$pt$))));
insert into public.curriculum_points (code, name, kind, exigence, regime_acquisition, rubrique, grade, display_order, node_id)
values ($pt$6-104$pt$, $pt$Reconnaître un nombre décimal$pt$, 'savoir_faire', 'attendu', 'diversite', $pt$Nombres, calcul et résolution de problèmes > Les nombres entiers et décimaux$pt$, '6', 4, (select id from public.classification_nodes where kind = 'notion' and name = $pt$Décimaux : numération$pt$ and parent_id = (select id from public.classification_nodes where kind = 'branch' and name = $pt$Nombres et calculs$pt$)));
insert into public.curriculum_points (code, name, kind, exigence, regime_acquisition, rubrique, grade, display_order, node_id)
values ($pt$6-105$pt$, $pt$Connaître la définition d'un pourcentage$pt$, 'connaissance', 'attendu', 'diversite', $pt$Nombres, calcul et résolution de problèmes > Les nombres entiers et décimaux$pt$, '6', 5, (select id from public.classification_nodes where kind = 'subnotion' and name = $pt$définition$pt$ and parent_id = (select id from public.classification_nodes where kind = 'notion' and name = $pt$Pourcentages$pt$ and parent_id = (select id from public.classification_nodes where kind = 'branch' and name = $pt$Proportionnalité$pt$))));
insert into public.curriculum_points (code, name, kind, exigence, regime_acquisition, rubrique, grade, display_order, node_id)
values ($pt$6-106$pt$, $pt$Associer et utiliser différentes écritures d'un nombre décimal : écriture à virgule, fraction, nombre mixte, pourcentage$pt$, 'savoir_faire', 'attendu', 'diversite', $pt$Nombres, calcul et résolution de problèmes > Les nombres entiers et décimaux$pt$, '6', 6, (select id from public.classification_nodes where kind = 'notion' and name = $pt$Décimaux : numération$pt$ and parent_id = (select id from public.classification_nodes where kind = 'branch' and name = $pt$Nombres et calculs$pt$)));
insert into public.curriculum_points (code, name, kind, exigence, regime_acquisition, rubrique, grade, display_order, node_id)
values ($pt$6-107$pt$, $pt$Placer sur une demi-droite graduée un point dont l'abscisse est un nombre décimal$pt$, 'savoir_faire', 'attendu', 'diversite', $pt$Nombres, calcul et résolution de problèmes > Les nombres entiers et décimaux$pt$, '6', 7, (select id from public.classification_nodes where kind = 'subnotion' and name = $pt$droite graduée$pt$ and parent_id = (select id from public.classification_nodes where kind = 'notion' and name = $pt$Décimaux : numération$pt$ and parent_id = (select id from public.classification_nodes where kind = 'branch' and name = $pt$Nombres et calculs$pt$))));
insert into public.curriculum_points (code, name, kind, exigence, regime_acquisition, rubrique, grade, display_order, node_id)
values ($pt$6-108$pt$, $pt$Repérer un nombre décimal sur une demi-droite graduée$pt$, 'savoir_faire', 'attendu', 'diversite', $pt$Nombres, calcul et résolution de problèmes > Les nombres entiers et décimaux$pt$, '6', 8, (select id from public.classification_nodes where kind = 'subnotion' and name = $pt$droite graduée$pt$ and parent_id = (select id from public.classification_nodes where kind = 'notion' and name = $pt$Décimaux : numération$pt$ and parent_id = (select id from public.classification_nodes where kind = 'branch' and name = $pt$Nombres et calculs$pt$))));
insert into public.curriculum_points (code, name, kind, exigence, regime_acquisition, rubrique, grade, display_order, node_id)
values ($pt$6-109$pt$, $pt$Comparer deux nombres décimaux$pt$, 'savoir_faire', 'attendu', 'diversite', $pt$Nombres, calcul et résolution de problèmes > Les nombres entiers et décimaux$pt$, '6', 9, (select id from public.classification_nodes where kind = 'subnotion' and name = $pt$comparer$pt$ and parent_id = (select id from public.classification_nodes where kind = 'notion' and name = $pt$Décimaux : numération$pt$ and parent_id = (select id from public.classification_nodes where kind = 'branch' and name = $pt$Nombres et calculs$pt$))));
insert into public.curriculum_points (code, name, kind, exigence, regime_acquisition, rubrique, grade, display_order, node_id)
values ($pt$6-110$pt$, $pt$Ordonner une liste de nombres décimaux$pt$, 'savoir_faire', 'attendu', 'diversite', $pt$Nombres, calcul et résolution de problèmes > Les nombres entiers et décimaux$pt$, '6', 10, (select id from public.classification_nodes where kind = 'subnotion' and name = $pt$comparer$pt$ and parent_id = (select id from public.classification_nodes where kind = 'notion' and name = $pt$Décimaux : numération$pt$ and parent_id = (select id from public.classification_nodes where kind = 'branch' and name = $pt$Nombres et calculs$pt$))));
insert into public.curriculum_points (code, name, kind, exigence, regime_acquisition, rubrique, grade, display_order, node_id)
values ($pt$6-111$pt$, $pt$Donner la valeur arrondie à l'unité, au dixième ou au centième, d'un nombre décimal$pt$, 'savoir_faire', 'attendu', 'diversite', $pt$Nombres, calcul et résolution de problèmes > Les nombres entiers et décimaux$pt$, '6', 11, (select id from public.classification_nodes where kind = 'subnotion' and name = $pt$arrondis et ordres de grandeur$pt$ and parent_id = (select id from public.classification_nodes where kind = 'notion' and name = $pt$Décimaux : numération$pt$ and parent_id = (select id from public.classification_nodes where kind = 'branch' and name = $pt$Nombres et calculs$pt$))));
insert into public.curriculum_points (code, name, kind, exigence, regime_acquisition, rubrique, grade, display_order, node_id)
values ($pt$6-112$pt$, $pt$Déterminer ou connaître la valeur arrondie de certains nombres non décimaux$pt$, 'savoir_faire', 'attendu', 'diversite', $pt$Nombres, calcul et résolution de problèmes > Les nombres entiers et décimaux$pt$, '6', 12, (select id from public.classification_nodes where kind = 'subnotion' and name = $pt$arrondis et ordres de grandeur$pt$ and parent_id = (select id from public.classification_nodes where kind = 'notion' and name = $pt$Décimaux : numération$pt$ and parent_id = (select id from public.classification_nodes where kind = 'branch' and name = $pt$Nombres et calculs$pt$))));
insert into public.curriculum_points (code, name, kind, exigence, regime_acquisition, rubrique, grade, display_order, node_id)
values ($pt$6-113$pt$, $pt$Encadrer un nombre décimal par deux nombres décimaux, intercaler un nombre décimal entre deux nombres décimaux$pt$, 'savoir_faire', 'attendu', 'diversite', $pt$Nombres, calcul et résolution de problèmes > Les nombres entiers et décimaux$pt$, '6', 13, (select id from public.classification_nodes where kind = 'subnotion' and name = $pt$encadrer$pt$ and parent_id = (select id from public.classification_nodes where kind = 'notion' and name = $pt$Décimaux : numération$pt$ and parent_id = (select id from public.classification_nodes where kind = 'branch' and name = $pt$Nombres et calculs$pt$))));
insert into public.curriculum_points (code, name, kind, exigence, regime_acquisition, rubrique, grade, display_order, node_id)
values ($pt$6-114$pt$, $pt$Additionner et soustraire des nombres décimaux$pt$, 'savoir_faire', 'attendu', 'diversite', $pt$Nombres, calcul et résolution de problèmes > Les nombres entiers et décimaux$pt$, '6', 14, (select id from public.classification_nodes where kind = 'notion' and name = $pt$Décimaux : calculs$pt$ and parent_id = (select id from public.classification_nodes where kind = 'branch' and name = $pt$Nombres et calculs$pt$)));
insert into public.curriculum_points (code, name, kind, exigence, regime_acquisition, rubrique, grade, display_order, node_id)
values ($pt$6-115$pt$, $pt$Multiplier un nombre entier ou un nombre décimal par 0,1, par 0,01, et par 0,001$pt$, 'savoir_faire', 'attendu', 'diversite', $pt$Nombres, calcul et résolution de problèmes > Les nombres entiers et décimaux$pt$, '6', 15, (select id from public.classification_nodes where kind = 'subnotion' and name = $pt$puissances de 10$pt$ and parent_id = (select id from public.classification_nodes where kind = 'notion' and name = $pt$Décimaux : calculs$pt$ and parent_id = (select id from public.classification_nodes where kind = 'branch' and name = $pt$Nombres et calculs$pt$))));
insert into public.curriculum_points (code, name, kind, exigence, regime_acquisition, rubrique, grade, display_order, node_id)
values ($pt$6-116$pt$, $pt$Connaître le lien avec la division par 10, 100 et par 1 000$pt$, 'connaissance', 'attendu', 'diversite', $pt$Nombres, calcul et résolution de problèmes > Les nombres entiers et décimaux$pt$, '6', 16, (select id from public.classification_nodes where kind = 'subnotion' and name = $pt$puissances de 10$pt$ and parent_id = (select id from public.classification_nodes where kind = 'notion' and name = $pt$Décimaux : calculs$pt$ and parent_id = (select id from public.classification_nodes where kind = 'branch' and name = $pt$Nombres et calculs$pt$))));
insert into public.curriculum_points (code, name, kind, exigence, regime_acquisition, rubrique, grade, display_order, node_id)
values ($pt$6-117$pt$, $pt$Comprendre le sens de la multiplication de deux nombres décimaux$pt$, 'connaissance', 'attendu', 'diversite', $pt$Nombres, calcul et résolution de problèmes > Les nombres entiers et décimaux$pt$, '6', 17, (select id from public.classification_nodes where kind = 'subnotion' and name = $pt$multiplier$pt$ and parent_id = (select id from public.classification_nodes where kind = 'notion' and name = $pt$Décimaux : calculs$pt$ and parent_id = (select id from public.classification_nodes where kind = 'branch' and name = $pt$Nombres et calculs$pt$))));
insert into public.curriculum_points (code, name, kind, exigence, regime_acquisition, rubrique, grade, display_order, node_id)
values ($pt$6-118$pt$, $pt$Calculer le produit de deux nombres décimaux$pt$, 'savoir_faire', 'attendu', 'diversite', $pt$Nombres, calcul et résolution de problèmes > Les nombres entiers et décimaux$pt$, '6', 18, (select id from public.classification_nodes where kind = 'subnotion' and name = $pt$multiplier$pt$ and parent_id = (select id from public.classification_nodes where kind = 'notion' and name = $pt$Décimaux : calculs$pt$ and parent_id = (select id from public.classification_nodes where kind = 'branch' and name = $pt$Nombres et calculs$pt$))));
insert into public.curriculum_points (code, name, kind, exigence, regime_acquisition, rubrique, grade, display_order, node_id)
values ($pt$6-119$pt$, $pt$Contrôler les résultats à l'aide d'ordres de grandeur$pt$, 'savoir_faire', 'attendu', 'diversite', $pt$Nombres, calcul et résolution de problèmes > Les nombres entiers et décimaux$pt$, '6', 19, (select id from public.classification_nodes where kind = 'subnotion' and name = $pt$arrondis et ordres de grandeur$pt$ and parent_id = (select id from public.classification_nodes where kind = 'notion' and name = $pt$Décimaux : numération$pt$ and parent_id = (select id from public.classification_nodes where kind = 'branch' and name = $pt$Nombres et calculs$pt$))));
insert into public.curriculum_points (code, name, kind, exigence, regime_acquisition, rubrique, grade, display_order, node_id)
values ($pt$6-120$pt$, $pt$Résoudre des problèmes mettant en jeu des multiplications entre des nombres décimaux$pt$, 'savoir_faire', 'attendu', 'diversite', $pt$Nombres, calcul et résolution de problèmes > Les nombres entiers et décimaux$pt$, '6', 20, (select id from public.classification_nodes where kind = 'subnotion' and name = $pt$multiplier$pt$ and parent_id = (select id from public.classification_nodes where kind = 'notion' and name = $pt$Décimaux : calculs$pt$ and parent_id = (select id from public.classification_nodes where kind = 'branch' and name = $pt$Nombres et calculs$pt$))));
insert into public.curriculum_points (code, name, kind, exigence, regime_acquisition, rubrique, grade, display_order, node_id)
values ($pt$6-121$pt$, $pt$Diviser un nombre décimal par un nombre entier non nul inférieur à 10$pt$, 'savoir_faire', 'attendu', 'diversite', $pt$Nombres, calcul et résolution de problèmes > Les nombres entiers et décimaux$pt$, '6', 21, (select id from public.classification_nodes where kind = 'subnotion' and name = $pt$diviser$pt$ and parent_id = (select id from public.classification_nodes where kind = 'notion' and name = $pt$Décimaux : calculs$pt$ and parent_id = (select id from public.classification_nodes where kind = 'branch' and name = $pt$Nombres et calculs$pt$))));
insert into public.curriculum_points (code, name, kind, exigence, regime_acquisition, rubrique, grade, display_order, node_id)
values ($pt$6-122$pt$, $pt$Résoudre des problèmes mettant en jeu des divisions décimales$pt$, 'savoir_faire', 'attendu', 'diversite', $pt$Nombres, calcul et résolution de problèmes > Les nombres entiers et décimaux$pt$, '6', 22, (select id from public.classification_nodes where kind = 'subnotion' and name = $pt$diviser$pt$ and parent_id = (select id from public.classification_nodes where kind = 'notion' and name = $pt$Décimaux : calculs$pt$ and parent_id = (select id from public.classification_nodes where kind = 'branch' and name = $pt$Nombres et calculs$pt$))));
insert into public.curriculum_points (code, name, kind, exigence, regime_acquisition, rubrique, grade, display_order, node_id)
values ($pt$6-123$pt$, $pt$Effectuer la division euclidienne d'un nombre entier par un nombre entier inférieur à 100$pt$, 'savoir_faire', 'attendu', 'diversite', $pt$Nombres, calcul et résolution de problèmes > Les nombres entiers et décimaux$pt$, '6', 23, (select id from public.classification_nodes where kind = 'subnotion' and name = $pt$division euclidienne$pt$ and parent_id = (select id from public.classification_nodes where kind = 'notion' and name = $pt$Entiers : division$pt$ and parent_id = (select id from public.classification_nodes where kind = 'branch' and name = $pt$Nombres et calculs$pt$))));
insert into public.curriculum_points (code, name, kind, exigence, regime_acquisition, rubrique, grade, display_order, node_id)
values ($pt$6-124$pt$, $pt$Résoudre des problèmes mettant en jeu des divisions euclidiennes$pt$, 'savoir_faire', 'attendu', 'diversite', $pt$Nombres, calcul et résolution de problèmes > Les nombres entiers et décimaux$pt$, '6', 24, (select id from public.classification_nodes where kind = 'subnotion' and name = $pt$division euclidienne$pt$ and parent_id = (select id from public.classification_nodes where kind = 'notion' and name = $pt$Entiers : division$pt$ and parent_id = (select id from public.classification_nodes where kind = 'branch' and name = $pt$Nombres et calculs$pt$))));
insert into public.curriculum_points (code, name, kind, exigence, regime_acquisition, rubrique, grade, display_order, node_id)
values ($pt$6-125$pt$, $pt$Relier une fraction au résultat exact de la division de son numérateur par son dénominateur$pt$, 'savoir_faire', 'attendu', 'diversite', $pt$Nombres, calcul et résolution de problèmes > Les fractions$pt$, '6', 25, (select id from public.classification_nodes where kind = 'subnotion' and name = $pt$définition$pt$ and parent_id = (select id from public.classification_nodes where kind = 'notion' and name = $pt$Fractions : sens et écritures$pt$ and parent_id = (select id from public.classification_nodes where kind = 'branch' and name = $pt$Nombres et calculs$pt$))));
insert into public.curriculum_points (code, name, kind, exigence, regime_acquisition, rubrique, grade, display_order, node_id)
values ($pt$6-126$pt$, $pt$Comprendre et connaître la définition du quotient d'un entier a par un entier b non nul$pt$, 'connaissance', 'attendu', 'diversite', $pt$Nombres, calcul et résolution de problèmes > Les fractions$pt$, '6', 26, (select id from public.classification_nodes where kind = 'subnotion' and name = $pt$définition$pt$ and parent_id = (select id from public.classification_nodes where kind = 'notion' and name = $pt$Fractions : sens et écritures$pt$ and parent_id = (select id from public.classification_nodes where kind = 'branch' and name = $pt$Nombres et calculs$pt$))));
insert into public.curriculum_points (code, name, kind, exigence, regime_acquisition, rubrique, grade, display_order, node_id)
values ($pt$6-127$pt$, $pt$Compléter des égalités à trous multiplicatives$pt$, 'savoir_faire', 'attendu', 'diversite', $pt$Nombres, calcul et résolution de problèmes > Les fractions$pt$, '6', 27, (select id from public.classification_nodes where kind = 'subnotion' and name = $pt$définition$pt$ and parent_id = (select id from public.classification_nodes where kind = 'notion' and name = $pt$Fractions : sens et écritures$pt$ and parent_id = (select id from public.classification_nodes where kind = 'branch' and name = $pt$Nombres et calculs$pt$))));
insert into public.curriculum_points (code, name, kind, exigence, regime_acquisition, rubrique, grade, display_order, node_id)
values ($pt$6-128$pt$, $pt$Placer une fraction sur une demi-droite graduée dans des cas simples$pt$, 'savoir_faire', 'attendu', 'diversite', $pt$Nombres, calcul et résolution de problèmes > Les fractions$pt$, '6', 28, (select id from public.classification_nodes where kind = 'subnotion' and name = $pt$droite graduée$pt$ and parent_id = (select id from public.classification_nodes where kind = 'notion' and name = $pt$Fractions : sens et écritures$pt$ and parent_id = (select id from public.classification_nodes where kind = 'branch' and name = $pt$Nombres et calculs$pt$))));
insert into public.curriculum_points (code, name, kind, exigence, regime_acquisition, rubrique, grade, display_order, node_id)
values ($pt$6-129$pt$, $pt$Graduer un segment de longueur donnée$pt$, 'savoir_faire', 'attendu', 'diversite', $pt$Nombres, calcul et résolution de problèmes > Les fractions$pt$, '6', 29, (select id from public.classification_nodes where kind = 'subnotion' and name = $pt$droite graduée$pt$ and parent_id = (select id from public.classification_nodes where kind = 'notion' and name = $pt$Fractions : sens et écritures$pt$ and parent_id = (select id from public.classification_nodes where kind = 'branch' and name = $pt$Nombres et calculs$pt$))));
insert into public.curriculum_points (code, name, kind, exigence, regime_acquisition, rubrique, grade, display_order, node_id)
values ($pt$6-130$pt$, $pt$Savoir que la fraction a/b peut représenter un nombre entier, un nombre décimal non entier ou un nombre non décimal$pt$, 'connaissance', 'attendu', 'diversite', $pt$Nombres, calcul et résolution de problèmes > Les fractions$pt$, '6', 30, (select id from public.classification_nodes where kind = 'subnotion' and name = $pt$forme décimale$pt$ and parent_id = (select id from public.classification_nodes where kind = 'notion' and name = $pt$Fractions : sens et écritures$pt$ and parent_id = (select id from public.classification_nodes where kind = 'branch' and name = $pt$Nombres et calculs$pt$))));
insert into public.curriculum_points (code, name, kind, exigence, regime_acquisition, rubrique, grade, display_order, node_id)
values ($pt$6-131$pt$, $pt$Utiliser une multiplication pour appliquer une fraction à un nombre entier$pt$, 'savoir_faire', 'attendu', 'diversite', $pt$Nombres, calcul et résolution de problèmes > Les fractions$pt$, '6', 31, (select id from public.classification_nodes where kind = 'subnotion' and name = $pt$fraction d'une quantité$pt$ and parent_id = (select id from public.classification_nodes where kind = 'notion' and name = $pt$Fractions : calculs$pt$ and parent_id = (select id from public.classification_nodes where kind = 'branch' and name = $pt$Nombres et calculs$pt$))));
insert into public.curriculum_points (code, name, kind, exigence, regime_acquisition, rubrique, grade, display_order, node_id)
values ($pt$6-132$pt$, $pt$Établir des égalités de fractions$pt$, 'savoir_faire', 'attendu', 'diversite', $pt$Nombres, calcul et résolution de problèmes > Les fractions$pt$, '6', 32, (select id from public.classification_nodes where kind = 'subnotion' and name = $pt$égalité de fractions$pt$ and parent_id = (select id from public.classification_nodes where kind = 'notion' and name = $pt$Fractions : sens et écritures$pt$ and parent_id = (select id from public.classification_nodes where kind = 'branch' and name = $pt$Nombres et calculs$pt$))));
insert into public.curriculum_points (code, name, kind, exigence, regime_acquisition, rubrique, grade, display_order, node_id)
values ($pt$6-133$pt$, $pt$Comparer et encadrer des fractions$pt$, 'savoir_faire', 'attendu', 'diversite', $pt$Nombres, calcul et résolution de problèmes > Les fractions$pt$, '6', 33, (select id from public.classification_nodes where kind = 'subnotion' and name = $pt$comparer$pt$ and parent_id = (select id from public.classification_nodes where kind = 'notion' and name = $pt$Fractions : sens et écritures$pt$ and parent_id = (select id from public.classification_nodes where kind = 'branch' and name = $pt$Nombres et calculs$pt$))));
insert into public.curriculum_points (code, name, kind, exigence, regime_acquisition, rubrique, grade, display_order, node_id)
values ($pt$6-134$pt$, $pt$Ordonner une liste de nombres écrits sous forme de fractions ou de nombres mixtes$pt$, 'savoir_faire', 'attendu', 'diversite', $pt$Nombres, calcul et résolution de problèmes > Les fractions$pt$, '6', 34, (select id from public.classification_nodes where kind = 'subnotion' and name = $pt$comparer$pt$ and parent_id = (select id from public.classification_nodes where kind = 'notion' and name = $pt$Fractions : sens et écritures$pt$ and parent_id = (select id from public.classification_nodes where kind = 'branch' and name = $pt$Nombres et calculs$pt$))));
insert into public.curriculum_points (code, name, kind, exigence, regime_acquisition, rubrique, grade, display_order, node_id)
values ($pt$6-135$pt$, $pt$Additionner et soustraire des fractions$pt$, 'savoir_faire', 'attendu', 'diversite', $pt$Nombres, calcul et résolution de problèmes > Les fractions$pt$, '6', 35, (select id from public.classification_nodes where kind = 'subnotion' and name = $pt$additionner et soustraire$pt$ and parent_id = (select id from public.classification_nodes where kind = 'notion' and name = $pt$Fractions : calculs$pt$ and parent_id = (select id from public.classification_nodes where kind = 'branch' and name = $pt$Nombres et calculs$pt$))));
insert into public.curriculum_points (code, name, kind, exigence, regime_acquisition, rubrique, grade, display_order, node_id)
values ($pt$6-136$pt$, $pt$Multiplier une fraction par un nombre entier$pt$, 'savoir_faire', 'attendu', 'diversite', $pt$Nombres, calcul et résolution de problèmes > Les fractions$pt$, '6', 36, (select id from public.classification_nodes where kind = 'subnotion' and name = $pt$multiplier$pt$ and parent_id = (select id from public.classification_nodes where kind = 'notion' and name = $pt$Fractions : calculs$pt$ and parent_id = (select id from public.classification_nodes where kind = 'branch' and name = $pt$Nombres et calculs$pt$))));
insert into public.curriculum_points (code, name, kind, exigence, regime_acquisition, rubrique, grade, display_order, node_id)
values ($pt$6-137$pt$, $pt$Résoudre des problèmes mettant en jeu des fractions$pt$, 'savoir_faire', 'attendu', 'diversite', $pt$Nombres, calcul et résolution de problèmes > Les fractions$pt$, '6', 37, (select id from public.classification_nodes where kind = 'notion' and name = $pt$Fractions : calculs$pt$ and parent_id = (select id from public.classification_nodes where kind = 'branch' and name = $pt$Nombres et calculs$pt$)));
insert into public.curriculum_points (code, name, kind, exigence, regime_acquisition, rubrique, grade, display_order, node_id)
values ($pt$6-138$pt$, $pt$Inventer des problèmes mettant en jeu des fractions$pt$, 'savoir_faire', 'attendu', 'diversite', $pt$Nombres, calcul et résolution de problèmes > Les fractions$pt$, '6', 38, (select id from public.classification_nodes where kind = 'notion' and name = $pt$Fractions : calculs$pt$ and parent_id = (select id from public.classification_nodes where kind = 'branch' and name = $pt$Nombres et calculs$pt$)));
insert into public.curriculum_points (code, name, kind, exigence, regime_acquisition, rubrique, grade, display_order, node_id)
values ($pt$6-139$pt$, $pt$Comprendre le sens d'un pourcentage$pt$, 'connaissance', 'attendu', 'diversite', $pt$Nombres, calcul et résolution de problèmes > Les fractions$pt$, '6', 39, (select id from public.classification_nodes where kind = 'subnotion' and name = $pt$définition$pt$ and parent_id = (select id from public.classification_nodes where kind = 'notion' and name = $pt$Pourcentages$pt$ and parent_id = (select id from public.classification_nodes where kind = 'branch' and name = $pt$Proportionnalité$pt$))));
insert into public.curriculum_points (code, name, kind, exigence, regime_acquisition, rubrique, grade, display_order, node_id)
values ($pt$6-140$pt$, $pt$Calculer une proportion (rapport entre une partie et le tout) et l'exprimer sous forme de pourcentage dans des cas simples$pt$, 'savoir_faire', 'attendu', 'diversite', $pt$Nombres, calcul et résolution de problèmes > Les fractions$pt$, '6', 40, (select id from public.classification_nodes where kind = 'subnotion' and name = $pt$calculer$pt$ and parent_id = (select id from public.classification_nodes where kind = 'notion' and name = $pt$Pourcentages$pt$ and parent_id = (select id from public.classification_nodes where kind = 'branch' and name = $pt$Proportionnalité$pt$))));
insert into public.curriculum_points (code, name, kind, exigence, regime_acquisition, rubrique, grade, display_order, node_id)
values ($pt$6-141$pt$, $pt$Appliquer un pourcentage à une grandeur ou à un nombre$pt$, 'savoir_faire', 'attendu', 'diversite', $pt$Nombres, calcul et résolution de problèmes > Les fractions$pt$, '6', 41, (select id from public.classification_nodes where kind = 'subnotion' and name = $pt$calculer$pt$ and parent_id = (select id from public.classification_nodes where kind = 'notion' and name = $pt$Pourcentages$pt$ and parent_id = (select id from public.classification_nodes where kind = 'branch' and name = $pt$Proportionnalité$pt$))));
insert into public.curriculum_points (code, name, kind, exigence, regime_acquisition, rubrique, grade, display_order, node_id)
values ($pt$6-142$pt$, $pt$Utiliser des modèles pré-algébriques pour résoudre des problèmes algébriques$pt$, 'savoir_faire', 'attendu', 'diversite', $pt$Nombres, calcul et résolution de problèmes > Algèbre$pt$, '6', 42, (select id from public.classification_nodes where kind = 'subnotion' and name = $pt$nombre inconnu$pt$ and parent_id = (select id from public.classification_nodes where kind = 'notion' and name = $pt$Premiers pas algébriques$pt$ and parent_id = (select id from public.classification_nodes where kind = 'branch' and name = $pt$Algèbre$pt$))));
insert into public.curriculum_points (code, name, kind, exigence, regime_acquisition, rubrique, grade, display_order, node_id)
values ($pt$6-143$pt$, $pt$Identifier la structure d'un motif évolutif en repérant une régularité et en identifiant une structure$pt$, 'savoir_faire', 'attendu', 'diversite', $pt$Nombres, calcul et résolution de problèmes > Algèbre$pt$, '6', 43, (select id from public.classification_nodes where kind = 'subnotion' and name = $pt$suites de motifs$pt$ and parent_id = (select id from public.classification_nodes where kind = 'notion' and name = $pt$Premiers pas algébriques$pt$ and parent_id = (select id from public.classification_nodes where kind = 'branch' and name = $pt$Algèbre$pt$))));
insert into public.curriculum_points (code, name, kind, exigence, regime_acquisition, rubrique, grade, display_order, node_id)
values ($pt$6-144$pt$, $pt$Calculer le périmètre d'un carré et d'un rectangle$pt$, 'savoir_faire', 'attendu', 'fluence', $pt$Grandeurs et mesures > Les longueurs > Automatismes$pt$, '6', 44, (select id from public.classification_nodes where kind = 'notion' and name = $pt$Périmètres$pt$ and parent_id = (select id from public.classification_nodes where kind = 'branch' and name = $pt$Grandeurs et mesures$pt$)));
insert into public.curriculum_points (code, name, kind, exigence, regime_acquisition, rubrique, grade, display_order, node_id)
values ($pt$6-145$pt$, $pt$Savoir que le périmètre du disque est proportionnel à son diamètre$pt$, 'connaissance', 'attendu', 'diversite', $pt$Grandeurs et mesures > Les longueurs$pt$, '6', 45, (select id from public.classification_nodes where kind = 'subnotion' and name = $pt$disque$pt$ and parent_id = (select id from public.classification_nodes where kind = 'notion' and name = $pt$Périmètres$pt$ and parent_id = (select id from public.classification_nodes where kind = 'branch' and name = $pt$Grandeurs et mesures$pt$))));
insert into public.curriculum_points (code, name, kind, exigence, regime_acquisition, rubrique, grade, display_order, node_id)
values ($pt$6-146$pt$, $pt$Connaître la formule du périmètre d'un disque$pt$, 'connaissance', 'attendu', 'diversite', $pt$Grandeurs et mesures > Les longueurs$pt$, '6', 46, (select id from public.classification_nodes where kind = 'subnotion' and name = $pt$disque$pt$ and parent_id = (select id from public.classification_nodes where kind = 'notion' and name = $pt$Périmètres$pt$ and parent_id = (select id from public.classification_nodes where kind = 'branch' and name = $pt$Grandeurs et mesures$pt$))));
insert into public.curriculum_points (code, name, kind, exigence, regime_acquisition, rubrique, grade, display_order, node_id)
values ($pt$6-147$pt$, $pt$Calculer le périmètre d'un disque$pt$, 'savoir_faire', 'attendu', 'diversite', $pt$Grandeurs et mesures > Les longueurs$pt$, '6', 47, (select id from public.classification_nodes where kind = 'subnotion' and name = $pt$disque$pt$ and parent_id = (select id from public.classification_nodes where kind = 'notion' and name = $pt$Périmètres$pt$ and parent_id = (select id from public.classification_nodes where kind = 'branch' and name = $pt$Grandeurs et mesures$pt$))));
insert into public.curriculum_points (code, name, kind, exigence, regime_acquisition, rubrique, grade, display_order, node_id)
values ($pt$6-148$pt$, $pt$Calculer des périmètres de figures composées$pt$, 'savoir_faire', 'attendu', 'diversite', $pt$Grandeurs et mesures > Les longueurs$pt$, '6', 48, (select id from public.classification_nodes where kind = 'notion' and name = $pt$Périmètres$pt$ and parent_id = (select id from public.classification_nodes where kind = 'branch' and name = $pt$Grandeurs et mesures$pt$)));
insert into public.curriculum_points (code, name, kind, exigence, regime_acquisition, rubrique, grade, display_order, node_id)
values ($pt$6-149$pt$, $pt$Résoudre des problèmes impliquant des longueurs$pt$, 'savoir_faire', 'attendu', 'diversite', $pt$Grandeurs et mesures > Les longueurs$pt$, '6', 49, (select id from public.classification_nodes where kind = 'notion' and name = $pt$Longueurs$pt$ and parent_id = (select id from public.classification_nodes where kind = 'branch' and name = $pt$Grandeurs et mesures$pt$)));
insert into public.curriculum_points (code, name, kind, exigence, regime_acquisition, rubrique, grade, display_order, node_id)
values ($pt$6-150$pt$, $pt$Effectuer des conversions d'aire$pt$, 'savoir_faire', 'attendu', 'diversite', $pt$Grandeurs et mesures > Les aires$pt$, '6', 50, (select id from public.classification_nodes where kind = 'subnotion' and name = $pt$unités et conversions$pt$ and parent_id = (select id from public.classification_nodes where kind = 'notion' and name = $pt$Aires$pt$ and parent_id = (select id from public.classification_nodes where kind = 'branch' and name = $pt$Grandeurs et mesures$pt$))));
insert into public.curriculum_points (code, name, kind, exigence, regime_acquisition, rubrique, grade, display_order, node_id)
values ($pt$6-151$pt$, $pt$Connaître la formule de l'aire d'un carré ou d'un rectangle$pt$, 'connaissance', 'attendu', 'diversite', $pt$Grandeurs et mesures > Les aires$pt$, '6', 51, (select id from public.classification_nodes where kind = 'notion' and name = $pt$Aires$pt$ and parent_id = (select id from public.classification_nodes where kind = 'branch' and name = $pt$Grandeurs et mesures$pt$)));
insert into public.curriculum_points (code, name, kind, exigence, regime_acquisition, rubrique, grade, display_order, node_id)
values ($pt$6-152$pt$, $pt$Calculer l'aire d'un carré ou d'un rectangle$pt$, 'savoir_faire', 'attendu', 'diversite', $pt$Grandeurs et mesures > Les aires$pt$, '6', 52, (select id from public.classification_nodes where kind = 'notion' and name = $pt$Aires$pt$ and parent_id = (select id from public.classification_nodes where kind = 'branch' and name = $pt$Grandeurs et mesures$pt$)));
insert into public.curriculum_points (code, name, kind, exigence, regime_acquisition, rubrique, grade, display_order, node_id)
values ($pt$6-153$pt$, $pt$Connaître l'unité centimètre cube$pt$, 'connaissance', 'attendu', 'diversite', $pt$Grandeurs et mesures > Les volumes$pt$, '6', 53, (select id from public.classification_nodes where kind = 'subnotion' and name = $pt$conversions$pt$ and parent_id = (select id from public.classification_nodes where kind = 'notion' and name = $pt$Volumes$pt$ and parent_id = (select id from public.classification_nodes where kind = 'branch' and name = $pt$Grandeurs et mesures$pt$))));
insert into public.curriculum_points (code, name, kind, exigence, regime_acquisition, rubrique, grade, display_order, node_id)
values ($pt$6-154$pt$, $pt$Comparer des volumes$pt$, 'savoir_faire', 'attendu', 'diversite', $pt$Grandeurs et mesures > Les volumes$pt$, '6', 54, (select id from public.classification_nodes where kind = 'notion' and name = $pt$Volumes$pt$ and parent_id = (select id from public.classification_nodes where kind = 'branch' and name = $pt$Grandeurs et mesures$pt$)));
insert into public.curriculum_points (code, name, kind, exigence, regime_acquisition, rubrique, grade, display_order, node_id)
values ($pt$6-155$pt$, $pt$Déterminer un volume$pt$, 'savoir_faire', 'attendu', 'diversite', $pt$Grandeurs et mesures > Les volumes$pt$, '6', 55, (select id from public.classification_nodes where kind = 'notion' and name = $pt$Volumes$pt$ and parent_id = (select id from public.classification_nodes where kind = 'branch' and name = $pt$Grandeurs et mesures$pt$)));
insert into public.curriculum_points (code, name, kind, exigence, regime_acquisition, rubrique, grade, display_order, node_id)
values ($pt$6-156$pt$, $pt$Savoir combien de jours il y a dans une année (bissextile ou non), combien d'années il y a dans un siècle, et dans un millénaire$pt$, 'connaissance', 'attendu', 'fluence', $pt$Grandeurs et mesures > Le repérage dans le temps et les durées > Automatismes$pt$, '6', 56, (select id from public.classification_nodes where kind = 'subnotion' and name = $pt$convertir$pt$ and parent_id = (select id from public.classification_nodes where kind = 'notion' and name = $pt$Durées$pt$ and parent_id = (select id from public.classification_nodes where kind = 'branch' and name = $pt$Grandeurs et mesures$pt$))));
insert into public.curriculum_points (code, name, kind, exigence, regime_acquisition, rubrique, grade, display_order, node_id)
values ($pt$6-157$pt$, $pt$Effectuer des calculs sur des horaires et des durées$pt$, 'savoir_faire', 'attendu', 'diversite', $pt$Grandeurs et mesures > Le repérage dans le temps et les durées$pt$, '6', 57, (select id from public.classification_nodes where kind = 'subnotion' and name = $pt$calculer$pt$ and parent_id = (select id from public.classification_nodes where kind = 'notion' and name = $pt$Durées$pt$ and parent_id = (select id from public.classification_nodes where kind = 'branch' and name = $pt$Grandeurs et mesures$pt$))));
insert into public.curriculum_points (code, name, kind, exigence, regime_acquisition, rubrique, grade, display_order, node_id)
values ($pt$6-158$pt$, $pt$Résoudre des problèmes impliquant des horaires et des durées$pt$, 'savoir_faire', 'attendu', 'diversite', $pt$Grandeurs et mesures > Le repérage dans le temps et les durées$pt$, '6', 58, (select id from public.classification_nodes where kind = 'subnotion' and name = $pt$calculer$pt$ and parent_id = (select id from public.classification_nodes where kind = 'notion' and name = $pt$Durées$pt$ and parent_id = (select id from public.classification_nodes where kind = 'branch' and name = $pt$Grandeurs et mesures$pt$))));
insert into public.curriculum_points (code, name, kind, exigence, regime_acquisition, rubrique, grade, display_order, node_id)
values ($pt$6-159$pt$, $pt$Convertir des durées$pt$, 'savoir_faire', 'attendu', 'diversite', $pt$Grandeurs et mesures > Le repérage dans le temps et les durées$pt$, '6', 59, (select id from public.classification_nodes where kind = 'subnotion' and name = $pt$convertir$pt$ and parent_id = (select id from public.classification_nodes where kind = 'notion' and name = $pt$Durées$pt$ and parent_id = (select id from public.classification_nodes where kind = 'branch' and name = $pt$Grandeurs et mesures$pt$))));
insert into public.curriculum_points (code, name, kind, exigence, regime_acquisition, rubrique, grade, display_order, node_id)
values ($pt$6-160$pt$, $pt$Connaître et utiliser la définition de la distance entre deux points$pt$, 'savoir_faire', 'attendu', 'diversite', $pt$Espace et géométrie > Étude de configurations planes$pt$, '6', 60, (select id from public.classification_nodes where kind = 'subnotion' and name = $pt$cercle$pt$ and parent_id = (select id from public.classification_nodes where kind = 'notion' and name = $pt$Figures planes$pt$ and parent_id = (select id from public.classification_nodes where kind = 'branch' and name = $pt$Géométrie$pt$))));
insert into public.curriculum_points (code, name, kind, exigence, regime_acquisition, rubrique, grade, display_order, node_id)
values ($pt$6-161$pt$, $pt$Connaître et utiliser la définition du milieu d'un segment$pt$, 'savoir_faire', 'attendu', 'diversite', $pt$Espace et géométrie > Étude de configurations planes$pt$, '6', 61, (select id from public.classification_nodes where kind = 'subnotion' and name = $pt$cercle$pt$ and parent_id = (select id from public.classification_nodes where kind = 'notion' and name = $pt$Figures planes$pt$ and parent_id = (select id from public.classification_nodes where kind = 'branch' and name = $pt$Géométrie$pt$))));
insert into public.curriculum_points (code, name, kind, exigence, regime_acquisition, rubrique, grade, display_order, node_id)
values ($pt$6-162$pt$, $pt$Connaître les définitions d'un cercle, d'un disque, d'un rayon, d'un diamètre, d'une corde$pt$, 'connaissance', 'attendu', 'diversite', $pt$Espace et géométrie > Étude de configurations planes$pt$, '6', 62, (select id from public.classification_nodes where kind = 'subnotion' and name = $pt$cercle$pt$ and parent_id = (select id from public.classification_nodes where kind = 'notion' and name = $pt$Figures planes$pt$ and parent_id = (select id from public.classification_nodes where kind = 'branch' and name = $pt$Géométrie$pt$))));
insert into public.curriculum_points (code, name, kind, exigence, regime_acquisition, rubrique, grade, display_order, node_id)
values ($pt$6-163$pt$, $pt$Comprendre la définition d'un cercle et celle d'un disque sous la forme d'ensembles de points$pt$, 'connaissance', 'attendu', 'diversite', $pt$Espace et géométrie > Étude de configurations planes$pt$, '6', 63, (select id from public.classification_nodes where kind = 'subnotion' and name = $pt$cercle$pt$ and parent_id = (select id from public.classification_nodes where kind = 'notion' and name = $pt$Figures planes$pt$ and parent_id = (select id from public.classification_nodes where kind = 'branch' and name = $pt$Géométrie$pt$))));
insert into public.curriculum_points (code, name, kind, exigence, regime_acquisition, rubrique, grade, display_order, node_id)
values ($pt$6-164$pt$, $pt$Résoudre des problèmes mettant en jeu des distances à un point$pt$, 'savoir_faire', 'attendu', 'diversite', $pt$Espace et géométrie > Étude de configurations planes$pt$, '6', 64, (select id from public.classification_nodes where kind = 'subnotion' and name = $pt$cercle$pt$ and parent_id = (select id from public.classification_nodes where kind = 'notion' and name = $pt$Figures planes$pt$ and parent_id = (select id from public.classification_nodes where kind = 'branch' and name = $pt$Géométrie$pt$))));
insert into public.curriculum_points (code, name, kind, exigence, regime_acquisition, rubrique, grade, display_order, node_id)
values ($pt$6-165$pt$, $pt$Connaître la définition de la médiatrice d'un segment$pt$, 'connaissance', 'attendu', 'diversite', $pt$Espace et géométrie > Étude de configurations planes$pt$, '6', 65, (select id from public.classification_nodes where kind = 'subnotion' and name = $pt$médiatrice et bissectrice$pt$ and parent_id = (select id from public.classification_nodes where kind = 'notion' and name = $pt$Figures planes$pt$ and parent_id = (select id from public.classification_nodes where kind = 'branch' and name = $pt$Géométrie$pt$))));
insert into public.curriculum_points (code, name, kind, exigence, regime_acquisition, rubrique, grade, display_order, node_id)
values ($pt$6-166$pt$, $pt$Comprendre et utiliser la propriété caractéristique de la médiatrice d'un segment$pt$, 'savoir_faire', 'attendu', 'diversite', $pt$Espace et géométrie > Étude de configurations planes$pt$, '6', 66, (select id from public.classification_nodes where kind = 'subnotion' and name = $pt$médiatrice et bissectrice$pt$ and parent_id = (select id from public.classification_nodes where kind = 'notion' and name = $pt$Figures planes$pt$ and parent_id = (select id from public.classification_nodes where kind = 'branch' and name = $pt$Géométrie$pt$))));
insert into public.curriculum_points (code, name, kind, exigence, regime_acquisition, rubrique, grade, display_order, node_id)
values ($pt$6-167$pt$, $pt$Résoudre des problèmes en s'appuyant sur la propriété caractéristique de la médiatrice$pt$, 'savoir_faire', 'attendu', 'diversite', $pt$Espace et géométrie > Étude de configurations planes$pt$, '6', 67, (select id from public.classification_nodes where kind = 'subnotion' and name = $pt$médiatrice et bissectrice$pt$ and parent_id = (select id from public.classification_nodes where kind = 'notion' and name = $pt$Figures planes$pt$ and parent_id = (select id from public.classification_nodes where kind = 'branch' and name = $pt$Géométrie$pt$))));
insert into public.curriculum_points (code, name, kind, exigence, regime_acquisition, rubrique, grade, display_order, node_id)
values ($pt$6-168$pt$, $pt$Connaître et utiliser les angles ainsi que le lexique et les notations qui s'y rapportent : angle droit, angle plat, angle plein, angle nul, angle aigu, angle obtus, angles opposés par le sommet, angles adjacents, angles supplémentaires$pt$, 'savoir_faire', 'attendu', 'diversite', $pt$Espace et géométrie > Étude de configurations planes$pt$, '6', 68, (select id from public.classification_nodes where kind = 'notion' and name = $pt$Angles$pt$ and parent_id = (select id from public.classification_nodes where kind = 'branch' and name = $pt$Grandeurs et mesures$pt$)));
insert into public.curriculum_points (code, name, kind, exigence, regime_acquisition, rubrique, grade, display_order, node_id)
values ($pt$6-169$pt$, $pt$Mesurer un angle$pt$, 'savoir_faire', 'attendu', 'diversite', $pt$Espace et géométrie > Étude de configurations planes$pt$, '6', 69, (select id from public.classification_nodes where kind = 'subnotion' and name = $pt$mesurer en degrés$pt$ and parent_id = (select id from public.classification_nodes where kind = 'notion' and name = $pt$Angles$pt$ and parent_id = (select id from public.classification_nodes where kind = 'branch' and name = $pt$Grandeurs et mesures$pt$))));
insert into public.curriculum_points (code, name, kind, exigence, regime_acquisition, rubrique, grade, display_order, node_id)
values ($pt$6-170$pt$, $pt$Construire un angle de mesure donnée$pt$, 'savoir_faire', 'attendu', 'diversite', $pt$Espace et géométrie > Étude de configurations planes$pt$, '6', 70, (select id from public.classification_nodes where kind = 'subnotion' and name = $pt$construire$pt$ and parent_id = (select id from public.classification_nodes where kind = 'notion' and name = $pt$Angles$pt$ and parent_id = (select id from public.classification_nodes where kind = 'branch' and name = $pt$Grandeurs et mesures$pt$))));
insert into public.curriculum_points (code, name, kind, exigence, regime_acquisition, rubrique, grade, display_order, node_id)
values ($pt$6-171$pt$, $pt$Connaître la définition de la bissectrice d'un angle saillant$pt$, 'connaissance', 'attendu', 'diversite', $pt$Espace et géométrie > Étude de configurations planes$pt$, '6', 71, (select id from public.classification_nodes where kind = 'subnotion' and name = $pt$médiatrice et bissectrice$pt$ and parent_id = (select id from public.classification_nodes where kind = 'notion' and name = $pt$Figures planes$pt$ and parent_id = (select id from public.classification_nodes where kind = 'branch' and name = $pt$Géométrie$pt$))));
insert into public.curriculum_points (code, name, kind, exigence, regime_acquisition, rubrique, grade, display_order, node_id)
values ($pt$6-172$pt$, $pt$Utiliser la définition de la bissectrice d'un angle pour effectuer des constructions et résoudre des problèmes$pt$, 'savoir_faire', 'attendu', 'diversite', $pt$Espace et géométrie > Étude de configurations planes$pt$, '6', 72, (select id from public.classification_nodes where kind = 'subnotion' and name = $pt$médiatrice et bissectrice$pt$ and parent_id = (select id from public.classification_nodes where kind = 'notion' and name = $pt$Figures planes$pt$ and parent_id = (select id from public.classification_nodes where kind = 'branch' and name = $pt$Géométrie$pt$))));
insert into public.curriculum_points (code, name, kind, exigence, regime_acquisition, rubrique, grade, display_order, node_id)
values ($pt$6-173$pt$, $pt$Construire des triangles$pt$, 'savoir_faire', 'attendu', 'diversite', $pt$Espace et géométrie > Étude de configurations planes$pt$, '6', 73, (select id from public.classification_nodes where kind = 'subnotion' and name = $pt$triangles$pt$ and parent_id = (select id from public.classification_nodes where kind = 'notion' and name = $pt$Figures planes$pt$ and parent_id = (select id from public.classification_nodes where kind = 'branch' and name = $pt$Géométrie$pt$))));
insert into public.curriculum_points (code, name, kind, exigence, regime_acquisition, rubrique, grade, display_order, node_id)
values ($pt$6-174$pt$, $pt$Connaître et utiliser les propriétés angulaires des triangles particuliers : triangle rectangle, triangle isocèle, triangle équilatéral$pt$, 'savoir_faire', 'attendu', 'diversite', $pt$Espace et géométrie > Étude de configurations planes$pt$, '6', 74, (select id from public.classification_nodes where kind = 'subnotion' and name = $pt$triangles$pt$ and parent_id = (select id from public.classification_nodes where kind = 'notion' and name = $pt$Figures planes$pt$ and parent_id = (select id from public.classification_nodes where kind = 'branch' and name = $pt$Géométrie$pt$))));
insert into public.curriculum_points (code, name, kind, exigence, regime_acquisition, rubrique, grade, display_order, node_id)
values ($pt$6-175$pt$, $pt$Connaître la valeur de la somme des mesures des angles d'un triangle$pt$, 'connaissance', 'attendu', 'diversite', $pt$Espace et géométrie > Étude de configurations planes$pt$, '6', 75, (select id from public.classification_nodes where kind = 'subnotion' and name = $pt$triangles$pt$ and parent_id = (select id from public.classification_nodes where kind = 'notion' and name = $pt$Figures planes$pt$ and parent_id = (select id from public.classification_nodes where kind = 'branch' and name = $pt$Géométrie$pt$))));
insert into public.curriculum_points (code, name, kind, exigence, regime_acquisition, rubrique, grade, display_order, node_id)
values ($pt$6-176$pt$, $pt$L'utiliser pour calculer des angles, effectuer des constructions et résoudre des problèmes$pt$, 'savoir_faire', 'attendu', 'diversite', $pt$Espace et géométrie > Étude de configurations planes$pt$, '6', 76, (select id from public.classification_nodes where kind = 'subnotion' and name = $pt$triangles$pt$ and parent_id = (select id from public.classification_nodes where kind = 'notion' and name = $pt$Figures planes$pt$ and parent_id = (select id from public.classification_nodes where kind = 'branch' and name = $pt$Géométrie$pt$))));
insert into public.curriculum_points (code, name, kind, exigence, regime_acquisition, rubrique, grade, display_order, node_id)
values ($pt$6-177$pt$, $pt$Savoir que les médiatrices d'un triangle sont concourantes$pt$, 'connaissance', 'attendu', 'diversite', $pt$Espace et géométrie > Étude de configurations planes$pt$, '6', 77, (select id from public.classification_nodes where kind = 'subnotion' and name = $pt$triangles$pt$ and parent_id = (select id from public.classification_nodes where kind = 'notion' and name = $pt$Figures planes$pt$ and parent_id = (select id from public.classification_nodes where kind = 'branch' and name = $pt$Géométrie$pt$))));
insert into public.curriculum_points (code, name, kind, exigence, regime_acquisition, rubrique, grade, display_order, node_id)
values ($pt$6-178$pt$, $pt$Connaître et construire le cercle circonscrit à un triangle$pt$, 'savoir_faire', 'attendu', 'diversite', $pt$Espace et géométrie > Étude de configurations planes$pt$, '6', 78, (select id from public.classification_nodes where kind = 'subnotion' and name = $pt$triangles$pt$ and parent_id = (select id from public.classification_nodes where kind = 'notion' and name = $pt$Figures planes$pt$ and parent_id = (select id from public.classification_nodes where kind = 'branch' and name = $pt$Géométrie$pt$))));
insert into public.curriculum_points (code, name, kind, exigence, regime_acquisition, rubrique, grade, display_order, node_id)
values ($pt$6-179$pt$, $pt$Connaître la définition du symétrique d'un point par rapport à une droite$pt$, 'connaissance', 'attendu', 'diversite', $pt$Espace et géométrie > Étude de configurations planes$pt$, '6', 79, (select id from public.classification_nodes where kind = 'notion' and name = $pt$Symétrie axiale$pt$ and parent_id = (select id from public.classification_nodes where kind = 'branch' and name = $pt$Géométrie$pt$)));
insert into public.curriculum_points (code, name, kind, exigence, regime_acquisition, rubrique, grade, display_order, node_id)
values ($pt$6-180$pt$, $pt$Connaître et utiliser les propriétés de la symétrie axiale pour effectuer des constructions$pt$, 'savoir_faire', 'attendu', 'diversite', $pt$Espace et géométrie > Étude de configurations planes$pt$, '6', 80, (select id from public.classification_nodes where kind = 'notion' and name = $pt$Symétrie axiale$pt$ and parent_id = (select id from public.classification_nodes where kind = 'branch' and name = $pt$Géométrie$pt$)));
insert into public.curriculum_points (code, name, kind, exigence, regime_acquisition, rubrique, grade, display_order, node_id)
values ($pt$6-181$pt$, $pt$Voir dans l'espace des assemblages de cubes$pt$, 'savoir_faire', 'attendu', 'diversite', $pt$Espace et géométrie > La vision dans l'espace$pt$, '6', 81, (select id from public.classification_nodes where kind = 'notion' and name = $pt$Solides$pt$ and parent_id = (select id from public.classification_nodes where kind = 'branch' and name = $pt$Géométrie$pt$)));
insert into public.curriculum_points (code, name, kind, exigence, regime_acquisition, rubrique, grade, display_order, node_id)
values ($pt$6-182$pt$, $pt$Planifier une enquête et recueillir des données$pt$, 'savoir_faire', 'attendu', 'diversite', $pt$Organisation et gestion de données et probabilités > Organisation et gestion de données$pt$, '6', 82, (select id from public.classification_nodes where kind = 'notion' and name = $pt$Représenter des données$pt$ and parent_id = (select id from public.classification_nodes where kind = 'branch' and name = $pt$Statistiques$pt$)));
insert into public.curriculum_points (code, name, kind, exigence, regime_acquisition, rubrique, grade, display_order, node_id)
values ($pt$6-183$pt$, $pt$Réaliser des mesures et les consigner dans un tableau$pt$, 'savoir_faire', 'attendu', 'diversite', $pt$Organisation et gestion de données et probabilités > Organisation et gestion de données$pt$, '6', 83, (select id from public.classification_nodes where kind = 'subnotion' and name = $pt$tableaux$pt$ and parent_id = (select id from public.classification_nodes where kind = 'notion' and name = $pt$Représenter des données$pt$ and parent_id = (select id from public.classification_nodes where kind = 'branch' and name = $pt$Statistiques$pt$))));
insert into public.curriculum_points (code, name, kind, exigence, regime_acquisition, rubrique, grade, display_order, node_id)
values ($pt$6-184$pt$, $pt$Construire un tableau simple pour présenter des données (observations, caractères)$pt$, 'savoir_faire', 'attendu', 'diversite', $pt$Organisation et gestion de données et probabilités > Organisation et gestion de données$pt$, '6', 84, (select id from public.classification_nodes where kind = 'subnotion' and name = $pt$tableaux$pt$ and parent_id = (select id from public.classification_nodes where kind = 'notion' and name = $pt$Représenter des données$pt$ and parent_id = (select id from public.classification_nodes where kind = 'branch' and name = $pt$Statistiques$pt$))));
insert into public.curriculum_points (code, name, kind, exigence, regime_acquisition, rubrique, grade, display_order, node_id)
values ($pt$6-185$pt$, $pt$Faire un choix en filtrant les données d'un tableau selon un critère$pt$, 'savoir_faire', 'attendu', 'diversite', $pt$Organisation et gestion de données et probabilités > Organisation et gestion de données$pt$, '6', 85, (select id from public.classification_nodes where kind = 'subnotion' and name = $pt$tableaux$pt$ and parent_id = (select id from public.classification_nodes where kind = 'notion' and name = $pt$Représenter des données$pt$ and parent_id = (select id from public.classification_nodes where kind = 'branch' and name = $pt$Statistiques$pt$))));
insert into public.curriculum_points (code, name, kind, exigence, regime_acquisition, rubrique, grade, display_order, node_id)
values ($pt$6-186$pt$, $pt$Savoir que la probabilité d'un évènement est un nombre compris entre 0 et 1$pt$, 'connaissance', 'attendu', 'diversite', $pt$Organisation et gestion de données et probabilités > Les probabilités$pt$, '6', 86, (select id from public.classification_nodes where kind = 'subnotion' and name = $pt$probabilité simple$pt$ and parent_id = (select id from public.classification_nodes where kind = 'notion' and name = $pt$Expériences aléatoires$pt$ and parent_id = (select id from public.classification_nodes where kind = 'branch' and name = $pt$Probabilités$pt$))));
insert into public.curriculum_points (code, name, kind, exigence, regime_acquisition, rubrique, grade, display_order, node_id)
values ($pt$6-187$pt$, $pt$Calculer des probabilités dans des situations simples d'équiprobabilité$pt$, 'savoir_faire', 'attendu', 'diversite', $pt$Organisation et gestion de données et probabilités > Les probabilités$pt$, '6', 87, (select id from public.classification_nodes where kind = 'subnotion' and name = $pt$équiprobabilité$pt$ and parent_id = (select id from public.classification_nodes where kind = 'notion' and name = $pt$Expériences aléatoires$pt$ and parent_id = (select id from public.classification_nodes where kind = 'branch' and name = $pt$Probabilités$pt$))));
insert into public.curriculum_points (code, name, kind, exigence, regime_acquisition, rubrique, grade, display_order, node_id)
values ($pt$6-188$pt$, $pt$Comparer des résultats d'une expérience aléatoire répétée à une probabilité calculée$pt$, 'savoir_faire', 'attendu', 'diversite', $pt$Organisation et gestion de données et probabilités > Les probabilités$pt$, '6', 88, (select id from public.classification_nodes where kind = 'subnotion' and name = $pt$fréquences$pt$ and parent_id = (select id from public.classification_nodes where kind = 'notion' and name = $pt$Expériences aléatoires$pt$ and parent_id = (select id from public.classification_nodes where kind = 'branch' and name = $pt$Probabilités$pt$))));
insert into public.curriculum_points (code, name, kind, exigence, regime_acquisition, rubrique, grade, display_order, node_id)
values ($pt$6-189$pt$, $pt$Connaître la définition de la proportionnalité entre deux grandeurs et la mettre en lien avec des expressions de la vie courante$pt$, 'savoir_faire', 'attendu', 'diversite', $pt$La proportionnalité$pt$, '6', 89, (select id from public.classification_nodes where kind = 'subnotion' and name = $pt$reconnaître$pt$ and parent_id = (select id from public.classification_nodes where kind = 'notion' and name = $pt$Situations de proportionnalité$pt$ and parent_id = (select id from public.classification_nodes where kind = 'branch' and name = $pt$Proportionnalité$pt$))));
insert into public.curriculum_points (code, name, kind, exigence, regime_acquisition, rubrique, grade, display_order, node_id)
values ($pt$6-190$pt$, $pt$Identifier si une situation relève du « modèle » de la proportionnalité$pt$, 'savoir_faire', 'attendu', 'diversite', $pt$La proportionnalité$pt$, '6', 90, (select id from public.classification_nodes where kind = 'subnotion' and name = $pt$reconnaître$pt$ and parent_id = (select id from public.classification_nodes where kind = 'notion' and name = $pt$Situations de proportionnalité$pt$ and parent_id = (select id from public.classification_nodes where kind = 'branch' and name = $pt$Proportionnalité$pt$))));
insert into public.curriculum_points (code, name, kind, exigence, regime_acquisition, rubrique, grade, display_order, node_id)
values ($pt$6-191$pt$, $pt$Résoudre un problème de proportionnalité en choisissant une procédure adaptée : propriété de linéarité pour la multiplication ou l'addition, retour à l'unité$pt$, 'savoir_faire', 'attendu', 'diversite', $pt$La proportionnalité$pt$, '6', 91, (select id from public.classification_nodes where kind = 'subnotion' and name = $pt$appliquer$pt$ and parent_id = (select id from public.classification_nodes where kind = 'notion' and name = $pt$Situations de proportionnalité$pt$ and parent_id = (select id from public.classification_nodes where kind = 'branch' and name = $pt$Proportionnalité$pt$))));
insert into public.curriculum_points (code, name, kind, exigence, regime_acquisition, rubrique, grade, display_order, node_id)
values ($pt$6-192$pt$, $pt$Représenter une situation de proportionnalité à l'aide d'un tableau ou de notations symboliques$pt$, 'savoir_faire', 'attendu', 'diversite', $pt$La proportionnalité$pt$, '6', 92, (select id from public.classification_nodes where kind = 'notion' and name = $pt$Situations de proportionnalité$pt$ and parent_id = (select id from public.classification_nodes where kind = 'branch' and name = $pt$Proportionnalité$pt$)));
insert into public.curriculum_points (code, name, kind, exigence, regime_acquisition, rubrique, grade, display_order, node_id)
values ($pt$6-193$pt$, $pt$S'initier à la résolution de problèmes d'échelles$pt$, 'savoir_faire', 'attendu', 'diversite', $pt$La proportionnalité$pt$, '6', 93, (select id from public.classification_nodes where kind = 'notion' and name = $pt$Échelle d'une carte$pt$ and parent_id = (select id from public.classification_nodes where kind = 'branch' and name = $pt$Proportionnalité$pt$)));
insert into public.curriculum_points (code, name, kind, exigence, regime_acquisition, rubrique, grade, display_order, node_id)
values ($pt$6-194$pt$, $pt$Identifier une instruction ou une séquence d'instructions$pt$, 'algorithme', 'attendu', 'diversite', $pt$Initiation à la pensée informatique$pt$, '6', 94, (select id from public.classification_nodes where kind = 'notion' and name = $pt$Préalgorithmique$pt$ and parent_id = (select id from public.classification_nodes where kind = 'branch' and name = $pt$Algorithmique$pt$)));
insert into public.curriculum_points (code, name, kind, exigence, regime_acquisition, rubrique, grade, display_order, node_id)
values ($pt$6-195$pt$, $pt$Produire et exécuter une séquence d'instructions$pt$, 'algorithme', 'attendu', 'diversite', $pt$Initiation à la pensée informatique$pt$, '6', 95, (select id from public.classification_nodes where kind = 'notion' and name = $pt$Préalgorithmique$pt$ and parent_id = (select id from public.classification_nodes where kind = 'branch' and name = $pt$Algorithmique$pt$)));
insert into public.curriculum_points (code, name, kind, exigence, regime_acquisition, rubrique, grade, display_order, node_id)
values ($pt$6-196$pt$, $pt$Répéter à la main une séquence d'instructions pour accomplir une tâche imposée$pt$, 'algorithme', 'attendu', 'diversite', $pt$Initiation à la pensée informatique$pt$, '6', 96, (select id from public.classification_nodes where kind = 'notion' and name = $pt$Préalgorithmique$pt$ and parent_id = (select id from public.classification_nodes where kind = 'branch' and name = $pt$Algorithmique$pt$)));
insert into public.curriculum_points (code, name, kind, exigence, regime_acquisition, rubrique, grade, display_order, node_id)
values ($pt$6-197$pt$, $pt$Programmer la construction d'un chemin simple$pt$, 'algorithme', 'attendu', 'diversite', $pt$Initiation à la pensée informatique$pt$, '6', 97, (select id from public.classification_nodes where kind = 'notion' and name = $pt$Préalgorithmique$pt$ and parent_id = (select id from public.classification_nodes where kind = 'branch' and name = $pt$Algorithmique$pt$)));

-- ---- 2. Les 28 références d'automatismes (listes de la 6e) ------------------
-- Un code introuvable insérerait 0 ligne EN SILENCE : le bloc DO final compte.
insert into public.curriculum_point_automatismes (point_id, grade)
select p.id, '6' from public.curriculum_points p where p.code = $pt$CE1-062$pt$;
insert into public.curriculum_point_automatismes (point_id, grade)
select p.id, '6' from public.curriculum_points p where p.code = $pt$CE2-022$pt$;
insert into public.curriculum_point_automatismes (point_id, grade)
select p.id, '6' from public.curriculum_points p where p.code = $pt$CE2-042$pt$;
insert into public.curriculum_point_automatismes (point_id, grade)
select p.id, '6' from public.curriculum_points p where p.code = $pt$CE2-043$pt$;
insert into public.curriculum_point_automatismes (point_id, grade)
select p.id, '6' from public.curriculum_points p where p.code = $pt$CM1-067$pt$;
insert into public.curriculum_point_automatismes (point_id, grade)
select p.id, '6' from public.curriculum_points p where p.code = $pt$CM1-068$pt$;
insert into public.curriculum_point_automatismes (point_id, grade)
select p.id, '6' from public.curriculum_points p where p.code = $pt$CM1-106$pt$;
insert into public.curriculum_point_automatismes (point_id, grade)
select p.id, '6' from public.curriculum_points p where p.code = $pt$CM2-008$pt$;
insert into public.curriculum_point_automatismes (point_id, grade)
select p.id, '6' from public.curriculum_points p where p.code = $pt$CM2-013$pt$;
insert into public.curriculum_point_automatismes (point_id, grade)
select p.id, '6' from public.curriculum_points p where p.code = $pt$CM2-021$pt$;
insert into public.curriculum_point_automatismes (point_id, grade)
select p.id, '6' from public.curriculum_points p where p.code = $pt$CM2-022$pt$;
insert into public.curriculum_point_automatismes (point_id, grade)
select p.id, '6' from public.curriculum_points p where p.code = $pt$CM2-024$pt$;
insert into public.curriculum_point_automatismes (point_id, grade)
select p.id, '6' from public.curriculum_points p where p.code = $pt$CM2-030$pt$;
insert into public.curriculum_point_automatismes (point_id, grade)
select p.id, '6' from public.curriculum_points p where p.code = $pt$CM2-038$pt$;
insert into public.curriculum_point_automatismes (point_id, grade)
select p.id, '6' from public.curriculum_points p where p.code = $pt$CM2-039$pt$;
insert into public.curriculum_point_automatismes (point_id, grade)
select p.id, '6' from public.curriculum_points p where p.code = $pt$CM2-042$pt$;
insert into public.curriculum_point_automatismes (point_id, grade)
select p.id, '6' from public.curriculum_points p where p.code = $pt$CM2-043$pt$;
insert into public.curriculum_point_automatismes (point_id, grade)
select p.id, '6' from public.curriculum_points p where p.code = $pt$CM2-061$pt$;
insert into public.curriculum_point_automatismes (point_id, grade)
select p.id, '6' from public.curriculum_points p where p.code = $pt$CM2-071$pt$;
insert into public.curriculum_point_automatismes (point_id, grade)
select p.id, '6' from public.curriculum_points p where p.code = $pt$CM2-072$pt$;
insert into public.curriculum_point_automatismes (point_id, grade)
select p.id, '6' from public.curriculum_points p where p.code = $pt$CM2-073$pt$;
insert into public.curriculum_point_automatismes (point_id, grade)
select p.id, '6' from public.curriculum_points p where p.code = $pt$CM2-074$pt$;
insert into public.curriculum_point_automatismes (point_id, grade)
select p.id, '6' from public.curriculum_points p where p.code = $pt$CM2-082$pt$;
insert into public.curriculum_point_automatismes (point_id, grade)
select p.id, '6' from public.curriculum_points p where p.code = $pt$CM2-083$pt$;
insert into public.curriculum_point_automatismes (point_id, grade)
select p.id, '6' from public.curriculum_points p where p.code = $pt$CM2-088$pt$;
insert into public.curriculum_point_automatismes (point_id, grade)
select p.id, '6' from public.curriculum_points p where p.code = $pt$CM2-092$pt$;
insert into public.curriculum_point_automatismes (point_id, grade)
select p.id, '6' from public.curriculum_points p where p.code = $pt$CM2-098$pt$;
insert into public.curriculum_point_automatismes (point_id, grade)
select p.id, '6' from public.curriculum_points p where p.code = $pt$CM2-107$pt$;

-- ---- 3. Vérifications (la migration échoue si le compte n'y est pas) --------

do $check$
declare
	v_points integer;
	v_sans_noeud integer;
	v_refs integer;
	v_fluence integer;
	v_algo integer;
	v_anciens integer;
begin
	select count(*) into v_points from public.curriculum_points where grade = '6';
	select count(*) into v_sans_noeud from public.curriculum_points
	 where grade = '6' and node_id is null;
	select count(*) into v_refs from public.curriculum_point_automatismes where grade = '6';
	select count(*) into v_fluence from public.curriculum_points
	 where grade = '6' and regime_acquisition = 'fluence';
	select count(*) into v_algo from public.curriculum_points
	 where grade = '6' and kind = 'algorithme';
	-- Les 95 points de l'ancien seed 2020 (6-001…6-095, rattachés aux objectifs)
	-- restent INTACTS jusqu'à l'étape 4 de C5 (décision R5 = B).
	select count(*) into v_anciens from public.curriculum_points
	 where code like '6-0%' and objective_id is not null;
	if v_points <> 97 or v_sans_noeud <> 0 or v_refs <> 28
	   or v_fluence <> 2 or v_algo <> 4 or v_anciens <> 95 then
		raise exception 'seed 6e incohérent : points=%, sans nœud=%, réfs=%, fluence=%, algo=%, anciens=%',
			v_points, v_sans_noeud, v_refs, v_fluence, v_algo, v_anciens;
	end if;
end $check$;
